// src/middleware/structured-logging.js
//
// Express middleware for structured JSON logging with trace context
// Logs all requests/responses in unified schema with correlation IDs
//
// Generated by: Phase 3 observability spine - TASK 6 (Backend Instrumentation)

const { trace } = require('@opentelemetry/api');

/**
 * Create structured logging middleware
 * Logs all HTTP requests/responses in unified JSON format with trace context
 */
function createStructuredLoggingMiddleware(logger = console) {
  return (req, res, next) => {
    const startTime = Date.now();
    
    // Get trace context
    const span = trace.getActiveSpan();
    const traceId = req.traceId || (span ? span.spanContext().traceId : null);
    const spanId = req.spanId || (span ? span.spanContext().spanId : null);
    
    // Extract metadata from request
    const requestMetadata = {
      timestamp: new Date().toISOString(),
      service: 'code-server-backend',
      level: 'INFO',
      type: 'http_request',
      trace_id: traceId,
      span_id: spanId,
      
      http_request: {
        method: req.method,
        path: req.path,
        url: req.originalUrl,
        query: Object.keys(req.query).length > 0 ? req.query : undefined,
        headers: {
          content_type: req.headers['content-type'],
          user_agent: req.headers['user-agent'],
          accept: req.headers['accept'],
        },
        remote_addr: req.ip || req.connection.remoteAddress,
      },
      
      user: {
        id: req.user?.id || req.sessionID || 'anonymous',
        session_id: req.sessionID || undefined,
        email: req.user?.email || undefined,
      },
      
      request_body_size: req.headers['content-length'] || 0,
    };

    // Intercept response.send to capture response data
    const originalSend = res.send;
    
    res.send = function(data) {
      const duration = Date.now() - startTime;
      
      // Log response
      const responseMetadata = {
        ...requestMetadata,
        type: 'http_response',
        http_response: {
          status_code: res.statusCode,
          status_message: res.statusMessage || 'OK',
        },
        performance: {
          duration_ms: duration,
        },
        response_body_size: Buffer.byteLength(
          typeof data === 'string' ? data : JSON.stringify(data)
        ),
      };

      // Log to structured logger
      logger.log(JSON.stringify(responseMetadata));

      // Call original send
      return originalSend.call(this, data);
    };

    // Also handle json() responses
    const originalJson = res.json;
    
    res.json = function(data) {
      const duration = Date.now() - startTime;
      
      // Log response
      const responseMetadata = {
        ...requestMetadata,
        type: 'http_response',
        http_response: {
          status_code: res.statusCode,
          status_message: res.statusMessage || 'OK',
        },
        performance: {
          duration_ms: duration,
        },
        response_body_size: Buffer.byteLength(JSON.stringify(data)),
      };

      // Log to structured logger
      logger.log(JSON.stringify(responseMetadata));

      // Call original json
      return originalJson.call(this, data);
    };

    // Log request (optional - for request debugging)
    // Commented out by default to reduce noise
    // logger.log(JSON.stringify(requestMetadata));

    next();
  };
}

/**
 * Create error logging middleware
 * Logs errors with full trace context and stack traces
 */
function createErrorLoggingMiddleware(logger = console) {
  return (err, req, res, next) => {
    const span = trace.getActiveSpan();
    const traceId = req.traceId || (span ? span.spanContext().traceId : null);
    const spanId = req.spanId || (span ? span.spanContext().spanId : null);
    
    const errorMetadata = {
      timestamp: new Date().toISOString(),
      service: 'code-server-backend',
      level: 'ERROR',
      type: 'error',
      trace_id: traceId,
      span_id: spanId,
      
      error: {
        type: err.name || 'UnknownError',
        message: err.message || 'Unknown error',
        code: err.code || undefined,
        status: err.status || 500,
        stack: process.env.NODE_ENV !== 'production' ? err.stack : undefined,
      },
      
      http_request: {
        method: req.method,
        path: req.path,
        url: req.originalUrl,
      },
      
      user: {
        id: req.user?.id || req.sessionID || 'anonymous',
      },
    };

    // Log error
    logger.error(JSON.stringify(errorMetadata));

    // Send error response
    res.status(err.status || 500).json({
      error: true,
      message: process.env.NODE_ENV === 'production' 
        ? 'Internal server error' 
        : err.message,
      trace_id: traceId,
      ...(process.env.NODE_ENV !== 'production' && {
        stack: err.stack,
      }),
    });
  };
}

/**
 * Create trace context injection middleware
 * Adds trace context to all log statements within request lifetime
 */
function createTraceContextLogInjectionMiddleware() {
  return (req, res, next) => {
    const span = trace.getActiveSpan();
    
    if (span) {
      const spanContext = span.spanContext();
      
      // Store in request for middleware/handlers to use
      req.traceContext = {
        traceId: spanContext.traceId,
        spanId: spanContext.spanId,
        traceFlags: spanContext.traceFlags,
      };
      
      // Override console methods to inject trace context
      const originalLog = console.log;
      const originalError = console.error;
      const originalWarn = console.warn;
      
      console.log = function(...args) {
        const message = args.join(' ');
        const enhanced = `[${spanContext.traceId}] ${message}`;
        originalLog.call(console, enhanced);
      };
      
      console.error = function(...args) {
        const message = args.join(' ');
        const enhanced = `[${spanContext.traceId}] ${message}`;
        originalError.call(console, enhanced);
      };
      
      console.warn = function(...args) {
        const message = args.join(' ');
        const enhanced = `[${spanContext.traceId}] ${message}`;
        originalWarn.call(console, enhanced);
      };
      
      // Restore on response finish
      res.on('finish', () => {
        console.log = originalLog;
        console.error = originalError;
        console.warn = originalWarn;
      });
    }
    
    next();
  };
}

/**
 * Utility to log messages with trace context
 */
function logWithTrace(level = 'INFO', message, metadata = {}) {
  const span = trace.getActiveSpan();
  const traceId = span ? span.spanContext().traceId : null;
  const spanId = span ? span.spanContext().spanId : null;
  
  const logEntry = {
    timestamp: new Date().toISOString(),
    service: 'code-server-backend',
    level,
    message,
    trace_id: traceId,
    span_id: spanId,
    ...metadata,
  };
  
  const logLevel = level.toLowerCase();
  if (logLevel === 'error') {
    console.error(JSON.stringify(logEntry));
  } else if (logLevel === 'warn') {
    console.warn(JSON.stringify(logEntry));
  } else {
    console.log(JSON.stringify(logEntry));
  }
}

module.exports = {
  createStructuredLoggingMiddleware,
  createErrorLoggingMiddleware,
  createTraceContextLogInjectionMiddleware,
  logWithTrace,
};
