# Caddy Certificate Configuration (Auto-generated by Terraform)
# Phase 3 Week 2: SSL/TLS ACME Automation
# Domain: ${apex_domain}
# Environment: ${environment}
# Certificate ARN: ${cert_arn}
# Generated: $(date)

# Production Domain Configuration with Let's Encrypt
(${apex_domain}) {
	# Let's Encrypt ACME certificate
	tls {
		issuer acme {
			email ${letsencrypt_email}
			challenges {
				dns cloudflare {
					token (env "CLOUDFLARE_API_TOKEN")
				}
			}
		}
	}
	
	# Security headers (standard for all domains)
	header / {
		# HSTS: Force HTTPS for 1 year
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		
		# Content Security Policy
		Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https:; frame-ancestors 'none';"
		
		# Prevent MIME type sniffing
		X-Content-Type-Options "nosniff"
		
		# Prevent clickjacking
		X-Frame-Options "DENY"
		
		# XSS Protection
		X-XSS-Protection "1; mode=block"
		
		# Referrer Policy
		Referrer-Policy "strict-origin-when-cross-origin"
		
		# Permissions Policy
		Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()"
		
		# Remove Server header
		-Server
	}
	
	# JSON logging
	log {
		level info
		format json
		output file /var/log/caddy/access-${environment}.log {
			roll_size 100mb
			roll_keep 10
		}
	}
}

# Import this configuration in your main Caddyfile:
# import caddy-certificate.conf

# Subject Alternative Names (SANs) included:
# ${subdomains}

# Certificate Renewal:
# Automatic via Let's Encrypt (renewal 30 days before expiry)
# Status: Monitored by Terraform CloudWatch Lambda

# To verify certificate:
# openssl s_client -connect ${apex_domain}:443 -showcerts
