#!/bin/bash
# Phase 7: API Gateways - Kong, Caddy, oauth2-proxy, Cloudflare Tunnel
set -euo pipefail

ENVIRONMENT="${1:-production}"
PRIMARY_IP="${2:-192.168.168.31}"

echo "═══════════════════════════════════════════════════════════════"
echo "[Phase 7] API Gateways & Ingress"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Environment: $ENVIRONMENT"
echo "Primary: $PRIMARY_IP"
echo ""
echo "Gateway Services:"
echo "  ✓ Caddy (port 443) - reverse proxy + automatic TLS (ACME)"
echo "  ✓ oauth2-proxy (port 4180) - OAuth2/OIDC authentication gateway"
echo "  ✓ Kong (port 8000/8443) - API gateway + rate limiting"
echo "  ✓ Cloudflare Tunnel - Ingress from internet (no port 80/443)"
echo ""
echo "Routing Architecture:"
echo "  Internet → Cloudflare Tunnel"
echo "         ↓"
echo "  Caddy (TLS termination, HTTPS only)"
echo "         ↓"
echo "  oauth2-proxy (authentication gate)"
echo "         ↓"
echo "  Kong (API gateway, rate limiting, routing)"
echo "         ↓"
echo "  Services (code-server, APIs, internal services)"
echo ""
echo "Features:"
echo "  ✓ HTTPS everywhere (TLS 1.2+, AEAD ciphers)"
echo "  ✓ OAuth2/OIDC with Google identity provider"
echo "  ✓ Automatic certificate renewal (ACME DNS-01)"
echo "  ✓ Rate limiting (per-user, per-IP)"
echo "  ✓ Request tracing (correlation IDs)"
echo "  ✓ Security headers (HSTS, CSP, X-Frame-Options)"
echo ""
echo "Status: Ready for full implementation"
echo "═══════════════════════════════════════════════════════════════"
