# ════════════════════════════════════════════════════════════════════════════
# NOTE: This file is GENERATED by Terraform from docker-compose.tpl
# DO NOT EDIT MANUALLY — all changes go in main.tf
# Regenerate: terraform apply
# ════════════════════════════════════════════════════════════════════════════

version: "3.9"

services:
  # ─── code-server ────────────────────────────────────────────────────────────
  # VS Code running in the browser with Copilot Chat support
  # Image pinned to specific base + extensions freeze at build time
  code-server:
    build:
      context: .
      dockerfile: Dockerfile.code-server
      args:
        # ALL VERSIONS FROZEN HERE FOR IMMUTABILITY
        CODE_SERVER_VERSION: "${code_server_version}"
        COPILOT_VERSION: "${copilot_version}"
        COPILOT_CHAT_VERSION: "${copilot_chat_version}"
    image: code-server-patched:${code_server_version}
    container_name: code-server
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${code_server_port}"
    environment:
      - PASSWORD=$${CODE_SERVER_PASSWORD:?CODE_SERVER_PASSWORD must be set}
      - SUDO_PASSWORD=$${CODE_SERVER_PASSWORD:?CODE_SERVER_PASSWORD must be set}
      - SERVICE_URL=https://open-vsx.org/vscode/gallery
      - ITEM_URL=https://open-vsx.org/vscode/item
      - CS_DISABLE_FILE_DOWNLOADS=false
      # Navigator shim patched out at build time (see Dockerfile.code-server)
      - NODE_OPTIONS=--enable-source-maps
      - GITHUB_TOKEN=$${GITHUB_TOKEN:-}
      - OLLAMA_ENDPOINT=http://ollama:${ollama_port}
      - OLLAMA_DEFAULT_MODEL=${llama_model}
    command:
      - "--bind-addr=0.0.0.0:${code_server_port}"
      - "--disable-telemetry"
      - "--cert=false"
      - "--auth=password"
    volumes:
      - ${data_volume}:/home/coder/.local/share/code-server
      - ${workspace_volume}:${workspace_path}
      - ./config/settings.json:/etc/code-server/settings.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${code_server_port}/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: ${code_server_memory_limit}
          cpus: '${code_server_cpus_limit}'
        reservations:
          memory: 512m
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  # ─── ollama ─────────────────────────────────────────────────────────────────
  # Local LLM server (pinned to ${ollama_version})
  ollama:
    image: ollama/ollama:${ollama_version}
    container_name: ollama
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${ollama_port}"
    environment:
      - OLLAMA_HOST=0.0.0.0:${ollama_port}
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_NUM_THREAD=$${OLLAMA_NUM_THREAD:-8}
      - OLLAMA_NUM_GPU=$${OLLAMA_NUM_GPU:-0}
    volumes:
      - ${ollama_volume}:/root/.ollama
      - ${workspace_dir}:${workspace_path}:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ollama_port}/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 32g
        reservations:
          memory: 8g
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

  # ─── ollama-init ────────────────────────────────────────────────────────────
  # One-time service that pulls models on startup
  ollama-init:
    image: ollama/ollama:${ollama_version}
    container_name: ollama-init
    networks:
      - ${network_name}
    environment:
      - OLLAMA_HOST=ollama:${ollama_port}
    volumes:
      - ${ollama_volume}:/root/.ollama
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "🚀 Pulling elite LLM models..."
        echo "⏳ Pulling ${llama_model}..."
        ollama pull ${llama_model} || true
        echo "⏳ Pulling codegemma..."
        ollama pull codegemma || true
        echo "⏳ Pulling neural-chat..."
        ollama pull neural-chat || true
        echo "⏳ Pulling mistral..."
        ollama pull mistral || true
        echo "✅ All models ready"
        sleep infinity
    depends_on:
      - ollama
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # ─── oauth2-proxy ───────────────────────────────────────────────────────────
  # Authentication sidecar (pinned to ${oauth2_proxy_version})
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:${oauth2_proxy_version}
    container_name: oauth2-proxy
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${oauth2_proxy_port}"
    environment:
      OAUTH2_PROXY_CLIENT_ID: "$${GOOGLE_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "$${GOOGLE_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "$${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://accounts.google.com"
      OAUTH2_PROXY_REDIRECT_URL: "https://$${DOMAIN}/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://code-server:${code_server_port}/"
      OAUTH2_PROXY_EMAIL_DOMAINS: ""
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: "/etc/oauth2-proxy/allowed-emails.txt"
      OAUTH2_PROXY_COOKIE_NAME: "_oauth2_proxy_ide"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_HTTPONLY: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_EXPIRE: "24h"
      OAUTH2_PROXY_COOKIE_REFRESH: "15m"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:${oauth2_proxy_port}"
      OAUTH2_PROXY_PROXY_PREFIX: "/oauth2"
      OAUTH2_PROXY_PROXY_WEBSOCKETS: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
      OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
      OAUTH2_PROXY_AUTH_LOGGING: "true"
      OAUTH2_PROXY_REQUEST_LOGGING: "true"
      OAUTH2_PROXY_SKIP_AUTH_REGEX: "^/healthz|^/oauth2"
    volumes:
      - ./allowed-emails.txt:/etc/oauth2-proxy/allowed-emails.txt:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${oauth2_proxy_port}/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - code-server
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # ─── caddy ──────────────────────────────────────────────────────────────────
  # Reverse proxy + TLS (pinned to ${caddy_version})
  caddy:
    image: caddy:${caddy_version}
    container_name: caddy
    restart: unless-stopped
    networks:
      - ${network_name}
    ports:
      - "${caddy_http_port}:80"
      - "${caddy_https_port}:443"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-config:/config
      - caddy-data:/data
    environment:
      - ACME_AGREE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      - oauth2-proxy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# ─────────────────────────────────────────────────────────────────────────────
# Networks & Volumes
# ─────────────────────────────────────────────────────────────────────────────
networks:
  ${network_name}:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  # ── NAS-backed (shared across .31 and .42 via NFS) ──────────────────────
  ${data_volume}:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${nas_host},nfsvers=4,rsize=131072,wsize=131072,hard,timeo=600,retrans=2,_netdev"
      device: ":${nas_export_path}/code-server/profile"

  ${workspace_volume}:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${nas_host},nfsvers=4,rsize=131072,wsize=131072,hard,timeo=600,retrans=2,_netdev"
      device: ":${nas_export_path}/code-server/workspace"

  ${ollama_volume}:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${nas_host},nfsvers=4,rsize=131072,wsize=131072,hard,timeo=600,retrans=2,_netdev"
      device: ":${nas_export_path}/ollama"

  # ── Local-only (NFS locking incompatible with these engines) ─────────────
  caddy-config:
    driver: local
  caddy-data:
    driver: local
