# ════════════════════════════════════════════════════════════════════════════
# NOTE: This file is GENERATED by Terraform from docker-compose.tpl
# DO NOT EDIT MANUALLY — all changes go in main.tf
# Regenerate: terraform apply
# ════════════════════════════════════════════════════════════════════════════

services:
  # ─── code-server ────────────────────────────────────────────────────────────
  # VS Code running in the browser with Copilot Chat support
  # Image pinned to specific base + extensions freeze at build time
  code-server:
    build:
      context: .
      dockerfile: Dockerfile.code-server
      args:
        # ALL VERSIONS FROZEN HERE FOR IMMUTABILITY
        CODE_SERVER_VERSION: "${code_server_version}"
        COPILOT_VERSION: "${copilot_version}"
        COPILOT_CHAT_VERSION: "${copilot_chat_version}"
    image: code-server-patched:${code_server_version}
    container_name: code-server
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${code_server_port}"
    environment:
      - PASSWORD=$${CODE_SERVER_PASSWORD:-change-me-in-env}
      - SUDO_PASSWORD=$${CODE_SERVER_PASSWORD:-change-me-in-env}
      - SERVICE_URL=https://open-vsx.org/vscode/gallery
      - ITEM_URL=https://open-vsx.org/vscode/item
      - CS_DISABLE_FILE_DOWNLOADS=false
      # Navigator shim patched out at build time (see Dockerfile.code-server)
      - NODE_OPTIONS=--enable-source-maps
      - GITHUB_TOKEN=$${GITHUB_TOKEN:-}
      - OLLAMA_ENDPOINT=http://ollama:${ollama_port}
      - OLLAMA_DEFAULT_MODEL=${llama_model}
      # ─── OpenTelemetry Instrumentation (Phase 24-A) ───────────────────
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=code-server
      - OTEL_RESOURCE_ATTRIBUTES=environment=production,version=4.115.0,hostname=code-server
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command:
      - "--bind-addr=0.0.0.0:${code_server_port}"
      - "--disable-telemetry"
      - "--cert=false"
      - "--auth=none"
    volumes:
      - ${data_volume}:/home/coder
      - ${workspace_dir}:${workspace_path}
      - ./config/settings.json:/etc/code-server/settings.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${code_server_port}/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: ${code_server_memory_limit}
          cpus: '${code_server_cpus_limit}'
        reservations:
          memory: 512m
          cpus: '0.25'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  # ─── ollama ─────────────────────────────────────────────────────────────────
  # Local LLM server (pinned to ${ollama_version})
  ollama:
    image: ollama/ollama:${ollama_version}
    container_name: ollama
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${ollama_port}"
    environment:
      - OLLAMA_HOST=0.0.0.0:${ollama_port}
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_NUM_THREAD=$${OLLAMA_NUM_THREAD:-8}
      - OLLAMA_NUM_GPU=$${OLLAMA_NUM_GPU:-0}
    volumes:
      - ${ollama_volume}:/root/.ollama
      - ${workspace_dir}:${workspace_path}:ro
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "</dev/tcp/localhost/${ollama_port}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 32g
        reservations:
          memory: 8g
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

  # ─── ollama-init ────────────────────────────────────────────────────────────
  # One-time service that pulls models on startup
  ollama-init:
    image: ollama/ollama:${ollama_version}
    container_name: ollama-init
    networks:
      - ${network_name}
    environment:
      - OLLAMA_HOST=ollama:${ollama_port}
    volumes:
      - ${ollama_volume}:/root/.ollama
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "🚀 Pulling elite LLM models..."
        echo "⏳ Pulling ${llama_model}..."
        ollama pull ${llama_model} || true
        echo "⏳ Pulling codegemma..."
        ollama pull codegemma || true
        echo "⏳ Pulling neural-chat..."
        ollama pull neural-chat || true
        echo "⏳ Pulling mistral..."
        ollama pull mistral || true
        echo "✅ All models ready"
        sleep infinity
    depends_on:
      - ollama
    restart: on-failure

  # ─── oauth2-proxy ───────────────────────────────────────────────────────────
  # Authentication sidecar (pinned to ${oauth2_proxy_version})
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:${oauth2_proxy_version}
    container_name: oauth2-proxy
    restart: unless-stopped
    networks:
      - ${network_name}
    expose:
      - "${oauth2_proxy_port}"
    user: "0:0"
    env_file:
      - .env
    environment:
      OAUTH2_PROXY_CLIENT_ID: "$${GOOGLE_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "$${GOOGLE_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "$${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://accounts.google.com"
      OAUTH2_PROXY_REDIRECT_URL: "https://$${DOMAIN}/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://code-server:${code_server_port}/"
      OAUTH2_PROXY_EMAIL_DOMAINS: ""
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: "/etc/oauth2-proxy/allowed-emails.txt"
      OAUTH2_PROXY_COOKIE_NAME: "_oauth2_proxy_ide"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_HTTPONLY: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_EXPIRE: "24h"
      OAUTH2_PROXY_COOKIE_REFRESH: "15m"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:${oauth2_proxy_port}"
      OAUTH2_PROXY_PROXY_PREFIX: "/oauth2"
      OAUTH2_PROXY_PROXY_WEBSOCKETS: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
      OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
      OAUTH2_PROXY_AUTH_LOGGING: "true"
      OAUTH2_PROXY_REQUEST_LOGGING: "true"
      OAUTH2_PROXY_SKIP_AUTH_REGEX: "^/healthz|^/oauth2"
    volumes:
      - ./allowed-emails.txt:/etc/oauth2-proxy/allowed-emails.txt:ro
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "--spider", "http://localhost:${oauth2_proxy_port}/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - code-server
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # ─── caddy ──────────────────────────────────────────────────────────────────
  # Reverse proxy + TLS (pinned to ${caddy_version})
  caddy:
    image: caddy:${caddy_version}
    container_name: caddy
    restart: unless-stopped
    networks:
      - ${network_name}
    ports:
      - "${caddy_http_port}:80"
      - "${caddy_https_port}:443"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-config:/config
      - caddy-data:/data
    environment:
      # ─── DNS & TLS Configuration (Phase 21+) ──────────────────────────
      # For production: DOMAIN=kushnir.cloud (real DNS + Let's Encrypt)
      # For on-prem: DOMAIN=${external_domain} (nip.io or static IP)
      - DOMAIN=$${DOMAIN}
      - ACME_EMAIL=$${ACME_EMAIL}
      - ACME_AGREE=true
      # ─── OpenTelemetry Instrumentation (Phase 24-A) ───────────────────
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=caddy-proxy
      - OTEL_RESOURCE_ATTRIBUTES=environment=production,version=${caddy_version},hostname=caddy
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      - oauth2-proxy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

%{ if enable_cloudflared }
  # ─── cloudflared ────────────────────────────────────────────────────────────
  # Cloudflare Tunnel sidecar (enabled only when token is provided via Terraform)
  cloudflared:
    image: cloudflare/cloudflared:2024.12.0
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - ${network_name}
    env_file:
      - .env
    command:
      - tunnel
      - run
      - --token=$${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - caddy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
%{ endif }

# ─────────────────────────────────────────────────────────────────────────────
# Networks & Volumes
# ─────────────────────────────────────────────────────────────────────────────
networks:
  ${network_name}:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  ${data_volume}:
    driver: local
  ${ollama_volume}:
    driver: local
  caddy-config:
    driver: local
  caddy-data:
    driver: local
