#!/bin/bash
# Fix missing environment variables in .env

cat >> /home/akushnir/code-server-enterprise/.env << 'EOF'

# ─── OLLAMA (LLM Inference Engine with NVIDIA T1000) ──────────────────────────
OLLAMA_VERSION=0.1.45
OLLAMA_PORT=11434
OLLAMA_HOST_ADDR=0.0.0.0:11434
OLLAMA_DEVICE_NVIDIA1=/dev/nvidia1
OLLAMA_DEVICE_NVIDIACTL=/dev/nvidiactl
OLLAMA_DEVICE_UVM=/dev/nvidia-uvm
OLLAMA_DEVICE_UVM_TOOLS=/dev/nvidia-uvm-tools
OLLAMA_CUDA_VISIBLE_DEVICES=1
OLLAMA_NVIDIA_VISIBLE_DEVICES=1
OLLAMA_NUM_GPU=1
OLLAMA_GPU_LAYERS=99
OLLAMA_KEEP_ALIVE=5m
OLLAMA_MAX_LOADED_MODELS=3
OLLAMA_NUM_THREAD=8
OLLAMA_FLASH_ATTENTION=1
OLLAMA_NUM_PARALLEL=4
OLLAMA_MAX_VRAM=8g
OLLAMA_MEMORY_LIMIT=8g

# ─── ADDITIONAL MISSING VARIABLES ──────────────────────────────────────────────
COREDNS_VERSION=1.11.1
POSTGRES_CPU_RESERVE=0.5
REDIS_CPU_RESERVE=0.5
CODE_SERVER_CPU_RESERVE=1.0
PROMETHEUS_VERSION=v2.49.1
ALERTMANAGER_VERSION=v0.26.0
PGBOUNCER_VERSION=1.21.0
LOCUST_VERSION=2.20.0
LOKI_VERSION=2.9.4
KONG_VERSION=3.4.0
KONG_POSTGRES_PASSWORD=kong-secure-password-change-in-prod
CLOUDFLARE_TUNNEL_VERSION=2024.1.5
CADDY_VERSION=2.9.1-alpine
TZ=UTC
EOF
echo "✓ Added missing environment variables"
