#!/usr/bin/env bash
# GITHUB_ISSUE_SYNC_EXECUTION_COMMANDS.sh
# Copy-paste ready commands for GitHub issue sync setup
# Execute line by line or source this file
set -e
trap 'echo "Script failed at line $LINENO"; exit 1' ERR
trap 'echo "Performing cleanup..."; rm -f /tmp/*.tmp 2>/dev/null || true' EXIT

echo "GitHub Issue Sync Setup - Execution Commands"
echo "=============================================="
echo ""
echo "Option 1: GCP GSM Integration (Recommended)"
echo "=============================================="
echo ""
echo "Step 1: Check GCP authentication"
echo "  $ gcloud auth application-default print-access-token"
echo ""
echo "If the above fails, authenticate:"
echo "  $ gcloud auth application-default login"
echo ""
echo "Step 2: Run setup script"
echo "  $ bash setup-github-gcp-integration.sh"
echo ""
echo "When prompted, enter your Ubuntu user password"
echo ""
echo "Step 3: Reload shell and verify"
echo "  $ source ~/.bashrc"
echo "  $ gh auth status"
echo "  $ gh issue list --repo kushin77/code-server --limit 5"
echo ""
echo "Step 4: Restart VS Code"
echo "  File → Close Window, then reopen"
echo ""
echo "=============================================="
echo "Option 2: Manual Token Setup"
echo "=============================================="
echo ""
echo "Step 1: Create token at GitHub"
echo "  Visit: https://github.com/settings/tokens?type=beta"
echo "  Required scopes:"
echo "    ✓ repo:read, repo:write"
echo "    ✓ issues:read, issues:write"
echo "    ✓ pull_requests:read, pull_requests:write"
echo "    ✓ projects:read"
echo "  Copy token (looks like: github_pat_XXXX)"
echo ""
echo "Step 2: Run setup script"
echo "  $ bash setup-github-issue-sync-ubuntu.sh"
echo ""
echo "When prompted:"
echo "  - Choose: HTTPS"
echo "  - Choose: Paste authentication token"
echo "  - Paste token from Step 1"
echo ""
echo "Step 3: Reload and verify"
echo "  $ source ~/.bashrc"
echo "  $ gh auth status"
echo ""
echo "Step 4: Restart VS Code"
echo ""
echo "=============================================="
echo "Verification Commands"
echo "=============================================="
echo ""
echo "Check GitHub CLI installed:"
echo "  $ gh --version"
echo ""
echo "Check authentication:"
echo "  $ gh auth status"
echo ""
echo "List issues:"
echo "  $ gh issue list --repo kushin77/code-server --limit 5"
echo ""
echo "Create test issue:"
echo "  $ gh issue create --repo kushin77/code-server --title 'Test' --body 'Testing'"
echo ""
echo "Check environment:"
echo "  $ echo \$GITHUB_REPO"
echo "  $ echo \$GITHUB_OWNER"
echo "  $ echo \$GCP_PROJECT"
echo ""
echo "=============================================="
echo "Quick Troubleshooting"
echo "=============================================="
echo ""
echo "If 'gh: command not found':"
echo "  $ sudo apt-get install -y gh"
echo ""
echo "If GitHub not authenticated:"
echo "  $ gh auth login"
echo ""
echo "If VS Code Copilot still can't access GitHub:"
echo "  1. Close VS Code completely"
echo "  2. Open terminal and run: source ~/.bashrc"
echo "  3. Reopen VS Code"
echo ""
echo "If GCP token retrieval fails:"
echo "  $ gcloud auth application-default login"
echo "  Then run setup script again"
echo ""
echo "=============================================="
