-- PostgreSQL Configuration for Query Tracing with OpenTelemetry
-- 
-- Enables slow query logging with trace context extraction
-- Generated by: Phase 3 observability spine - TASK 7 (PostgreSQL Query Tracing)
--
-- Installation:
-- 1. Update postgresql.conf with settings from this file
-- 2. Reload PostgreSQL: SELECT pg_reload_conf();
-- 3. Queries will start logging with trace context

-- ═════════════════════════════════════════════════════════════════════════════
-- LOGGING CONFIGURATION
-- ═════════════════════════════════════════════════════════════════════════════

-- Enable query logging
log_statement = 'all'  -- Log all statements (can change to 'mod' for modifications only)

-- Log queries slower than this (milliseconds)
-- Development: 100ms, Staging: 500ms, Production: 1000ms
log_min_duration_statement = 1000

-- Log connections
log_connections = on
log_disconnections = on

-- Log statement parameters for debugging
log_parameter_max_length = 1024

-- Include detailed query statistics
log_checkpoints = on
log_lock_waits = on
log_temp_files = 1024  -- Log temp files > 1MB

-- ═════════════════════════════════════════════════════════════════════════════
-- LOG FORMAT CONFIGURATION
-- ═════════════════════════════════════════════════════════════════════════════

-- Use JSON format for structured logging
log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '

-- Alternative with trace context extraction:
-- log_line_prefix = '[%t] %u@%d pid=%p trace_id=%c '
-- This requires custom logging_collector configuration

-- ═════════════════════════════════════════════════════════════════════════════
-- PERFORMANCE ANALYSIS SETTINGS
-- ═════════════════════════════════════════════════════════════════════════════

-- Analyze query execution time
log_duration = off  # off - only log slow queries
                  # on - log duration of all queries

-- Enable query statistics (auto_explain)
-- Required: CREATE EXTENSION auto_explain;
shared_preload_libraries = 'auto_explain'

-- auto_explain settings
auto_explain.log_min_duration = 1000  # Log plans > 1 second
auto_explain.log_analyze = true        # Include actual execution stats
auto_explain.log_timing = true        # Include execution timing
auto_explain.log_buffers = true       # Include buffer usage
auto_explain.log_wal = true           # Include WAL usage
auto_explain.log_level = log          # Log level (notice, info, log)

-- ═════════════════════════════════════════════════════════════════════════════
-- TRACE CONTEXT EXTRACTION (Custom)
-- ═════════════════════════════════════════════════════════════════════════════
-- 
-- Query comments with trace context are automatically logged:
-- 
-- Example query:
-- /*+ trace_id='3fa85f64...' span_id='9a8c5c7d...' */
-- SELECT * FROM users;
--
-- PostgreSQL logs the entire query including the comment, so trace context
-- is automatically captured in the log file.
--
-- Log parser can extract trace_id and span_id from the comment using regex:
-- Regex: /trace_id='([^']+)'\s+span_id='([^']+)'/
--

-- ═════════════════════════════════════════════════════════════════════════════
-- MONITORING AND ALERTING VIEWS
-- ═════════════════════════════════════════════════════════════════════════════

-- Create views for monitoring slow queries with trace context

-- View 1: Recent slow queries
CREATE OR REPLACE VIEW pg_slow_queries_with_trace AS
SELECT
  query_start,
  query_duration_ms,
  query_text,
  -- Extract trace_id from query comment
  (regexp_matches(query_text, "trace_id='([^']+)'", 'g'))[1] AS trace_id,
  (regexp_matches(query_text, "span_id='([^']+)'", 'g'))[1] AS span_id,
  -- Query operation type
  CASE
    WHEN query_text ~* '^SELECT' THEN 'select'
    WHEN query_text ~* '^INSERT' THEN 'insert'
    WHEN query_text ~* '^UPDATE' THEN 'update'
    WHEN query_text ~* '^DELETE' THEN 'delete'
    ELSE 'other'
  END AS operation,
  -- Query table (best effort extraction)
  (regexp_matches(query_text, 'FROM\s+(\w+)', 'g'))[1] AS table_name
FROM pg_stat_statements
WHERE mean_exec_time > 1000  -- > 1 second
ORDER BY query_start DESC
LIMIT 100;

-- View 2: Trace correlation statistics
CREATE OR REPLACE VIEW pg_trace_correlation_stats AS
SELECT
  trace_id,
  COUNT(*) AS query_count,
  MIN(query_duration_ms) AS min_duration_ms,
  AVG(query_duration_ms) AS avg_duration_ms,
  MAX(query_duration_ms) AS max_duration_ms,
  MAX(query_start) AS last_query_time,
  string_agg(DISTINCT operation, ', ') AS operations,
  string_agg(DISTINCT table_name, ', ') AS tables
FROM pg_slow_queries_with_trace
WHERE trace_id IS NOT NULL
GROUP BY trace_id
ORDER BY max_duration_ms DESC;

-- ═════════════════════════════════════════════════════════════════════════════
-- QUERY STATISTICS EXTENSION
-- ═════════════════════════════════════════════════════════════════════════════

-- Enable pg_stat_statements for detailed statistics
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Reset statistics periodically (e.g., daily)
-- SELECT pg_stat_statements_reset();

-- View top slow queries
CREATE OR REPLACE VIEW pg_top_slow_queries AS
SELECT
  query,
  calls,
  total_time,
  mean_time,
  max_time,
  rows,
  stddev_time
FROM pg_stat_statements
WHERE mean_time > 100  -- > 100ms average
ORDER BY mean_time DESC
LIMIT 20;

-- ═════════════════════════════════════════════════════════════════════════════
-- INDEX USAGE STATISTICS
-- ═════════════════════════════════════════════════════════════════════════════

-- Identify missing indexes
CREATE OR REPLACE VIEW pg_missing_indexes AS
SELECT
  schemaname,
  tablename,
  attname AS column_name,
  idx_scan,
  idx_tup_read,
  idx_tup_fetch
FROM pg_stat_user_indexes
WHERE idx_scan = 0  -- Not scanned at all
ORDER BY idx_tup_read + idx_tup_fetch DESC;

-- ═════════════════════════════════════════════════════════════════════════════
-- LOCK CONTENTION MONITORING
-- ═════════════════════════════════════════════════════════════════════════════

-- Find blocking locks
CREATE OR REPLACE VIEW pg_blocking_locks AS
SELECT
  blocked_locks.pid AS blocked_pid,
  blocked_activity.query AS blocked_statement,
  blocking_locks.pid AS blocking_pid,
  blocking_activity.query AS blocking_statement,
  blocked_activity.application_name AS blocked_application,
  blocking_activity.application_name AS blocking_application
FROM pg_catalog.pg_locks blocked_locks
  JOIN pg_catalog.pg_stat_activity blocked_activity ON blocked_activity.pid = blocked_locks.pid
  JOIN pg_catalog.pg_locks blocking_locks
    ON blocking_locks.locktype = blocked_locks.locktype
    AND blocking_locks.database IS NOT DISTINCT FROM blocked_locks.database
    AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
    AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
    AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
    AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
    AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
    AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
    AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
    AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
    AND blocking_locks.pid != blocked_locks.pid
  JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
WHERE NOT blocked_locks.granted;

-- ═════════════════════════════════════════════════════════════════════════════
-- CACHE HIT RATIO MONITORING
-- ═════════════════════════════════════════════════════════════════════════════

-- Calculate buffer cache hit ratio
CREATE OR REPLACE VIEW pg_cache_hit_ratio AS
SELECT
  sum(heap_blks_read) as heap_read,
  sum(heap_blks_hit) as heap_hit,
  sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as heap_ratio,
  sum(idx_blks_read) as idx_read,
  sum(idx_blks_hit) as idx_hit,
  sum(idx_blks_hit) / (sum(idx_blks_hit) + sum(idx_blks_read)) as idx_ratio
FROM pg_statio_user_tables;

-- ═════════════════════════════════════════════════════════════════════════════
-- CONNECTION MONITORING
-- ═════════════════════════════════════════════════════════════════════════════

-- Monitor active connections
CREATE OR REPLACE VIEW pg_active_connections AS
SELECT
  pid,
  usename,
  application_name,
  client_addr,
  state,
  query,
  query_start,
  state_change,
  EXTRACT(EPOCH FROM (NOW() - query_start)) AS query_duration_sec
FROM pg_stat_activity
WHERE state IS NOT NULL
ORDER BY query_start;

-- ═════════════════════════════════════════════════════════════════════════════
-- VACUUM AND MAINTENANCE STATISTICS
-- ═════════════════════════════════════════════════════════════════════════════

-- Monitor table bloat
CREATE OR REPLACE VIEW pg_table_bloat AS
SELECT
  schemaname,
  tablename,
  n_live_tup,
  n_dead_tup,
  ROUND(100 * n_dead_tup / NULLIF(n_live_tup + n_dead_tup, 0), 2) AS dead_ratio,
  last_vacuum,
  last_autovacuum
FROM pg_stat_user_tables
WHERE n_dead_tup > 1000
ORDER BY n_dead_tup DESC;

-- ═════════════════════════════════════════════════════════════════════════════
-- ALERTING THRESHOLDS (for Prometheus/AlertManager)
-- ═════════════════════════════════════════════════════════════════════════════

-- Alert if:
-- 1. Cache hit ratio < 95% (slow reads from disk)
-- 2. Slow query time > 1 second (degraded performance)
-- 3. Blocking locks detected (contention)
-- 4. Dead tuples > 10% of table (bloat)
-- 5. Connections > 80 (near limit)

-- ═════════════════════════════════════════════════════════════════════════════
-- DEPLOYMENT CHECKLIST
-- ═════════════════════════════════════════════════════════════════════════════

-- 1. [ ] Update postgresql.conf with logging settings
-- 2. [ ] Reload PostgreSQL: SELECT pg_reload_conf();
-- 3. [ ] Create extensions: CREATE EXTENSION pg_stat_statements;
-- 4. [ ] Create views (above)
-- 5. [ ] Configure log shipping to centralized logging
-- 6. [ ] Set up alerts in Prometheus/AlertManager
-- 7. [ ] Configure Grafana dashboard
-- 8. [ ] Test with: SELECT query with trace context comment
-- 9. [ ] Verify logs contain trace_id and span_id
-- 10. [ ] Set up log parser to extract trace context

-- ═════════════════════════════════════════════════════════════════════════════
-- SAMPLE QUERIES FOR TESTING
-- ═════════════════════════════════════════════════════════════════════════════

-- Test query with trace context:
-- /*+ trace_id='3fa85f64-5717-4562-b3fc-2c963f66afa6' span_id='9a8c5c7d-1e6f-4b2a-8c3d-5f7a2b6e9c1d' */
-- SELECT * FROM pg_stat_statements LIMIT 10;

-- This will log the entire query including the trace context comment,
-- which can be extracted by log parsers.
