-- Redis Instrumentation Script for OpenTelemetry
-- Generates trace context for all Redis operations
-- Lua script executed server-side for minimal latency impact
--
-- Generated by: Phase 3 observability spine - TASK 8 (Redis Instrumentation)
-- Date: April 16, 2026
-- Version: 1.0.0

-- Generate unique IDs for distributed tracing
local function generate_trace_id()
    -- Generate 128-bit trace ID (hex format)
    local t = {}
    for i = 1, 16 do
        table.insert(t, string.format('%02x', math.random(0, 255)))
    end
    return table.concat(t)
end

local function generate_span_id()
    -- Generate 64-bit span ID (hex format)
    local t = {}
    for i = 1, 8 do
        table.insert(t, string.format('%02x', math.random(0, 255)))
    end
    return table.concat(t)
end

-- Register span data for instrumentation hooks
local function register_span(operation, key, duration_ms, hit_or_miss)
    -- Store span metadata in Redis itself (monitoring use)
    local span_id = generate_span_id()
    local span_data = {
        timestamp = redis.call('TIME'),
        operation = operation,
        key = key,
        duration_ms = duration_ms,
        hit_or_miss = hit_or_miss,
        span_id = span_id
    }
    
    -- Store with 1-hour TTL for monitoring dashboards
    redis.call('SETEX', 
        '__spans:' .. span_id, 
        3600, 
        cjson.encode(span_data)
    )
    
    return span_id
end

-- Instrumentation wrapper functions
-- These are called by the redis-py wrapper at connection level

-- KEYS[1] = cache key
-- ARGV[1] = trace_id
-- ARGV[2] = span_id
function get_with_trace(keys, args)
    local cache_key = keys[1]
    local trace_id = args[1]
    local span_id = args[2]
    
    local start_time = redis.call('TIME')
    local result = redis.call('GET', cache_key)
    local end_time = redis.call('TIME')
    
    -- Calculate duration in milliseconds
    local duration_ms = (tonumber(end_time[1]) - tonumber(start_time[1])) * 1000 +
                       (tonumber(end_time[2]) - tonumber(start_time[2])) / 1000
    
    local hit_or_miss = result ~= false and 'hit' or 'miss'
    
    -- Register span for observability
    register_span('GET', cache_key, duration_ms, hit_or_miss)
    
    return {
        value = result,
        trace_id = trace_id,
        span_id = span_id,
        operation = 'GET',
        hit_or_miss = hit_or_miss,
        duration_ms = duration_ms
    }
end

-- KEYS[1] = cache key
-- ARGV[1] = trace_id
-- ARGV[2] = span_id
-- ARGV[3] = value
-- ARGV[4] = ttl_seconds (optional)
function set_with_trace(keys, args)
    local cache_key = keys[1]
    local trace_id = args[1]
    local span_id = args[2]
    local value = args[3]
    local ttl_seconds = args[4] or 3600  -- Default 1 hour
    
    local start_time = redis.call('TIME')
    
    if ttl_seconds and tonumber(ttl_seconds) > 0 then
        redis.call('SETEX', cache_key, ttl_seconds, value)
    else
        redis.call('SET', cache_key, value)
    end
    
    local end_time = redis.call('TIME')
    
    -- Calculate duration in milliseconds
    local duration_ms = (tonumber(end_time[1]) - tonumber(start_time[1])) * 1000 +
                       (tonumber(end_time[2]) - tonumber(start_time[2])) / 1000
    
    -- Register span
    register_span('SET', cache_key, duration_ms, 'write')
    
    return {
        success = true,
        trace_id = trace_id,
        span_id = span_id,
        operation = 'SET',
        duration_ms = duration_ms
    }
end

-- KEYS[1] = cache key
-- ARGV[1] = trace_id
-- ARGV[2] = span_id
function del_with_trace(keys, args)
    local cache_key = keys[1]
    local trace_id = args[1]
    local span_id = args[2]
    
    local start_time = redis.call('TIME')
    local deleted = redis.call('DEL', cache_key)
    local end_time = redis.call('TIME')
    
    -- Calculate duration in milliseconds
    local duration_ms = (tonumber(end_time[1]) - tonumber(start_time[1])) * 1000 +
                       (tonumber(end_time[2]) - tonumber(start_time[2])) / 1000
    
    -- Register span
    register_span('DEL', cache_key, duration_ms, deleted > 0 and 'deleted' or 'notfound')
    
    return {
        deleted = deleted,
        trace_id = trace_id,
        span_id = span_id,
        operation = 'DEL',
        duration_ms = duration_ms
    }
end

-- KEYS[1] = pattern
-- ARGV[1] = trace_id
-- ARGV[2] = span_id
function scan_with_trace(keys, args)
    local pattern = keys[1]
    local trace_id = args[1]
    local span_id = args[2]
    
    local start_time = redis.call('TIME')
    local cursor = '0'
    local keys_found = {}
    
    repeat
        local result = redis.call('SCAN', cursor, 'MATCH', pattern, 'COUNT', 1000)
        cursor = result[1]
        for i, key in ipairs(result[2]) do
            table.insert(keys_found, key)
        end
    until cursor == '0'
    
    local end_time = redis.call('TIME')
    
    -- Calculate duration in milliseconds
    local duration_ms = (tonumber(end_time[1]) - tonumber(start_time[1])) * 1000 +
                       (tonumber(end_time[2]) - tonumber(start_time[2])) / 1000
    
    -- Register span
    register_span('SCAN', pattern, duration_ms, 'scan')
    
    return {
        keys = keys_found,
        count = #keys_found,
        trace_id = trace_id,
        span_id = span_id,
        operation = 'SCAN',
        duration_ms = duration_ms
    }
end

-- Get cache statistics for monitoring
function get_cache_stats()
    local info = redis.call('INFO', 'stats')
    local memory = redis.call('INFO', 'memory')
    
    return {
        info = info,
        memory = memory
    }
end

-- Export functions for use by wrapper
return {
    get_with_trace = get_with_trace,
    set_with_trace = set_with_trace,
    del_with_trace = del_with_trace,
    scan_with_trace = scan_with_trace,
    get_cache_stats = get_cache_stats,
    generate_trace_id = generate_trace_id,
    generate_span_id = generate_span_id,
    register_span = register_span
}
