# CoreDNS Configuration — Internal DNS for prod.internal domain
#
# This file resolves all *.prod.internal DNS names to their corresponding
# hosts within the private network. External queries fallback to public DNS.
#
# Generated from: environments/production/hosts.yml
# Do NOT edit this file directly; update hosts.yml and regenerate.

# ============================================================================
# PRODUCTION INTERNAL DOMAIN — prod.internal
# ============================================================================
prod.internal {
    # Forward all prod.internal queries to this local file (generated below)
    file /etc/coredns/zones/db.prod.internal {
        reload 10s
    }

    # Log all DNS queries for debugging
    log {
        class error
    }

    # Health check endpoint (used by Keepalived or external monitors)
    health :8053

    # Enable query caching (TTL-aware)
    cache 300 {
        denial 30 0
    }
}

# ============================================================================
# EXTERNAL QUERIES — Fallback to public DNS
# ============================================================================
. {
    # Forward all external queries (non-prod.internal) to public resolvers
    forward . 8.8.8.8 8.8.4.4 {
        # Use TCP for DNS-over-TCP (more reliable in firewalled networks)
        policy sequential
        health 5s
        max_fails 3
    }

    # Cache external results
    cache 60 {
        # Cache negative results (NXDOMAIN) for shorter duration
        denial 10 0
    }

    # Log external queries
    log {
        class error
    }

    # Enable prometheus metrics (optional, for monitoring DNS performance)
    prometheus 0.0.0.0:9153

    # Enable query rate limiting to prevent DNS amplification attacks
    rate_limit {
        # Allow 100 requests per second per IP
        actions drop
    }
}

# ============================================================================
# LOGGING & MONITORING
# ============================================================================
# Logging is configured per-zone above.
# Metrics available at: http://<coredns-ip>:9153/metrics

# Health check endpoint:
#   curl -s http://127.0.0.1:8053/health
#   Returns: "OK" (HTTP 200) if CoreDNS is serving
