terraform {
  required_version = ">= 1.7"
  
  # ═══════════════════════════════════════════════════════════════════════
  # REMOTE STATE BACKEND — MinIO S3-compatible (Issue #417)
  # ═══════════════════════════════════════════════════════════════════════
  # Initialize with: terraform init -backend-config=backend-config.hcl
  # Verify with: terraform state list (should show resources from remote)
  # Migration: terraform init -migrate-state (moves local to remote)
  #
  # Security:
  # - Credentials via AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY env vars
  # - State encrypted at rest in MinIO (TLS in transit via Caddy)
  # - Local terraform.tfstate should be deleted after successful migration
  # - gitignore: *.tfstate* (never commit local state)
  #
  # On-Premises Benefits:
  # - No cloud vendor lock-in (MinIO is S3-compatible)
  # - State stored on 192.168.168.31 (on-prem infrastructure)
  # - Team collaboration with state locking
  # - Disaster recovery (state is backed up with database)
  # ═══════════════════════════════════════════════════════════════════════
  
  backend "s3" {
    bucket         = "code-server-tfstate"
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
    endpoint       = "http://minio:9000"
    
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_region_validation      = true
  }
  
  required_providers {
    # Local file operations
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    
    # Null provider (for resource-less actions)
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    
    # Docker container orchestration
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    
    # Random resource generation (secrets, tokens)
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    
    # AWS cloud provider (optional, for hybrid deployments)
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    
    # Cloudflare DNS and tunneling
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.27"
    }
    
    # GoDaddy DNS provider (on-premises domain management)
    godaddy = {
      source  = "n3integration/godaddy"
      version = "~> 1.9"
    }
    
    # HashiCorp Vault (secrets management)
    vault = {
      source  = "hashicorp/vault"
      version = "~> 4.2"
    }
  }
}

provider "docker" {
  host = var.docker_host
}

# ════════════════════════════════════════════════════════════════════════════
# SINGLE SOURCE OF TRUTH FOR ALL INFRASTRUCTURE
# 
# This Terraform configuration is the authoritative IaC definition for the
# code-server enterprise deployment. All versions, configuration, and state
# flow through Terraform for reproducibility and idempotency.
#
# DEPLOYMENT WORKFLOW (Idempotent):
#   1. terraform init      # Initialize state backend (local by default)
#   2. terraform plan      # Review changes (should show exactly what will change)
#   3. terraform apply     # Generate docker-compose.yml + secrets config
#   4. docker compose rebuild --no-cache  # Build images with pinned versions
#   5. docker compose up -d               # Deploy containers
#   6. docker compose healthcheck         # Verify all services healthy
#
# IDEMPOTENCY GUARANTEES:
#   - Terraform state ensures generated files are tracked
#   - docker-compose.yml is GENERATED, not manually edited (pins all versions)
#   - Re-running terraform apply + docker compose rebuild produces identical result
#   - All versions hardcoded in Terraform, not pulled at deploy time
#
# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 1: Ensure output directory exists
# ════════════════════════════════════════════════════════════════════════════
resource "null_resource" "workspace_setup" {
  provisioner "local-exec" {
    command = "mkdir -p ${path.module}/workspace ${path.module}/config/caddy"
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 2: Generate docker-compose.yml (SINGLE SOURCE OF TRUTH)
# 
# NOTE: docker-compose.yml is managed directly in repo (IaC consolidation)
# Not generated by Terraform - static configuration used across all environments
# Template generation removed (P1 elite standard: single source of truth)
resource "local_file" "docker_compose_reference" {
  # Reference only - actual docker-compose.yml committed to repo
  filename = "${path.module}/../docker-compose.yml"
  content  = file("${path.module}/../docker-compose.yml")

  # Ensure workspace exists first
  depends_on = [null_resource.workspace_setup]

  lifecycle {
    # Track this as reference only
    ignore_changes = [content]
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 3: Generate Caddyfile for local development
# ════════════════════════════════════════════════════════════════════════════
resource "local_file" "caddyfile" {
  filename = "${path.module}/config/caddy/Caddyfile"

  content = templatefile("${path.module}/../Caddyfile.tpl", {
    code_server_host  = "localhost"
    code_server_port  = local.code_server_port
    oauth2_proxy_port = local.oauth2_port
  })

  depends_on = [null_resource.workspace_setup]
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 4: Generate .env for docker-compose secrets (DO NOT COMMIT)
# ════════════════════════════════════════════════════════════════════════════
resource "local_file" "env_file" {
  filename = "${path.module}/.env"

  content = <<-EOT
# ⚠️  Generated by Terraform — DO NOT COMMIT TO GIT
# This file contains secrets pulled from Google Secret Manager
# Regenerate: terraform apply
# 
# To populate from GSM: scripts/fetch-gsm-secrets.sh

# Code Server
CODE_SERVER_PASSWORD=$${var.code_server_password}

# Google OAuth (from GSM)
GOOGLE_CLIENT_ID=$${var.google_client_id}
GOOGLE_CLIENT_SECRET=$${var.google_client_secret}
OAUTH2_PROXY_COOKIE_SECRET=$${var.oauth2_proxy_cookie_secret}

# Domain routing
DOMAIN=$${var.domain}

# GitHub token (optional, for higher rate limits)
GITHUB_TOKEN=$${var.github_token}

# Workspace volume mount
WORKSPACE_PATH=$${local.storage.workspace_dir}

# Ollama configuration
OLLAMA_NUM_THREAD=$${var.ollama_num_threads}
OLLAMA_NUM_GPU=$${var.ollama_num_gpu}

EOT

  depends_on = [null_resource.workspace_setup]

  lifecycle {
    # Never replace secrets file; use terraform apply to regenerate from vars
    prevent_destroy = false
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 5: Reference deployment script (not generated by terraform)
# ════════════════════════════════════════════════════════════════════════════

# Deployment script is maintained in scripts/deploy.sh (not Terraform-generated)
# Terraform integration point: validate scripts exist
resource "null_resource" "validate_scripts_exist" {
  provisioner "local-exec" {
    command = <<-SHELL
      for script in scripts/deploy.sh scripts/nas-mount-31.sh scripts/wireguard-install.sh; do
        if [[ ! -f "$script" ]]; then
          echo "ERROR: Required script not found: $script"
          exit 1
        fi
      done
    SHELL
  }
}

# ════════════════════════════════════════════════════════════════════════════
# OUTPUT: Deployment Summary
# ════════════════════════════════════════════════════════════════════════════

output "deployment_ready" {
  description = "True if all validation passed"
  value       = true
}

# Make deploy scripts executable
resource "null_resource" "make_deploy_executable" {
  provisioner "local-exec" {
    # Make scripts executable on Linux/Mac
    command = "chmod +x scripts/deploy.sh scripts/nas-mount-31.sh scripts/wireguard-install.sh 2>/dev/null || true"
  }
  depends_on = [null_resource.validate_scripts_exist]
}

# ════════════════════════════════════════════════════════════════════════════
# OUTPUTS: Display deployment status
# ════════════════════════════════════════════════════════════════════════════
output "deployment_summary" {
  description = "Summary of IaC deployment configuration"
  value = {
    service_name    = local.service_name
    environment     = local.environment
    pinned_versions = local.docker_images
    network_name    = local.network_name
    storage_volumes = { data = local.data_volume, workspace = local.workspace_path }
  }
}
