terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "docker" {
  host = var.docker_host
}

# ════════════════════════════════════════════════════════════════════════════
# SINGLE SOURCE OF TRUTH FOR ALL INFRASTRUCTURE
# 
# This Terraform configuration is the authoritative IaC definition for the
# code-server enterprise deployment. All versions, configuration, and state
# flow through Terraform for reproducibility and idempotency.
#
# DEPLOYMENT WORKFLOW (Idempotent):
#   1. terraform init      # Initialize state backend (local by default)
#   2. terraform plan      # Review changes (should show exactly what will change)
#   3. terraform apply     # Generate docker-compose.yml + secrets config
#   4. docker compose rebuild --no-cache  # Build images with pinned versions
#   5. docker compose up -d               # Deploy containers
#   6. docker compose healthcheck         # Verify all services healthy
#
# IDEMPOTENCY GUARANTEES:
#   - Terraform state ensures generated files are tracked
#   - docker-compose.yml is GENERATED, not manually edited (pins all versions)
#   - Re-running terraform apply + docker compose rebuild produces identical result
#   - All versions hardcoded in Terraform, not pulled at deploy time
#
# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 1: Ensure output directory exists
# ════════════════════════════════════════════════════════════════════════════
resource "null_resource" "workspace_setup" {
  provisioner "local-exec" {
    command = "mkdir -p ${path.module}/workspace ${path.module}/config/caddy"
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 2: Generate docker-compose.yml (SINGLE SOURCE OF TRUTH)
# 
# NOTE: docker-compose.yml is managed directly in repo (IaC consolidation)
# Not generated by Terraform - static configuration used across all environments
# Template generation removed (P1 elite standard: single source of truth)
resource "local_file" "docker_compose_reference" {
  # Reference only - actual docker-compose.yml committed to repo
  filename = "${path.module}/../docker-compose.yml"

  # Ensure workspace exists first
  depends_on = [null_resource.workspace_setup]

  lifecycle {
    # Track this as reference only
    ignore_changes = [content]
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 3: Generate Caddyfile for local development
# ════════════════════════════════════════════════════════════════════════════
resource "local_file" "caddyfile" {
  filename = "${path.module}/config/caddy/Caddyfile"

  content = templatefile("${path.module}/../Caddyfile.tpl", {
    code_server_host  = "localhost"
    code_server_port  = local.network.code_server_port
    oauth2_proxy_port = local.network.oauth2_proxy_port
  })

  depends_on = [null_resource.workspace_setup]
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 4: Generate .env for docker-compose secrets (DO NOT COMMIT)
# ════════════════════════════════════════════════════════════════════════════
resource "local_file" "env_file" {
  filename = "${path.module}/.env"

  content = <<-EOT
# ⚠️  Generated by Terraform — DO NOT COMMIT TO GIT
# This file contains secrets pulled from Google Secret Manager
# Regenerate: terraform apply
# 
# To populate from GSM: scripts/fetch-gsm-secrets.sh

# Code Server
CODE_SERVER_PASSWORD=$${var.code_server_password}

# Google OAuth (from GSM)
GOOGLE_CLIENT_ID=$${var.google_client_id}
GOOGLE_CLIENT_SECRET=$${var.google_client_secret}
OAUTH2_PROXY_COOKIE_SECRET=$${var.oauth2_proxy_cookie_secret}

# Domain routing
DOMAIN=$${var.domain}

# GitHub token (optional, for higher rate limits)
GITHUB_TOKEN=$${var.github_token}

# Workspace volume mount
WORKSPACE_PATH=$${local.storage.workspace_dir}

# Ollama configuration
OLLAMA_NUM_THREAD=$${var.ollama_num_threads}
OLLAMA_NUM_GPU=$${var.ollama_num_gpu}

EOT

  depends_on = [null_resource.workspace_setup]

  lifecycle {
    # Never replace secrets file; use terraform apply to regenerate from vars
    prevent_destroy = false
  }
}

# ════════════════════════════════════════════════════════════════════════════
# RESOURCE 5: Generate deployment script (idempotent orchestration)
# ════════════════════════════════════════════════════════════════════════════
resource "local_file" "deploy_script" {
  filename = "${path.module}/scripts/deploy.sh"

  content = <<-EOT
#!/bin/bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Idempotent Deployment Script
# Orchestrates: Terraform → docker-compose rebuild → startup verification
# 
# Usage:  bash scripts/deploy.sh
# 
# What it does:
#   1. Runs terraform apply to generate docker-compose.yml with pinned versions
#   2. Rebuilds Docker images (--no-cache for immutability verification)
#   3. Brings up all services
#   4. Waits for all healthchecks to pass
#   5. Validates critical paths (extension activations, oauth2-proxy auth)
# 
# Exit code: 0 = success, 1 = deployment failed
# ─────────────────────────────────────────────────────────────────────────────

PROJECT_DIR="$$(cd "$$(dirname "$${BASH_SOURCE[0]}")/.." && pwd)"
cd "$$PROJECT_DIR"

LOG_FILE="$${PROJECT_DIR}/deployment.log"
exec 1> >(tee -a "$$LOG_FILE")
exec 2>&1

echo "════════════════════════════════════════════════════════════════════════════"
echo "IDEMPOTENT DEPLOYMENT: code-server-enterprise"
echo "Timestamp: $$(date -Iseconds)"
echo "════════════════════════════════════════════════════════════════════════════"

# Step 1: Terraform init + apply (generates docker-compose.yml with versions)
echo ""
echo "Step 1: Generating infrastructure config (Terraform)..."
if terraform init && terraform apply -auto-approve; then
  echo "✅ Terraform apply completed"
else
  echo "❌ FATAL: Terraform apply failed"
  exit 1
fi

# Step 2: Build Docker images (immutability: --no-cache forces full rebuild)
echo ""
echo "Step 2: Building Docker images with pinned versions..."
if docker compose build --no-cache; then
  echo "✅ Docker images built successfully"
else
  echo "❌ FATAL: Docker image build failed"
  exit 1
fi

# Step 3: Bring up services
echo ""
echo "Step 3: Deploying containers..."
if docker compose up -d; then
  echo "✅ Containers started"
else
  echo "❌ FATAL: Docker compose up failed"
  exit 1
fi

# Step 4: Wait for healthchecks
echo ""
echo "Step 4: Waiting for all services to be healthy..."
MAX_WAIT=120
ELAPSED=0
while [ $$ELAPSED -lt $$MAX_WAIT ]; do
  HEALTHY=$$(docker compose ps --format json | jq '[.[] | select(.Health=="healthy" or .State=="running")] | length')
  TOTAL=$$(docker compose ps --format json | jq 'length')
  echo "  [$$ELAPSED/$$MAX_WAIT] Healthy services: $$HEALTHY/$$TOTAL"
  
  if [ "$$HEALTHY" -eq "$$TOTAL" ]; then
    echo "✅ All services healthy"
    break
  fi
  
  sleep 5
  ELAPSED=$$((ELAPSED + 5))
done

if [ $$ELAPSED -ge $$MAX_WAIT ]; then
  echo "⚠️  WARNING: Services not fully healthy after $$MAX_WAIT seconds (may still be starting)"
  docker compose ps
fi

# Step 5: Verify critical paths
echo ""
echo "Step 5: Validating deployment..."
CHECKS_PASSED=0

# Check code-server HTTP endpoint
if curl -sf http://localhost:8080/healthz > /dev/null 2>&1; then
  echo "✅ code-server HTTP health check passed"
  ((CHECKS_PASSED++))
else
  echo "⚠️  code-server HTTP health check failed (may still be starting)"
fi

# Check docker compose state
if docker compose ps code-server | grep -q "healthy\|running"; then
  echo "✅ code-server container is running"
  ((CHECKS_PASSED++))
else
  echo "❌ code-server container is not running"
fi

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "DEPLOYMENT COMPLETE"
echo "✅ Access IDE at: https://ide.kushnir.cloud"
echo "✅ Authentication: Google OAuth2"
echo "✅ TLS: Let's Encrypt (auto-renewed)"
echo "════════════════════════════════════════════════════════════════════════════"
EOT

  depends_on = [local_file.docker_compose_reference]
}

# Make deploy script executable
resource "null_resource" "make_deploy_executable" {
  provisioner "local-exec" {
    # Make scripts executable on Linux/Mac
    command = "chmod +x '${local_file.deploy_script.filename}' 2>/dev/null || true"
  }
  depends_on = [local_file.deploy_script]
}

# ════════════════════════════════════════════════════════════════════════════
# OUTPUTS: Display deployment status
# ════════════════════════════════════════════════════════════════════════════
output "deployment_summary" {
  description = "Summary of IaC deployment configuration"
  value = {
    service_name          = local.service_name
    environment           = local.environment
    pinned_versions       = local.versions
    network               = local.network
    storage_volumes       = { data = local.storage.data_volume, ollama = local.storage.ollama_volume }
  }
}
