terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

# ════════════════════════════════════════════════════════════════════════════
# PHASE 26-C: Multi-Tenant Organization Support (12 hours)
# Team-based API management and billing with RBAC
# ════════════════════════════════════════════════════════════════════════════

# PostgreSQL schema migration for organizations (idempotent)
locals {
  org_database_schema = {
    organizations = {
      columns = {
        id          = "UUID PRIMARY KEY"
        name        = "VARCHAR(255) NOT NULL"
        tier        = "VARCHAR(20) NOT NULL DEFAULT 'free'"
        created_at  = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        owner_id    = "UUID REFERENCES users(id) NOT NULL"
        max_members = "INT DEFAULT 10"
        metadata    = "JSONB DEFAULT '{}'"
      }
      indexes = [
        "owner_id",
        "tier",
        "created_at"
      ]
    }
    
    organization_members = {
      columns = {
        id        = "UUID PRIMARY KEY"
        org_id    = "UUID REFERENCES organizations(id) NOT NULL"
        user_id   = "UUID REFERENCES users(id) NOT NULL"
        role      = "VARCHAR(50) NOT NULL" # admin, developer, auditor, viewer
        joined_at = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        metadata  = "JSONB DEFAULT '{}'"
      }
      indexes = [
        "org_id",
        "user_id",
        "role"
      ]
    }
    
    organization_api_keys = {
      columns = {
        id             = "UUID PRIMARY KEY"
        org_id         = "UUID REFERENCES organizations(id) NOT NULL"
        key_hash       = "VARCHAR(256) NOT NULL UNIQUE"
        name           = "VARCHAR(255) NOT NULL"
        created_at     = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        rotated_at     = "TIMESTAMP"
        expires_at     = "TIMESTAMP"
        last_used_at   = "TIMESTAMP"
        permissions    = "JSONB DEFAULT '[]'"
      }
      indexes = [
        "org_id",
        "key_hash",
        "expires_at"
      ]
    }
  }

  # RBAC roles (single source of truth)
  rbac_roles = {
    admin = {
      description = "Full organization management, billing, API keys"
      permissions = [
        "org:read",
        "org:update",
        "org:delete",
        "members:*",
        "api_keys:*",
        "billing:*",
        "logs:read"
      ]
    }
    developer = {
      description = "Create/view API keys, read analytics"
      permissions = [
        "org:read",
        "api_keys:create",
        "api_keys:read",
        "api_keys:delete",
        "analytics:read",
        "logs:read"
      ]
    }
    auditor = {
      description = "Read-only access to logs and analytics"
      permissions = [
        "org:read",
        "analytics:read",
        "logs:read",
        "api_keys:read"
      ]
    }
    viewer = {
      description = "Read-only access to public schemas"
      permissions = [
        "org:read",
        "schemas:read"
      ]
    }
  }
}

# PostgreSQL migration for organizations
# Canonical K8s manifest is: kubernetes/phase-26-organizations/organization-api.yaml
# This resource generates the idempotent SQL migration file only (no K8s overlap)
resource "local_file" "phase_26c_org_migration" {
  filename = "${path.module}/../db/migrations/phase-26c-organizations-generated.sql"

  content = <<-SQL
    -- Phase 26-C: Organization schema migration (idempotent)
    -- Generated by phase-26c-organizations.tf — DO NOT EDIT MANUALLY
    -- Canonical K8s: kubernetes/phase-26-organizations/organization-api.yaml

    CREATE TABLE IF NOT EXISTS organizations (
      id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      name        VARCHAR(255) NOT NULL,
      tier        VARCHAR(20)  NOT NULL DEFAULT 'free',
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      owner_id    UUID NOT NULL,
      max_members INT DEFAULT 10,
      metadata    JSONB DEFAULT '{}',
      CONSTRAINT valid_tier CHECK (tier IN ('free','pro','enterprise'))
    );

    CREATE TABLE IF NOT EXISTS organization_members (
      id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      org_id    UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      user_id   UUID NOT NULL,
      role      VARCHAR(50) NOT NULL,
      joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      metadata  JSONB DEFAULT '{}',
      UNIQUE(org_id, user_id),
      CONSTRAINT valid_role CHECK (role IN ('admin','developer','auditor','viewer'))
    );

    CREATE TABLE IF NOT EXISTS organization_api_keys (
      id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      org_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      key_hash     VARCHAR(256) NOT NULL UNIQUE,
      name         VARCHAR(255) NOT NULL,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      rotated_at   TIMESTAMP,
      expires_at   TIMESTAMP,
      last_used_at TIMESTAMP,
      permissions  JSONB DEFAULT '[]'
    );

    CREATE INDEX IF NOT EXISTS idx_org_owner   ON organizations(owner_id);
    CREATE INDEX IF NOT EXISTS idx_org_tier    ON organizations(tier);
    CREATE INDEX IF NOT EXISTS idx_org_members_org  ON organization_members(org_id);
    CREATE INDEX IF NOT EXISTS idx_org_members_user ON organization_members(user_id);
    CREATE INDEX IF NOT EXISTS idx_org_keys_org     ON organization_api_keys(org_id);
    CREATE INDEX IF NOT EXISTS idx_org_keys_hash    ON organization_api_keys(key_hash);
  SQL
}

output "phase_26c_schema" {
  description = "PostgreSQL schema for organization support"
  value       = local.org_database_schema
}

output "phase_26c_rbac_config" {
  description = "RBAC roles and permissions"
  value       = local.rbac_roles
}

output "phase_26c_status" {
  description = "Phase 26-C implementation status"
  value = {
    status      = "IMPLEMENTED"
    tables      = 3
    rbac_roles  = length(local.rbac_roles)
    features    = "Organization hierarchy, RBAC, API key management, audit logs"
    deployment  = "192.168.168.31"
  }
}
