// frontend/src/hooks/useTracing.ts
//
// React hook for accessing tracing functionality in components
// Provides easy access to span creation and trace context propagation
//
// Generated by: Phase 3 observability spine - TASK 5 (Frontend Instrumentation)

import { useEffect } from "react";
import { trace } from "@opentelemetry/api";
import { getCurrentTraceId, getCurrentSpanId } from "../otel-setup";

/**
 * Hook to create a span for a component or operation
 * @param operationName Name of the operation (e.g., "file_upload")
 * @param attributes Additional span attributes
 */
export function useSpan(operationName: string, attributes: Record<string, any> = {}) {
  const tracer = trace.getTracer("code-server-frontend");

  return {
    /**
     * Start a span and execute a function within its context
     */
    withSpan: async <T,>(fn: () => Promise<T>) => {
      return tracer.startActiveSpan(operationName, async (span) => {
        try {
          // Set attributes
          Object.entries(attributes).forEach(([key, value]) => {
            span.setAttributes({ [key]: value });
          });

          // Execute function
          const result = await fn();

          // Mark success
          span.setAttributes({ "operation.success": true });
          span.end();

          return result;
        } catch (error) {
          // Mark error
          span.recordException(error as Error);
          span.setAttributes({
            "operation.success": false,
            "error.type": (error as any)?.name || "Unknown",
          });
          span.end();

          throw error;
        }
      });
    },

    /**
     * Synchronous version of withSpan
     */
    withSpanSync: <T,>(fn: () => T) => {
      return tracer.startActiveSpan(operationName, (span) => {
        try {
          const result = fn();
          span.setAttributes({ "operation.success": true });
          return result;
        } catch (error) {
          span.recordException(error as Error);
          span.setAttributes({ "operation.success": false });
          throw error;
        } finally {
          span.end();
        }
      });
    },

    /**
     * Get current trace context
     */
    getTraceContext: () => ({
      traceId: getCurrentTraceId(),
      spanId: getCurrentSpanId(),
    }),
  };
}

/**
 * Hook to measure component render time
 */
export function useRenderTime(componentName: string) {
  useEffect(() => {
    const tracer = trace.getTracer("code-server-frontend");

    tracer.startActiveSpan(`component.render.${componentName}`, (span) => {
      // Span ends when component unmounts
      return () => {
        span.end();
      };
    });
  }, [componentName]);
}

/**
 * Hook to automatically trace API calls
 */
export function useApi<T,>(
  url: string,
  options: RequestInit = {},
): {
  data: T | null;
  loading: boolean;
  error: Error | null;
  refetch: () => Promise<T>;
} {
  const span = useSpan("api.call", {
    "http.url": url,
    "http.method": options.method || "GET",
  });

  const [data, setData] = React.useState<T | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<Error | null>(null);

  const fetch = async () => {
    try {
      setLoading(true);
      const result = await span.withSpan(async () => {
        const response = await globalThis.fetch(url, {
          ...options,
          headers: {
            ...options.headers,
            "x-trace-id": getCurrentTraceId(),
          },
        });

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        return await response.json();
      });

      setData(result);
      setError(null);
    } catch (err) {
      setError(err as Error);
      setData(null);
    } finally {
      setLoading(false);
    }
  };

  React.useEffect(() => {
    fetch();
  }, [url]);

  return { data, loading, error, refetch: fetch };
}

/**
 * Higher-order component to wrap components with tracing
 */
export function withTracing<P extends object>(
  WrappedComponent: React.ComponentType<P>,
  componentName: string,
) {
  return function TracedComponent(props: P) {
    useRenderTime(componentName);

    return <WrappedComponent {...props} />;
  };
}
