#!/usr/bin/env bash
# @file        scripts/ops/terraform-drift-detect.sh
# @module      operations/terraform
# @description Manual Terraform drift detection with GitHub issue creation capability

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../_common/init.sh"

# Require terraform command
require_command terraform

# Optional: GitHub CLI for issue creation
HAS_GH=0
if command -v gh &> /dev/null; then
  HAS_GH=1
fi

# Arguments
REPO="${1:-}"
DRY_RUN="${DRY_RUN:-0}"
OPEN_ISSUE="${OPEN_ISSUE:-0}"

# Validation
if [[ -z "$REPO" ]]; then
  log_error "Usage: $0 <repo-owner>/<repo-name> [--dry-run] [--open-issue]"
  log_error "  Example: $0 kushin77/code-server"
  exit 1
fi

# Work in terraform directory
cd terraform || log_fatal "terraform/ directory not found"

log_info "=== Terraform Drift Detection ==="
log_info "Repository: $REPO"
log_info "Working directory: $(pwd)"
log_info ""

# Initialize terraform
log_info "Initializing Terraform..."
terraform init

# Validate configuration
log_info "Validating Terraform configuration..."
terraform validate || log_fatal "Terraform validation failed"

# Run plan with detailed exit code
log_info "Running terraform plan to detect drift..."
PLAN_OUTPUT=$(mktemp)
DRIFT_DETECTED=0

# Exit codes:
# 0 = no changes
# 1 = error
# 2 = changes detected (drift)
terraform plan -detailed-exitcode -no-color -out=tfplan > "$PLAN_OUTPUT" 2>&1 || PLAN_EXIT=$?
PLAN_EXIT=${PLAN_EXIT:-0}

log_info "Terraform plan exit code: $PLAN_EXIT"
echo ""
cat "$PLAN_OUTPUT"
echo ""

if [[ $PLAN_EXIT -eq 2 ]]; then
  DRIFT_DETECTED=1
  log_warn "⚠️  DRIFT DETECTED — Infrastructure has diverged from Terraform state"
elif [[ $PLAN_EXIT -eq 0 ]]; then
  log_info "✅ No drift detected — Infrastructure matches declared state"
elif [[ $PLAN_EXIT -eq 1 ]]; then
  log_error "❌ Terraform plan failed with error"
  rm -f "$PLAN_OUTPUT"
  exit 1
fi

# Optionally create GitHub issue if drift detected
if [[ $DRIFT_DETECTED -eq 1 ]] && [[ $HAS_GH -eq 1 ]] && [[ $OPEN_ISSUE -eq 1 ]]; then
  log_info ""
  log_info "Creating GitHub issue for drift detection..."
  
  PLAN_CONTENT=$(head -100 "$PLAN_OUTPUT" | sed 's/`/`̀/g')  # Escape backticks
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  
  ISSUE_BODY="## Terraform Drift Detection Report

**Detected**: $TIMESTAMP
**Repository**: $REPO
**Exit Code**: 2 (changes detected)

### Plan Output (First 100 lines)
\`\`\`
$PLAN_CONTENT
\`\`\`

### Remediation
Run one of:
1. \`terraform apply tfplan\` — apply changes to infrastructure
2. \`terraform refresh\` — update state to match real infrastructure
3. See: docs/terraform-operations.md

**Generated by**: scripts/ops/terraform-drift-detect.sh"

  gh issue create --repo "$REPO" \
    --title "🚨 Terraform Drift Detected — Manual Check" \
    --body "$ISSUE_BODY" \
    --label infrastructure,terraform,drift-detected,P1 \
    || log_warn "Failed to create GitHub issue (are you authenticated with gh?)"
fi

# Cleanup
rm -f "$PLAN_OUTPUT"

# Exit with appropriate code
if [[ $DRIFT_DETECTED -eq 1 ]]; then
  exit 2
else
  exit 0
fi
