// src/__tests__/backend-otel-instrumentation.test.js
//
// Tests for backend OpenTelemetry instrumentation
// Validates trace context generation, propagation, and middleware behavior
//
// Generated by: Phase 3 observability spine - TASK 6 (Backend Instrumentation)

const assert = require('assert');
const express = require('express');
const { trace, context } = require('@opentelemetry/api');
const {
  initOTelBackend,
  createTraceContextMiddleware,
  createTraceContextPropagationMiddleware,
  withSpan,
  getCurrentTraceId,
  getCurrentSpanId,
} = require('../otel-backend-setup');
const {
  createStructuredLoggingMiddleware,
  createErrorLoggingMiddleware,
  logWithTrace,
} = require('../middleware/structured-logging');
const {
  addTraceContextToSQL,
  extractOperation,
} = require('../middleware/database-instrumentation');

describe('Backend OpenTelemetry Instrumentation', () => {
  // ===== SETUP =====

  before(() => {
    // Initialize OTEL for tests
    initOTelBackend();
  });

  // ===== TRACE CONTEXT GENERATION TESTS =====

  describe('Trace Context Generation', () => {
    it('should generate trace IDs within spans', (done) => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('test.operation', (span) => {
        const spanContext = span.spanContext();
        
        // Trace ID should be 32 hex characters
        assert.strictEqual(spanContext.traceId.length, 32);
        assert.match(spanContext.traceId, /^[0-9a-f]{32}$/);
        
        // Span ID should be 16 hex characters
        assert.strictEqual(spanContext.spanId.length, 16);
        assert.match(spanContext.spanId, /^[0-9a-f]{16}$/);
        
        span.end();
        done();
      });
    });

    it('should propagate trace IDs across nested spans', (done) => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('parent.span', (parentSpan) => {
        const parentTraceId = parentSpan.spanContext().traceId;
        
        tracer.startActiveSpan('child.span', (childSpan) => {
          const childTraceId = childSpan.spanContext().traceId;
          
          // Trace IDs should match
          assert.strictEqual(parentTraceId, childTraceId);
          
          // Span IDs should be different
          assert.notStrictEqual(
            parentSpan.spanContext().spanId,
            childSpan.spanContext().spanId
          );
          
          childSpan.end();
        });
        
        parentSpan.end();
        done();
      });
    });

    it('should provide getCurrentTraceId and getCurrentSpanId utilities', (done) => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('test.operation', (span) => {
        const traceId = getCurrentTraceId();
        const spanId = getCurrentSpanId();
        
        assert.strictEqual(traceId, span.spanContext().traceId);
        assert.strictEqual(spanId, span.spanContext().spanId);
        
        span.end();
        done();
      });
    });
  });

  // ===== MIDDLEWARE TESTS =====

  describe('Express Middleware Integration', () => {
    it('should add trace context headers to responses', () => {
      const app = express();
      
      app.use(createTraceContextMiddleware());
      app.get('/test', (req, res) => {
        res.json({ success: true });
      });

      // Test would require actual HTTP request
      // This is a basic structure test
      assert.ok(app._router);
    });

    it('should extract trace context from incoming requests', () => {
      const app = express();
      
      app.use(createTraceContextPropagationMiddleware());
      
      // Test middleware exists and is callable
      const middleware = createTraceContextPropagationMiddleware();
      assert.strictEqual(typeof middleware, 'function');
    });
  });

  // ===== ASYNC SPAN EXECUTION =====

  describe('withSpan Utility', () => {
    it('should execute function within span context', async () => {
      const result = await withSpan('test.operation', async (span) => {
        assert.ok(span);
        return 'test_result';
      });

      assert.strictEqual(result, 'test_result');
    });

    it('should capture exceptions in spans', async () => {
      const tracer = trace.getTracer('test');
      let exceptionCaught = false;

      try {
        await withSpan('test.error', async (span) => {
          throw new Error('Test error');
        });
      } catch (err) {
        exceptionCaught = true;
        assert.strictEqual(err.message, 'Test error');
      }

      assert.ok(exceptionCaught);
    });

    it('should set operation success attributes', async () => {
      const tracer = trace.getTracer('test');
      
      await withSpan('test.success', async (span) => {
        return 'success';
      });

      // Span should be marked successful
      // (Can't directly verify attributes without intercepting, but no error should occur)
    });

    it('should set operation failure attributes', async () => {
      const tracer = trace.getTracer('test');
      
      try {
        await withSpan('test.failure', async (span) => {
          throw new Error('Test error');
        });
      } catch (err) {
        // Error should be caught
        assert.ok(err);
      }
    });
  });

  // ===== STRUCTURED LOGGING TESTS =====

  describe('Structured Logging Middleware', () => {
    it('should create structured logging middleware', () => {
      const middleware = createStructuredLoggingMiddleware();
      assert.strictEqual(typeof middleware, 'function');
    });

    it('should create error logging middleware', () => {
      const middleware = createErrorLoggingMiddleware();
      assert.strictEqual(typeof middleware, 'function');
    });

    it('should log messages with trace context', async () => {
      const tracer = trace.getTracer('test');
      let logOutput = '';

      // Capture console.log
      const originalLog = console.log;
      console.log = (msg) => {
        logOutput = msg;
      };

      tracer.startActiveSpan('test.logging', (span) => {
        logWithTrace('INFO', 'Test message', { custom_field: 'value' });
        
        // Verify log format
        assert.ok(logOutput.includes('Test message'));
        assert.ok(logOutput.includes(span.spanContext().traceId));
        
        span.end();
      });

      console.log = originalLog;
    });
  });

  // ===== DATABASE INSTRUMENTATION TESTS =====

  describe('Database Query Instrumentation', () => {
    it('should extract operation types from SQL', () => {
      assert.strictEqual(extractOperation('SELECT * FROM users'), 'select');
      assert.strictEqual(extractOperation('INSERT INTO users VALUES (1)'), 'insert');
      assert.strictEqual(extractOperation('UPDATE users SET name = ?'), 'update');
      assert.strictEqual(extractOperation('DELETE FROM users WHERE id = 1'), 'delete');
      assert.strictEqual(extractOperation('CREATE TABLE users (...)'), 'create');
      assert.strictEqual(extractOperation('DROP TABLE users'), 'drop');
      assert.strictEqual(extractOperation('BEGIN TRANSACTION'), 'begin_transaction');
      assert.strictEqual(extractOperation('COMMIT'), 'commit');
      assert.strictEqual(extractOperation('ROLLBACK'), 'rollback');
      assert.strictEqual(extractOperation('INVALID QUERY'), 'unknown');
    });

    it('should add trace context to SQL queries', async () => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('test.db', (span) => {
        const sql = 'SELECT * FROM users WHERE id = 1';
        const enhanced = addTraceContextToSQL(sql);
        
        // Should add trace context comment
        assert.ok(enhanced.includes('trace_id'));
        assert.ok(enhanced.includes('span_id'));
        assert.ok(enhanced.includes(sql));
        
        span.end();
      });
    });

    it('should handle null trace context gracefully', () => {
      const sql = 'SELECT * FROM users';
      const enhanced = addTraceContextToSQL(sql, null, null);
      
      // Should return original SQL if no trace context
      assert.strictEqual(enhanced, sql);
    });
  });

  // ===== INTEGRATION TESTS =====

  describe('Integration Tests', () => {
    it('should maintain trace context through async operations', async () => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('integration.test', async (span) => {
        const spanContext = span.spanContext();
        
        // Simulate async operation
        const promise = new Promise(resolve => {
          setTimeout(() => {
            const activeTraceId = getCurrentTraceId();
            resolve(activeTraceId);
          }, 10);
        });
        
        // Trace ID should be propagated through async boundary
        // (Note: This test may fail depending on context propagation implementation)
        
        span.end();
      });
    });

    it('should correlate logs, traces, and database operations', async () => {
      const tracer = trace.getTracer('test');
      
      tracer.startActiveSpan('correlation.test', async (span) => {
        const traceId = getCurrentTraceId();
        
        // Simulate database operation
        const sql = 'SELECT * FROM users';
        const enhancedSql = addTraceContextToSQL(sql);
        
        // All should have same trace ID
        assert.ok(enhancedSql.includes(traceId));
        
        // Simulate logging
        logWithTrace('INFO', 'Database operation completed');
        
        // All three (trace, log, sql) share trace ID
        assert.ok(traceId);
        
        span.end();
      });
    });
  });

  // ===== PERFORMANCE TESTS =====

  describe('Performance', () => {
    it('should have minimal overhead for span creation', async () => {
      const tracer = trace.getTracer('test');
      const startTime = Date.now();
      
      for (let i = 0; i < 1000; i++) {
        tracer.startActiveSpan(`perf.test.${i}`, (span) => {
          span.end();
        });
      }
      
      const duration = Date.now() - startTime;
      
      // Should complete 1000 spans in reasonable time (< 1 second)
      assert.ok(duration < 1000, `1000 spans took ${duration}ms`);
    });

    it('should not impact request handling latency significantly', async () => {
      const tracer = trace.getTracer('test');
      
      const startTime = Date.now();
      
      tracer.startActiveSpan('request.simulation', async (span) => {
        // Simulate request processing
        for (let i = 0; i < 100; i++) {
          await new Promise(resolve => setImmediate(resolve));
        }
        span.end();
      });
      
      // Should not add significant overhead
      // (Actual latency depends on implementation)
    });
  });
});

// ===== HELPER FUNCTIONS FOR MANUAL TESTING =====

/**
 * Helper to manually test Express middleware
 * Usage: testExpressMiddleware()
 */
async function testExpressMiddleware() {
  const app = express();
  
  app.use(createTraceContextMiddleware());
  app.use(createStructuredLoggingMiddleware());
  
  app.get('/test', (req, res) => {
    res.json({
      trace_id: req.traceId,
      span_id: req.spanId,
      message: 'Trace context injected',
    });
  });
  
  // Start server
  const server = app.listen(3333, () => {
    console.log('[TEST] Express middleware test server listening on :3333');
    console.log('[TEST] Try: curl -v http://localhost:3333/test');
  });
  
  return server;
}

module.exports = {
  testExpressMiddleware,
};
