apiVersion: v1
kind: Service
metadata:
  name: embeddings
  namespace: agents
  labels:
    app: embeddings
spec:
  type: ClusterIP
  selector:
    app: embeddings
  ports:
    - port: 8001
      targetPort: 8001
