#!/usr/bin/env bash
# @file        scripts/_common/docs-gap-analyzer.sh
# @module      docs/gap-analyzer
# @description Scan for missing documentation files and auto-create GitHub issues
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/_common/init.sh"
source "$SCRIPT_DIR/_common/github-api-client.sh"

readonly REPO="${REPO:-kushin77/code-server}"
readonly DOCS_DIR="${DOCS_DIR:-docs}"

# Required documentation files
declare -A REQUIRED_DOCS=(
  [OVERVIEW.md]="High-level overview of the project and architecture"
  [DEPLOYMENT-RUNBOOK.md]="Step-by-step deployment instructions"
  [SECURITY-GUIDE.md]="Security practices and vulnerability reporting"
  [TEST-PLAN.md]="Testing strategy and how to run tests"
  [API-REFERENCE.md]="API endpoints and usage documentation"
  [CHANGELOG.md]="Version history and release notes"
  [CONTRIBUTING.md]="How to contribute to the project"
  [TROUBLESHOOTING.md]="Common issues and solutions"
)

# Scan for missing docs
find_missing_docs() {
  log_info "Scanning for missing documentation files..."
  
  local missing_count=0
  
  for doc in "${!REQUIRED_DOCS[@]}"; do
    if [[ ! -f "$DOCS_DIR/$doc" ]]; then
      log_warn "Missing: $doc"
      missing_count+=1
    else
      log_info "✓ Found: $doc"
    fi
  done
  
  log_info "Found $missing_count missing documentation files"
  return $missing_count
}

# Check for broken links in documentation
check_broken_links() {
  log_info "Checking for broken links in documentation..."
  
  if [[ ! -d "$DOCS_DIR" ]]; then
    log_warn "Docs directory not found"
    return 1
  fi
  
  local broken_count=0
  local md_files
  md_files=$(find "$DOCS_DIR" -name "*.md" -type f)
  
  while IFS= read -r file; do
    # Extract links from markdown
    local links
    links=$(grep -oE '\[([^\]]+)\]\(([^)]+)\)' "$file" 2>/dev/null || true)
    
    while IFS= read -r link; do
      local url
      url=$(echo "$link" | sed 's/.*(\(.*\)).*/\1/')
      
      # Skip external URLs
      if [[ "$url" =~ ^https?:// ]]; then
        continue
      fi
      
      # Check if local file exists
      if [[ ! "$url" =~ ^# ]] && [[ ! -f "$DOCS_DIR/$url" ]]; then
        log_warn "Broken link in $file: $url"
        broken_count+=1
      fi
    done <<< "$links"
  done <<< "$md_files"
  
  log_info "Found $broken_count broken links"
  return $broken_count
}

# Create issue for missing documentation
create_doc_issue() {
  local doc_name="$1"
  local description="$2"
  local token
  token=$(github_get_token)
  
  # Check if issue already exists
  local search_response
  search_response=$(github_api_call GET "/search/issues?q=repo:$REPO%20\"Missing%20documentation:%20$doc_name\"" || echo "{}")
  
  local existing_count
  existing_count=$(echo "$search_response" | jq '.total_count // 0')
  
  if [[ "$existing_count" -gt 0 ]]; then
    log_info "Issue already exists for $doc_name"
    return 0
  fi
  
  log_info "Creating issue for missing documentation: $doc_name..."
  
  local title="Missing documentation: $doc_name"
  local body="**Documentation File:** \`$doc_name\`

**Description:** $description

**Location:** [\`docs/$doc_name\`](https://github.com/$REPO/tree/main/docs)

**Action Items:**
- [ ] Write comprehensive documentation
- [ ] Include code examples
- [ ] Link from main README
- [ ] Verify links work correctly

---
*Auto-generated by Documentation Gap Analyzer*"
  
  github_api_call POST "/repos/$REPO/issues" \
    "{
      \"title\": \"$title\",
      \"body\": \"$body\",
      \"labels\": [\"documentation\", \"auto-generated\", \"P2\"]
    }" || log_error "Failed to create issue for $doc_name"
  
  log_info "✓ Issue created for $doc_name"
}

# Scan and file issues for all missing docs
scan_and_create_doc_issues() {
  log_info "Documentation Gap Analysis starting..."
  
  local created_count=0
  
  for doc in "${!REQUIRED_DOCS[@]}"; do
    if [[ ! -f "$DOCS_DIR/$doc" ]]; then
      create_doc_issue "$doc" "${REQUIRED_DOCS[$doc]}"
      created_count+=1
    fi
  done
  
  log_info "✓ Created $created_count issues for missing documentation"
}

# Generate report
generate_docs_report() {
  log_info "Generating documentation gap report..."
  
  local report_file="docs-gap-analysis.json"
  local missing_array="[]"
  local present_array="[]"
  
  for doc in "${!REQUIRED_DOCS[@]}"; do
    if [[ ! -f "$DOCS_DIR/$doc" ]]; then
      missing_array=$(echo "$missing_array" | jq --arg doc "$doc" --arg desc "${REQUIRED_DOCS[$doc]}" \
        '. += [{"name": $doc, "description": $desc}]')
    else
      present_array=$(echo "$present_array" | jq --arg doc "$doc" --arg desc "${REQUIRED_DOCS[$doc]}" \
        '. += [{"name": $doc, "description": $desc}]')
    fi
  done
  
  local report
  report=$(jq -n \
    --argjson missing "$missing_array" \
    --argjson present "$present_array" \
    '{timestamp: now | floor, repo: $ENV.REPO, missing_docs: $missing, present_docs: $present}')
  
  echo "$report" > "$report_file"
  log_info "✓ Report generated: $report_file"
}

export -f find_missing_docs check_broken_links create_doc_issue scan_and_create_doc_issues generate_docs_report

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-scan}" in
    scan) find_missing_docs && scan_and_create_doc_issues ;;
    find) find_missing_docs ;;
    links) check_broken_links ;;
    report) generate_docs_report ;;
    all) find_missing_docs && check_broken_links && scan_and_create_doc_issues && generate_docs_report && log_info "✓ Documentation gap analysis complete" ;;
    *) echo "Usage: $0 {scan|find|links|report|all}" ;;
  esac
fi
