#!/usr/bin/env bash
# @file        scripts/_common/pmo-todo-scanner.sh
# @module      pmo/todo-scanner
# @description Auto-create GitHub issues from TODO/FIXME/HACK patterns
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/_common/init.sh"
source "$SCRIPT_DIR/_common/github-api-client.sh"

readonly REPO="${REPO:-kushin77/code-server}"
readonly WORK_DIR="${WORK_DIR:-.}"

# Find all TODO/FIXME/HACK patterns in code
find_todos_in_code() {
  log_info "Scanning for TODO/FIXME/HACK patterns..."
  find "$WORK_DIR" -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.py" -o -name "*.sh" \) \
    -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/__pycache__/*" \
    -not -path "*/scripts/_common/pmo-todo-scanner.sh" 2>/dev/null | \
    xargs grep -n "TODO\|FIXME\|HACK" 2>/dev/null || true
}

# Parse TODO item from grep output
parse_todo_item() {
  local line="$1"
  local file line_num type content priority
  file=$(echo "$line" | cut -d: -f1)
  line_num=$(echo "$line" | cut -d: -f2)
  type=$(echo "$line" | grep -oE "TODO|FIXME|HACK" | head -1)
  content=$(echo "$line" | sed 's/.*\(TODO\|FIXME\|HACK\)://' | sed 's/^ *//' | head -c 80)
  
  case "$type" in
    FIXME) priority="P1" ;;
    TODO)  priority="P2" ;;
    HACK)  priority="P3" ;;
    *)     priority="P2" ;;
  esac
  
  printf '%s\t%s\t%s\t%s\t%s\n' "$file" "$line_num" "$type" "$content" "$priority"
}

# Check if issue already exists
todo_issue_exists() {
  local file="$1" line_num="$2" type="$3"
  local token response count
  token=$(github_get_token)
  response=$(github_api_call GET "/search/issues?q=repo:$REPO%20\"$file:$line_num\"" 2>/dev/null || echo "{}")
  count=$(printf '%s' "$response" | python3 -c 'import json,sys
try:
  data=json.load(sys.stdin)
  print(data.get("total_count", 0))
except Exception:
  print(0)
')
  [[ "$count" -gt 0 ]] && return 0 || return 1
}

# Create GitHub issue from TODO
create_issue_from_todo() {
  local file="$1" line_num="$2" type="$3" content="$4" priority="$5"
  local token
  token=$(github_get_token)
  
  if todo_issue_exists "$file" "$line_num" "$type"; then
    log_info "Issue already exists for $file:$line_num"
    return 0
  fi
  
  log_info "Creating issue: [$type] $content ($file:$line_num, $priority)..."
  
  local title="[$type] $content"
  local body="**Location:** [\`$file:$line_num\`](https://github.com/$REPO/blob/main/$file#L$line_num)
**Type:** $type
---
*Auto-generated by PMO Todo Scanner*"
  
  local labels="[\"auto-generated\",\"${type,,}\",\"$priority\"]"
  local payload
  payload=$(python3 -c 'import json,sys; print(json.dumps({"title": sys.argv[1], "body": sys.argv[2], "labels": json.loads(sys.argv[3])}))' "$title" "$body" "$labels")
  github_api_call POST "/repos/$REPO/issues" "$payload" || log_error "Failed to create issue"
  
  log_info "✓ Issue created"
}

# Main entry point
scan_and_create_issues() {
  log_info "PMO Todo Scanner starting..."
  local created=0 skipped=0

  while IFS=$'\t' read -r file line_num type content priority; do
    [[ -z "$file" ]] && continue
    create_issue_from_todo "$file" "$line_num" "$type" "$content" "$priority" && created+=1 || skipped+=1
  done < <(find_todos_in_code | while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    parse_todo_item "$line"
  done)

  log_info "✓ Scan complete"
}

export -f find_todos_in_code parse_todo_item todo_issue_exists create_issue_from_todo scan_and_create_issues

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-scan}" in
    scan) scan_and_create_issues ;;
    find) find_todos_in_code ;;
    *) echo "Usage: $0 {scan|find}" ;;
  esac
fi
