apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      cacheTimeout: 60

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: traceID=(\w+)
          name: TraceID
          url: 'http://jaeger:16686/trace/$${__value.raw}'

  - name: AlertManager
    type: alertlist
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
