#!/usr/bin/env bash
# @file        scripts/pmo/handoff-write.sh
# @module      pmo/session
# @description Write structured handoff at end of Copilot session for continuity
# @owner       PMO Framework
# @status      active
#
# Accepts session state (sub-issue, step, blockers, notes) and writes to
# /memories/session/epic-N-handoff.md for zero-context-loss resumption.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MEMORIES_DIR="${MEMORIES_DIR:-.}"
SUB_ISSUE="${1}"
STEP="${2:-}"
BLOCKER="${3:-}"
NOTES="${4:-}"

# Source logging
if [[ -f "$SCRIPT_DIR/scripts/_common/logging.sh" ]]; then
    source "$SCRIPT_DIR/scripts/_common/logging.sh"
else
    log_info() { echo "[INFO] $*"; }
    log_warn() { echo "[WARN] $*"; }
fi

[[ -z "$SUB_ISSUE" ]] && { echo "Usage: $0 <sub_issue_number> [step] [blocker] [notes]"; exit 1; }

mkdir -p "$MEMORIES_DIR/session"

# Extract epic number from issue (assuming format like 1576 for epic 1575)
EPIC_NUMBER="1575"
HANDOFF_FILE="$MEMORIES_DIR/session/epic-${EPIC_NUMBER}-handoff.md"

cat > "$HANDOFF_FILE" << EOF
# Epic #$EPIC_NUMBER Handoff — Session End

**Written:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Next Sub-Issue:** #$SUB_ISSUE
**Step:** $STEP
**Blocker Status:** ${BLOCKER:-None}

## Continuation Instructions

1. Review epic lock file: \`cat $MEMORIES_DIR/session/epic-lock.md\`
2. Read this handoff: \`cat $HANDOFF_FILE\`
3. Check the current sub-issue: \`gh issue view $SUB_ISSUE --repo kushin77/code-server\`
4. Resume from: **$STEP**
5. If blocked: **${BLOCKER:-None}**

## Session Notes
${NOTES:-No additional notes}

## Previous Work
- Check git log for recent commits on this branch
- Review PR #N if one was opened
- Check GitHub issue #$SUB_ISSUE for comments and status

## Next Steps
1. Checkout feature branch: \`git checkout feat/pmo-001-*-$SUB_ISSUE-*\`
2. Continue from step: $STEP
3. Follow the sub-issue instructions on GitHub
4. When complete: \`bash scripts/pmo/complete-issue.sh kushin77/code-server $SUB_ISSUE\`
5. Write next handoff: \`bash scripts/pmo/handoff-write.sh <next_issue> "<step>" "<blocker>"\`

---
Generated by scripts/pmo/handoff-write.sh
EOF

log_info "✓ Handoff written to: $HANDOFF_FILE"
log_info ""
log_info "Resume on next session with:"
log_info "  bash scripts/pmo/handoff-read.sh"
