#!/usr/bin/env bash
# @file        scripts/pmo/session-start.sh
# @module      pmo/session
# @description Initiate Copilot session lock to highest-priority open epic
# @owner       PMO Framework
# @status      active
#
# Selects the highest-priority (P0 > P1 > P2 > P3) open epic from GitHub,
# creates session lock file, and prints resume instructions for Copilot.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPO="${1:-kushin77/code-server}"
MEMORIES_DIR="${MEMORIES_DIR:-.}"

# Source logging (fallback if unavailable)
if [[ -f "$SCRIPT_DIR/scripts/_common/logging.sh" ]]; then
    source "$SCRIPT_DIR/scripts/_common/logging.sh"
else
    log_info() { echo "[INFO] $*"; }
    log_warn() { echo "[WARN] $*"; }
    log_error() { echo "[ERROR] $*"; }
fi

log_info "Starting PMO session for repository: $REPO"

# Query open epics with priority labels, sorted by priority
EPIC_QUERY='is:open label:epic (label:P0 OR label:P1 OR label:P2 OR label:P3) repo:'"$REPO"

log_info "Searching for highest-priority open epic..."
EPICS=$(gh search issues --repo "$REPO" "$EPIC_QUERY" --limit 10 --json number,title,labels)

if [[ -z "$EPICS" ]]; then
    log_error "No open epics found in $REPO"
    log_info "Create an epic issue with labels: epic, P0/P1/P2/P3"
    exit 1
fi

# Parse first (highest-priority) epic
EPIC_NUMBER=$(echo "$EPICS" | jq -r '.[0].number')
EPIC_TITLE=$(echo "$EPICS" | jq -r '.[0].title')
EPIC_LABELS=$(echo "$EPICS" | jq -r '.[0].labels[].name' | tr '\n' ',')

log_info "✓ Selected EPIC: #$EPIC_NUMBER — $EPIC_TITLE"
log_info "  Labels: $EPIC_LABELS"

# Create session lock file
mkdir -p "$MEMORIES_DIR/session"
LOCK_FILE="$MEMORIES_DIR/session/epic-lock.md"

cat > "$LOCK_FILE" << EOF
# PMO Session Lock

**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Repository:** $REPO
**Locked Epic:** #$EPIC_NUMBER — $EPIC_TITLE
**Status:** LOCKED

## Rules
1. Do NOT work on any other epic while this lock is active
2. Execute sub-issues in strict linear order (A → B → C → ...)
3. Follow 4-gate completion: commit → merge → deploy → clean
4. Before ending session: run handoff-write.sh with next sub-issue and step
5. Do NOT abandon epic unless explicitly approved

## Unlock Instructions
\`\`\`bash
rm -f $LOCK_FILE
\`\`\`

---
Generated by scripts/pmo/session-start.sh
EOF

log_info "✓ Created session lock: $LOCK_FILE"

# Print resume instructions
cat << EOF

┌─────────────────────────────────────────────────────────────┐
│ PMO SESSION STARTED                                         │
├─────────────────────────────────────────────────────────────┤
│ EPIC #$EPIC_NUMBER: $EPIC_TITLE
│
│ Next Steps:
│   1. Review EPIC #$EPIC_NUMBER on GitHub
│   2. Start with the first sub-issue (A)
│   3. Follow each sub-issue's step-by-step instructions
│   4. After completing each sub-issue: run complete-issue.sh #N
│   5. Before ending session: bash scripts/pmo/handoff-write.sh
│
│ Lock File: $LOCK_FILE
│ Release:   rm -f $LOCK_FILE
└─────────────────────────────────────────────────────────────┘

EOF

log_info "✅ Session ready. Lock active."
