---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-server
  namespace: prod
  labels:
    app: code-server
    iam-role: workload/viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: prod
  labels:
    app: backstage
    iam-role: workload/operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appsmith
  namespace: prod
  labels:
    app: appsmith
    iam-role: workload/operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: prod
  labels:
    app: ollama
    iam-role: workload/viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    iam-role: workload/viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
    iam-role: workload/viewer
