#!/bin/bash
#
# Installation script for backup cron jobs
# Usage: sudo bash install-backup-cronjobs.sh
#

BACKUP_SCRIPT_DIR="/home/akushnir/code-server/scripts/backup"
CRON_FILE="/etc/cron.d/code-server-backups"
ENV_FILE="$BACKUP_SCRIPT_DIR/code-server-backup-env.sh"

echo "Installing Code Server Backup Cron Jobs..."
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo "ERROR: This script must be run with sudo"
  exit 1
fi

# Check if backup scripts exist
if [ ! -d "$BACKUP_SCRIPT_DIR" ]; then
  echo "ERROR: Backup script directory not found: $BACKUP_SCRIPT_DIR"
  exit 1
fi

# Create cron file
cat > "$CRON_FILE" << 'EOF'
# Code Server Automated Backup Cron Jobs
# ========================================
# Generated by install-backup-cronjobs.sh

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Environment setup
BACKUP_SCRIPT_DIR=/home/akushnir/code-server/scripts/backup
ENV_FILE=$BACKUP_SCRIPT_DIR/code-server-backup-env.sh

# PostgreSQL: Hourly full backups (0 minutes past each hour)
0 * * * * root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/backup-postgres.sh" >> /var/log/code-server-backup-postgres.log 2>&1

# Redis: Hourly backups (15 minutes past each hour)  
15 * * * * root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/backup-redis.sh" >> /var/log/code-server-backup-redis.log 2>&1

# Docker Volumes: Daily backup at 2:00 AM
0 2 * * * root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/backup-volumes.sh" >> /var/log/code-server-backup-volumes.log 2>&1

# Backup Verification: Daily at 4:00 AM
0 4 * * * root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/verify-backups.sh" >> /var/log/code-server-backup-verify.log 2>&1

# Daily Report: 5:00 AM
0 5 * * * root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/backup-report.sh" >> /var/log/code-server-backup-report.log 2>&1

# Monthly Recovery Test: First Monday at 3:00 AM
0 3 1-7 * * [ "$(date +\%A)" = "Monday" ] && root source "$ENV_FILE" && bash "$BACKUP_SCRIPT_DIR/monthly-recovery-test.sh" >> /var/log/code-server-recovery-test.log 2>&1
EOF

# Set proper permissions
chmod 644 "$CRON_FILE"

echo "✅ Cron job file installed: $CRON_FILE"
echo ""
echo "Installed Cron Jobs:"
echo "  • PostgreSQL backup: Every hour at minute 0"
echo "  • Redis backup: Every hour at minute 15"
echo "  • Volume backup: Daily at 2:00 AM"
echo "  • Backup verification: Daily at 4:00 AM"
echo "  • Daily report: Daily at 5:00 AM"
echo "  • Monthly recovery test: 1st Monday at 3:00 AM"
echo ""
echo "Log Files:"
echo "  • /var/log/code-server-backup-postgres.log"
echo "  • /var/log/code-server-backup-redis.log"
echo "  • /var/log/code-server-backup-volumes.log"
echo "  • /var/log/code-server-backup-verify.log"
echo "  • /var/log/code-server-backup-report.log"
echo "  • /var/log/code-server-recovery-test.log"
echo ""
echo "To verify installation:"
echo "  sudo crontab -l | grep -A 20 'Code Server'"
echo ""
echo "To manually test a backup:"
echo "  sudo source $ENV_FILE && bash $BACKUP_SCRIPT_DIR/backup-postgres.sh"
echo ""
