modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 204, 206, 300, 301, 302, 304, 307, 308]
      method: GET
      no_follow_redirects: false
      prefer_ipv4: false
      tls_config:
        insecure_skip_verify: false
      headers:
        User-Agent: Prometheus Blackbox Exporter
      follow_redirects: true
      body_size_limit: 100MB
      compression: gzip

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 204, 206, 300, 301, 302, 304, 307, 308]
      headers:
        Content-Type: application/json
      body_size_limit: 100MB

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: ip4

  tcp_connect_tls:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: ip4

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4

  dns_a:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: ip4
      query_name: "ide.kushnir.cloud"
      query_type: "A"

  prometheus_health:
    prober: http
    timeout: 3s
    http:
      method: GET
      valid_status_codes: [200]
      path: "/-/healthy"
      headers:
        User-Agent: Prometheus Blackbox Exporter
