// frontend/src/otel-setup.ts
//
// OpenTelemetry SDK initialization for code-server frontend
// Sets up automatic instrumentation for HTTP calls, performance metrics, and manual spans
//
// Generated by: Phase 3 observability spine - TASK 5 (Frontend Instrumentation)

import { initializeInstrumentation } from "@opentelemetry/auto-instrumentations-web";
import { Resource } from "@opentelemetry/resources";
import { SemanticResourceAttributes } from "@opentelemetry/semantic-conventions";
import { BatchSpanProcessor } from "@opentelemetry/sdk-trace-web";
import { WebTracerProvider } from "@opentelemetry/sdk-trace-web";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { FetchInstrumentation } from "@opentelemetry/instrumentation-fetch";
import { XMLHttpRequestInstrumentation } from "@opentelemetry/instrumentation-xml-http-request";
import { ConsoleSpanExporter } from "@opentelemetry/sdk-trace-web";
import { context, trace } from "@opentelemetry/api";

/**
 * Initialize OpenTelemetry for the code-server frontend
 * Must be called BEFORE any application code runs
 */
export function initOTel() {
  // Get environment configuration
  const environment = import.meta.env.MODE || "development";
  const isProduction = environment === "production";
  const otelEndpoint = import.meta.env.VITE_OTEL_ENDPOINT || "http://localhost:4318";
  const samplingRate =
    environment === "production" ? 0.01 : environment === "staging" ? 0.1 : 1.0;

  // Create resource with metadata
  const resource = Resource.default().merge(
    new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: "code-server-frontend",
      [SemanticResourceAttributes.SERVICE_VERSION]: import.meta.env.VITE_APP_VERSION || "0.1.0",
      [SemanticResourceAttributes.SERVICE_NAMESPACE]: "production",
      environment,
    }),
  );

  // Create tracer provider
  const tracerProvider = new WebTracerProvider({ resource });

  // Export spans to OTLP backend
  const otlpExporter = new OTLPTraceExporter({
    url: `${otelEndpoint}/v1/traces`,
    headers: {
      "Content-Type": "application/json",
    },
    // For development, also log to console
    ...(environment !== "production" && {}),
  });

  // Batch processor to reduce overhead
  tracerProvider.addSpanProcessor(
    new BatchSpanProcessor(otlpExporter, {
      maxQueueSize: 512,
      maxExportBatchSize: 256,
      scheduledDelayMillis: 10000, // 10 seconds
    }),
  );

  // For development, also log to console
  if (!isProduction) {
    const consoleExporter = new ConsoleSpanExporter();
    tracerProvider.addSpanProcessor(new BatchSpanProcessor(consoleExporter));
  }

  // Set global tracer provider
  trace.setGlobalTracerProvider(tracerProvider);

  // Automatic HTTP instrumentation
  tracerProvider.addInstrumentation(
    new FetchInstrumentation({
      // Extract and propagate trace context
      requestHook: (span, request) => {
        // Add custom attributes to fetch spans
        span.setAttributes({
          "http.request.method": request.method,
          "http.request.body.size": request.body ? JSON.stringify(request.body).length : 0,
        });

        // Add trace context to outbound request headers
        const traceContext = trace.getActiveSpan()?.spanContext();
        if (traceContext) {
          const traceparent = formatTraceparent(traceContext);
          (request as any).headers = {
            ...(request as any).headers,
            traceparent,
            "x-trace-id": traceContext.traceId,
          };
        }
      },

      responseHook: (span, response) => {
        // Add response metadata to span
        span.setAttributes({
          "http.response.status_code": response.status,
          "http.response.content_length": response.headers.get("content-length") || 0,
        });
      },

      // Filter out noisy requests (optional)
      shouldStartSpan: (request) => {
        const url = new URL(request.url);
        // Don't trace health checks
        if (url.pathname === "/health" || url.pathname === "/healthz") {
          return false;
        }
        return true;
      },

      // Custom error handler
      onError: (error) => {
        console.error("Fetch instrumentation error:", error);
      },
    }),
  );

  // XML HttpRequest instrumentation (for legacy code)
  tracerProvider.addInstrumentation(
    new XMLHttpRequestInstrumentation({
      requestHook: (span, request) => {
        span.setAttributes({
          "http.request.method": request.method,
        });
      },

      responseHook: (span, response) => {
        span.setAttributes({
          "http.response.status_code": response.status,
        });
      },

      shouldStartSpan: (request) => {
        // Don't trace health checks
        if (request.url && (request.url.includes("/health") || request.url.includes("/healthz"))) {
          return false;
        }
        return true;
      },
    }),
  );

  // Generate and store trace ID for this page load
  const pageTraceId = generateTraceId();
  sessionStorage.setItem("trace_id", pageTraceId);
  sessionStorage.setItem("span_id", generateSpanId());

  // Log to console in development
  if (!isProduction) {
    console.log(`[OTEL] Initialized for ${environment} environment`);
    console.log(`[OTEL] Trace ID: ${pageTraceId}`);
    console.log(`[OTEL] Sampling rate: ${samplingRate}`);
    console.log(`[OTEL] Backend: ${otelEndpoint}`);
  }

  // Return tracer for use in app code
  return trace.getTracer("code-server-frontend");
}

/**
 * Generate a random trace ID (32 hex characters)
 */
function generateTraceId(): string {
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return Array.from(array, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * Generate a random span ID (16 hex characters)
 */
function generateSpanId(): string {
  const array = new Uint8Array(8);
  crypto.getRandomValues(array);
  return Array.from(array, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * Format trace context as W3C Trace Context (traceparent header)
 * Format: 00-<trace_id>-<span_id>-<trace_flags>
 */
function formatTraceparent(spanContext: any): string {
  const traceFlags = spanContext.traceFlags & 0x01 ? "01" : "00";
  return `00-${spanContext.traceId}-${spanContext.spanId}-${traceFlags}`;
}

/**
 * Helper to get the current trace ID from storage
 */
export function getCurrentTraceId(): string {
  return sessionStorage.getItem("trace_id") || "";
}

/**
 * Helper to get the current span ID from storage
 */
export function getCurrentSpanId(): string {
  return sessionStorage.getItem("span_id") || "";
}

/**
 * Helper to create a manual span for custom operations
 */
export function createSpan(name: string, attributes: Record<string, any> = {}) {
  const tracer = trace.getTracer("code-server-frontend");
  return tracer.startActiveSpan(name, (span) => {
    // Add attributes
    Object.entries(attributes).forEach(([key, value]) => {
      span.setAttributes({ [key]: value });
    });

    return span;
  });
}
