#!/bin/bash
################################################################################
# File: automated-iac-validation.sh
# Owner: Infrastructure/DevOps Team
# Purpose: Validate Infrastructure-as-Code posture and generate an audit report
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"
AUDIT_FILE="${SCRIPT_DIR}/IaC-AUDIT-REPORT.md"

if [ -f "${SCRIPT_DIR}/_common/init.sh" ]; then
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/_common/init.sh"
fi

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

pass() {
  echo "  PASS: $1"
  PASS_COUNT=$((PASS_COUNT + 1))
}

fail() {
  echo "  FAIL: $1"
  FAIL_COUNT=$((FAIL_COUNT + 1))
}

warn() {
  echo "  WARN: $1"
  WARN_COUNT=$((WARN_COUNT + 1))
}

echo "============================================================"
echo "IaC VALIDATION AUDIT"
echo "============================================================"

echo "TEST 1: Terraform configuration exists"
if [ -f "${PARENT_DIR}/main.tf" ] || [ -f "${PARENT_DIR}/terraform/main.tf" ]; then
  pass "Terraform configuration found"
else
  fail "Terraform configuration missing"
fi

echo "TEST 2: Docker Compose is generated by IaC"
if [ -f "${PARENT_DIR}/docker-compose.yml" ] && grep -q "GENERATED by Terraform" "${PARENT_DIR}/docker-compose.yml"; then
  pass "docker-compose.yml is Terraform-generated"
else
  warn "docker-compose.yml generation marker missing"
fi

echo "TEST 3: Caddyfile present"
if [ -f "${PARENT_DIR}/Caddyfile" ] || [ -f "${PARENT_DIR}/config/caddy/Caddyfile" ]; then
  pass "Caddyfile found"
else
  fail "Caddyfile missing"
fi

echo "TEST 4: Environment template exists"
if [ -f "${PARENT_DIR}/.env.example" ] || [ -f "${PARENT_DIR}/.env.template" ]; then
  pass "Environment template present"
else
  warn "Environment template missing"
fi

echo "TEST 5: Secret placeholders are not hardcoded in compose"
if grep -E "password\s*[:=]\s*[A-Za-z0-9]" "${PARENT_DIR}/docker-compose.yml" >/dev/null 2>&1; then
  warn "Potential hardcoded secret patterns detected"
else
  pass "No obvious hardcoded secret patterns"
fi

echo "TEST 6: Automation scripts are version controlled"
if git -C "${PARENT_DIR}" ls-files --error-unmatch "scripts/automated-deployment-orchestration.sh" >/dev/null 2>&1; then
  pass "Automation scripts are tracked by git"
else
  warn "Automation script tracking check inconclusive"
fi

echo "TEST 7: IaC deploy script exists"
if [ -f "${PARENT_DIR}/scripts/deploy.sh" ]; then
  pass "deploy.sh exists"
else
  fail "deploy.sh missing"
fi

echo "TEST 8: Terraform validation command available"
if command -v terraform >/dev/null 2>&1; then
  pass "terraform command available"
else
  warn "terraform command not available in current runtime"
fi

STATUS="IaC COMPLIANT"
if [ "$FAIL_COUNT" -gt 0 ]; then
  STATUS="IaC NON-COMPLIANT"
fi

cat > "$AUDIT_FILE" <<EOF
# IaC Audit Report

Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Auditor: automated-iac-validation.sh

## Summary
Status: $STATUS
Passed: $PASS_COUNT
Failed: $FAIL_COUNT
Warnings: $WARN_COUNT

## Notes
- This report is generated automatically and is safe to regenerate.
- Primary objective is deterministic Infrastructure-as-Code validation.
EOF

echo "Audit report saved to: $AUDIT_FILE"
echo "Passed: $PASS_COUNT | Failed: $FAIL_COUNT | Warnings: $WARN_COUNT"

if [ "$FAIL_COUNT" -gt 0 ]; then
  exit 1
fi

exit 0
