#!/usr/bin/env python3
"""
Structured Logging Schema Validator - CI Gate for Production Logs

Enforces W3C standard structured logging with mandatory fields:
- timestamp (ISO 8601)
- service (service identifier)
- environment (production/staging/dev)
- level (info/warn/error/debug)
- trace_id (distributed trace correlation)
- span_id (distributed span correlation)
- message (human-readable log message)
- user_id (pseudonymized if sensitive)

Validates all log entries in CI/CD pipeline before deployment.
Detects:
- Missing required fields
- Hardcoded secrets (API keys, passwords, tokens)
- PII exposure (unmasked email addresses, credit cards, SSNs)
- Invalid trace context format
- Non-compliant JSON structure

Generated by: Phase 3 observability spine - TASK 9 (CI Validation)
Date: April 16, 2026
Version: 1.0.0
"""

import json
import re
import sys
import logging
from pathlib import Path
from typing import Dict, List, Tuple, Any, Optional
from datetime import datetime
import subprocess

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(levelname)s: %(message)s'
)
logger = logging.getLogger(__name__)

# Required fields in every log entry
REQUIRED_FIELDS = {
    'timestamp': 'ISO 8601 format (YYYY-MM-DDTHH:MM:SS.sssZ)',
    'service': 'Service name (e.g., code-server, api, worker)',
    'environment': 'Environment (production, staging, development)',
    'level': 'Log level (info, warn, error, debug)',
    'trace_id': 'W3C trace ID (128-bit hex, optional but recommended)',
    'span_id': 'W3C span ID (64-bit hex, optional but recommended)',
    'message': 'Human-readable message',
}

# Optional fields with recommendations
RECOMMENDED_FIELDS = {
    'user_id': 'Pseudonymized user identifier (hashed, not raw email)',
    'request_id': 'HTTP request ID for correlation',
    'duration_ms': 'Operation duration in milliseconds',
    'status_code': 'HTTP status code (3-digit number)',
    'error': 'Error message if applicable',
    'stack_trace': 'Stack trace for errors',
    'context': 'Additional structured context',
}

# Secret detection patterns (PII/credentials)
SECRET_PATTERNS = {
    'api_key': [
        r'api[_-]?key["\']?\s*[:=]\s*["\']?([a-zA-Z0-9]{32,})["\']?',
        r'apikey["\']?\s*[:=]\s*["\']?([a-zA-Z0-9]{32,})["\']?',
        r'token["\']?\s*[:=]\s*["\']?(eyJ[A-Za-z0-9\-_.~]{80,})["\']?',
    ],
    'password': [
        r'password["\']?\s*[:=]\s*["\']?([^\s"\'\n]{8,})["\']?',
        r'passwd["\']?\s*[:=]\s*["\']?([^\s"\'\n]{8,})["\']?',
        r'pwd["\']?\s*[:=]\s*["\']?([^\s"\'\n]{8,})["\']?',
    ],
    'aws_key': [
        r'AKIA[0-9A-Z]{16}',  # AWS Access Key ID
        r'aws_secret_access_key["\']?\s*[:=]\s*["\']?([A-Za-z0-9/+=]{40})["\']?',
    ],
    'github_token': [
        r'github[_-]?token["\']?\s*[:=]\s*["\']?(ghp_[A-Za-z0-9_]{36,})["\']?',
        r'gh[_-]?token["\']?\s*[:=]\s*["\']?(ghp_[A-Za-z0-9_]{36,})["\']?',
    ],
    'private_key': [
        r'-----BEGIN\s*(RSA|EC|OPENSSH)\s*PRIVATE\s*KEY-----',
        r'private[_-]?key["\']?\s*[:=]\s*["\']?([A-Za-z0-9+/=]{100,})["\']?',
    ],
}

# PII patterns
PII_PATTERNS = {
    'email_unmasked': r'(?<!["\'])([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(?!["\'])',
    'phone': r'(?<!["\'])(\d{3}[-.]?\d{3}[-.]?\d{4})(?!["\'])',
    'ssn': r'(?<!["\'])(\d{3}-\d{2}-\d{4})(?!["\'])',
    'credit_card': r'(?<!["\'])(\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4})(?!["\'])',
}

# Valid trace/span ID format (W3C Trace Context)
TRACE_ID_PATTERN = re.compile(r'^[0-9a-f]{32}$')  # 128-bit hex
SPAN_ID_PATTERN = re.compile(r'^[0-9a-f]{16}$')   # 64-bit hex


class LogValidationError:
    """Represents a single validation error."""
    
    def __init__(
        self,
        error_type: str,
        severity: str,
        message: str,
        line_number: Optional[int] = None,
        field: Optional[str] = None,
        value: Optional[str] = None,
    ):
        self.error_type = error_type
        self.severity = severity  # error, warning, info
        self.message = message
        self.line_number = line_number
        self.field = field
        self.value = value
    
    def __str__(self) -> str:
        location = f":{self.line_number}" if self.line_number else ""
        return f"[{self.severity.upper()}] {self.error_type}{location}: {self.message}"


class StructuredLogValidator:
    """
    Validates log entries against schema and security rules.
    """
    
    def __init__(self):
        self.errors: List[LogValidationError] = []
        self.warnings: List[LogValidationError] = []
        self.stats = {
            'total_entries': 0,
            'valid_entries': 0,
            'invalid_entries': 0,
            'errors': 0,
            'warnings': 0,
        }
    
    def validate_log_entry(
        self,
        entry: Dict[str, Any],
        line_number: int = 0
    ) -> bool:
        """
        Validate a single log entry.
        
        Args:
            entry: Parsed JSON log entry
            line_number: Line number in log file
        
        Returns:
            True if valid, False if errors detected
        """
        self.stats['total_entries'] += 1
        has_errors = False
        
        # Check required fields
        for field, description in REQUIRED_FIELDS.items():
            if field not in entry:
                self._add_error(
                    LogValidationError(
                        error_type='MISSING_FIELD',
                        severity='error',
                        message=f"Missing required field '{field}': {description}",
                        line_number=line_number,
                        field=field,
                    )
                )
                has_errors = True
            else:
                # Validate field format
                if not self._validate_field_format(field, entry[field], line_number):
                    has_errors = True
        
        # Check for secrets
        for field, value in entry.items():
            if isinstance(value, str):
                if self._contains_secrets(value):
                    self._add_error(
                        LogValidationError(
                            error_type='SECRET_DETECTED',
                            severity='error',
                            message=f"Potential secret detected in field '{field}'",
                            line_number=line_number,
                            field=field,
                        )
                    )
                    has_errors = True
                
                # Check for PII
                if self._contains_pii(value):
                    self._add_error(
                        LogValidationError(
                            error_type='PII_DETECTED',
                            severity='warning',
                            message=f"Potential PII detected in field '{field}'",
                            line_number=line_number,
                            field=field,
                        )
                    )
        
        if has_errors:
            self.stats['invalid_entries'] += 1
        else:
            self.stats['valid_entries'] += 1
        
        return not has_errors
    
    def _validate_field_format(
        self,
        field: str,
        value: Any,
        line_number: int
    ) -> bool:
        """Validate field format according to schema."""
        has_errors = False
        
        if field == 'timestamp':
            if not isinstance(value, str):
                self._add_error(LogValidationError(
                    error_type='INVALID_TYPE',
                    severity='error',
                    message=f"Field 'timestamp' must be string, got {type(value).__name__}",
                    line_number=line_number,
                    field=field,
                ))
                has_errors = True
            else:
                try:
                    datetime.fromisoformat(value.replace('Z', '+00:00'))
                except ValueError:
                    self._add_error(LogValidationError(
                        error_type='INVALID_FORMAT',
                        severity='error',
                        message=f"Field 'timestamp' must be ISO 8601 format, got '{value}'",
                        line_number=line_number,
                        field=field,
                    ))
                    has_errors = True
        
        elif field == 'level':
            valid_levels = ['debug', 'info', 'warn', 'error', 'critical']
            if value not in valid_levels:
                self._add_error(LogValidationError(
                    error_type='INVALID_VALUE',
                    severity='error',
                    message=f"Field 'level' must be one of {valid_levels}, got '{value}'",
                    line_number=line_number,
                    field=field,
                ))
                has_errors = True
        
        elif field == 'environment':
            valid_envs = ['production', 'staging', 'development', 'test']
            if value not in valid_envs:
                self._add_error(LogValidationError(
                    error_type='INVALID_VALUE',
                    severity='warning',
                    message=f"Field 'environment' should be one of {valid_envs}, got '{value}'",
                    line_number=line_number,
                    field=field,
                ))
        
        elif field == 'trace_id':
            if value and not TRACE_ID_PATTERN.match(value):
                self._add_error(LogValidationError(
                    error_type='INVALID_FORMAT',
                    severity='warning',
                    message=f"Field 'trace_id' should be 128-bit hex (32 chars), got '{value}'",
                    line_number=line_number,
                    field=field,
                ))
        
        elif field == 'span_id':
            if value and not SPAN_ID_PATTERN.match(value):
                self._add_error(LogValidationError(
                    error_type='INVALID_FORMAT',
                    severity='warning',
                    message=f"Field 'span_id' should be 64-bit hex (16 chars), got '{value}'",
                    line_number=line_number,
                    field=field,
                ))
        
        return not has_errors
    
    def _contains_secrets(self, value: str) -> bool:
        """Check if value contains secrets/credentials."""
        for secret_type, patterns in SECRET_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, value, re.IGNORECASE):
                    return True
        return False
    
    def _contains_pii(self, value: str) -> bool:
        """Check if value contains PII."""
        for pii_type, pattern in PII_PATTERNS.items():
            if re.search(pattern, value):
                return True
        return False
    
    def _add_error(self, error: LogValidationError):
        """Add validation error."""
        if error.severity == 'error':
            self.errors.append(error)
            self.stats['errors'] += 1
        else:
            self.warnings.append(error)
            self.stats['warnings'] += 1
    
    def validate_file(self, filepath: Path) -> bool:
        """
        Validate a JSON Lines log file.
        
        Args:
            filepath: Path to .jsonl or .ndjson file
        
        Returns:
            True if all entries are valid, False otherwise
        """
        logger.info(f"Validating log file: {filepath}")
        
        with open(filepath, 'r') as f:
            for line_number, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                
                try:
                    entry = json.loads(line)
                    self.validate_log_entry(entry, line_number)
                except json.JSONDecodeError as e:
                    self._add_error(
                        LogValidationError(
                            error_type='INVALID_JSON',
                            severity='error',
                            message=f"Invalid JSON: {e}",
                            line_number=line_number,
                        )
                    )
                    self.stats['invalid_entries'] += 1
        
        return len(self.errors) == 0
    
    def print_report(self):
        """Print validation report."""
        print("\n" + "=" * 80)
        print("STRUCTURED LOGGING VALIDATION REPORT")
        print("=" * 80)
        
        print(f"\nStatistics:")
        print(f"  Total entries: {self.stats['total_entries']}")
        print(f"  Valid entries: {self.stats['valid_entries']}")
        print(f"  Invalid entries: {self.stats['invalid_entries']}")
        print(f"  Errors: {self.stats['errors']}")
        print(f"  Warnings: {self.stats['warnings']}")
        
        if self.errors:
            print(f"\n❌ ERRORS ({len(self.errors)}):")
            for error in self.errors[:10]:  # Show first 10
                print(f"  {error}")
            if len(self.errors) > 10:
                print(f"  ... and {len(self.errors) - 10} more")
        
        if self.warnings:
            print(f"\n⚠️  WARNINGS ({len(self.warnings)}):")
            for warning in self.warnings[:5]:  # Show first 5
                print(f"  {warning}")
            if len(self.warnings) > 5:
                print(f"  ... and {len(self.warnings) - 5} more")
        
        if not self.errors and not self.warnings:
            print(f"\n✅ All log entries are valid!")
        
        print("=" * 80 + "\n")
    
    def exit_code(self) -> int:
        """Return exit code for CI/CD."""
        if self.errors:
            return 1  # Fail on any errors
        if self.warnings:
            return 0  # Warnings are OK but logged
        return 0  # Success


class CIGateValidator:
    """
    CI/CD gate validator for production deployments.
    Checks logs from tests/builds before deployment approval.
    """
    
    def __init__(self):
        self.validator = StructuredLogValidator()
    
    def validate_ci_logs(self, log_files: List[Path]) -> bool:
        """
        Validate all CI logs before deployment.
        
        Args:
            log_files: List of log file paths
        
        Returns:
            True if all logs are valid
        """
        all_valid = True
        
        for log_file in log_files:
            if not log_file.exists():
                logger.warning(f"Log file not found: {log_file}")
                continue
            
            if not self.validator.validate_file(log_file):
                all_valid = False
        
        self.validator.print_report()
        return all_valid
    
    def block_deployment(self) -> bool:
        """Determine if deployment should be blocked."""
        return len(self.validator.errors) > 0


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Validate structured logging schema for production deployment'
    )
    parser.add_argument(
        'logfiles',
        nargs='+',
        type=Path,
        help='Log files to validate (.jsonl, .ndjson, or .log)'
    )
    parser.add_argument(
        '--fail-on-warnings',
        action='store_true',
        help='Treat warnings as errors'
    )
    parser.add_argument(
        '--max-errors',
        type=int,
        default=100,
        help='Maximum errors before stopping validation'
    )
    
    args = parser.parse_args()
    
    # Validate logs
    gate = CIGateValidator()
    all_valid = gate.validate_ci_logs(args.logfiles)
    
    # Handle warnings
    if args.fail_on_warnings and gate.validator.warnings:
        all_valid = False
    
    # Exit with appropriate code
    sys.exit(0 if all_valid else 1)


if __name__ == '__main__':
    main()
