#!/usr/bin/env bash
# deploy-kushnir-cloud.sh
# Idempotent deploy for <DOMAIN>/ide — fully containerised, no host mutation.
# Run on any Linux/WSL host with Docker installed.
#
# What it does:
#   1. Fetches secrets from GSM (GODADDY_KEY, GOOGLE_CLIENT_ID/SECRET, COOKIE_SECRET)
#   2. Writes .env (never committed) so docker compose picks them up
#   3. Sets GoDaddy DNS A record: DOMAIN → detected public IP
#   4. docker compose up --build -d   (all three services)
#   5. Health-checks every container
#
# Prerequisites:
#   - gcloud auth login (run once; token cached in ~/.config/gcloud)
#   - docker + docker compose plugin
#   - .env.template copied to .env and DOMAIN set (or export DOMAIN=... before running)
#   - Ports 80/443 reachable from internet (router forward + windows-port-forward.ps1 on WSL2)
#
# Usage:
#   ./scripts/deploy-kushnir-cloud.sh [--skip-dns] [--dry-run]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

SKIP_DNS=false
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-dns) SKIP_DNS=true; shift ;;
        --dry-run)  DRY_RUN=true; shift ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

log()  { echo "[$(date -u '+%H:%M:%S')] $*"; }
die()  { echo "[ERROR] $*" >&2; exit 1; }
run()  { [[ "$DRY_RUN" == true ]] && { echo "[DRY-RUN] $*"; return; }; "$@"; }

# ── Load existing .env if present (so DOMAIN etc. are available) ─────────────
if [[ -f "${REPO_DIR}/.env" ]]; then
    # Only export lines that look like KEY=value (skip comments/blanks)
    set -o allexport
    # shellcheck disable=SC1091
    source <(grep -E '^[A-Z_]+=.' "${REPO_DIR}/.env" || true)
    set +o allexport
fi

# ── Derive domain ─────────────────────────────────────────────────────────────
DOMAIN="${DOMAIN:-kushnir.cloud}"
log "Target domain: ${DOMAIN}"

# ── Step 1: Fetch secrets from GSM ───────────────────────────────────────────
log "Step 1/4: Fetching secrets from Google Secret Manager..."
if [[ "$DRY_RUN" == false ]]; then
    # shellcheck source=scripts/fetch-gsm-secrets.sh
    source "${SCRIPT_DIR}/fetch-gsm-secrets.sh"
else
    log "[DRY-RUN] Skipping GSM fetch — using existing env vars or empty placeholders"
    GODADDY_KEY="${GODADDY_KEY:-dry-run-key}"
    GODADDY_SECRET="${GODADDY_SECRET:-dry-run-secret}"
    GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
    GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
    OAUTH2_PROXY_COOKIE_SECRET="${OAUTH2_PROXY_COOKIE_SECRET:-$(openssl rand -base64 32)}"
fi

# ── Step 2: Detect public IP and set GoDaddy DNS ─────────────────────────────
if [[ "$SKIP_DNS" == false ]]; then
    log "Step 2/4: Detecting public IP and setting DNS..."
    PUBLIC_IP="${PUBLIC_IP:-$(curl -sf --max-time 5 https://api.ipify.org || curl -sf --max-time 5 https://ifconfig.me)}"
    [[ -z "$PUBLIC_IP" ]] && die "Could not detect public IP. Set PUBLIC_IP env var or pass --skip-dns."
    log "Public IP: ${PUBLIC_IP}"
    run PUBLIC_IP="$PUBLIC_IP" DOMAIN="$DOMAIN" bash "${SCRIPT_DIR}/set-godaddy-dns.sh"
    log "DNS set. Propagation takes up to 5 minutes."
else
    log "Step 2/4: Skipping DNS (--skip-dns)."
fi

# ── Step 3: Write .env and start all containers ───────────────────────────────
log "Step 3/4: Writing .env and starting Docker Compose stack..."
cd "$REPO_DIR"

CODE_SERVER_PASSWORD="${CODE_SERVER_PASSWORD:-$(openssl rand -hex 16)}"

# Write .env — idempotent (overwrites each deploy with fresh secrets from GSM)
run tee .env > /dev/null <<EOF
# Generated by deploy-kushnir-cloud.sh — DO NOT COMMIT
DOMAIN=${DOMAIN}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD}
ALLOWED_EMAIL_DOMAINS=${ALLOWED_EMAIL_DOMAINS:-*}
WORKSPACE_PATH=${WORKSPACE_PATH:-./workspace}
EOF
run chmod 600 .env

# Create workspace dir if not exists (idempotent)
run mkdir -p "${WORKSPACE_PATH:-./workspace}"

# Pull latest images then bring up all services
run docker compose pull
run docker compose up --remove-orphans -d
run docker compose ps

# ── Step 4: Health-check ──────────────────────────────────────────────────────
log "Step 4/4: Waiting for services to be healthy..."
[[ "$DRY_RUN" == false ]] && sleep 8

for svc in "code-server:8080/ide/healthz" "oauth2-proxy:4180/ping"; do
    name="${svc%%:*}"
    endpoint="http://localhost:${svc##*:}"
    if docker compose exec -T "${name}" wget -q --spider "${endpoint}" 2>/dev/null; then
        log "✅ ${name}: healthy"
    else
        log "⚠️  ${name}: not responding — docker compose logs ${name}"
    fi
done

log ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "Deploy complete!"
log ""
log "  IDE URL:         https://${DOMAIN}/ide"
log "  Google Auth:     https://${DOMAIN}/oauth2/start"
log "  code-server pw:  ${CODE_SERVER_PASSWORD}  (fallback direct access)"
log ""
log "  Move to new host:"
log "    1. Copy .env  (or re-run deploy to re-fetch from GSM)"
log "    2. docker compose up -d"
log "    3. On WSL2/Windows: .\\scripts\\windows-port-forward.ps1"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
