#!/usr/bin/env bash
# @file        scripts/error-triage-engine.sh
# @module      observability/triage
# @description Clusters error logs from Loki into SQLite and alerts on repeated patterns.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ -f "$SCRIPT_DIR/_common/init.sh" ]]; then
    source "$SCRIPT_DIR/_common/init.sh"
elif [[ -f "$PROJECT_ROOT/scripts/_common/init.sh" ]]; then
    source "$PROJECT_ROOT/scripts/_common/init.sh"
else
    echo "FATAL: Cannot source _common/init.sh"
    exit 1
fi

TRIAGE_DB="${TRIAGE_DB:-/var/lib/error-triage/error-triage.db}"
LOKI_ENDPOINT="${LOKI_ENDPOINT:-http://loki:3100}"
SQLITE3="${SQLITE3:-sqlite3}"
DAEMON_MODE=false
CHECK_INTERVAL="${ERROR_TRIAGE_INTERVAL:-300}"
MIN_OCCURRENCE_THRESHOLD="${ERROR_TRIAGE_THRESHOLD:-3}"
ERROR_TRIAGE_WINDOW="${ERROR_TRIAGE_WINDOW:-3600}"
PID_FILE="${PID_FILE:-/tmp/error-triage-engine.pid}"
ISSUE_CREATE_HELPER="${PROJECT_ROOT}/scripts/_common/issue-create-unified.sh"

init_db() {
    mkdir -p "$(dirname "$TRIAGE_DB")"
    "$SQLITE3" "$TRIAGE_DB" <<'SQL'
CREATE TABLE IF NOT EXISTS error_patterns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern_hash TEXT UNIQUE NOT NULL,
    error_message TEXT NOT NULL,
    first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    occurrence_count INTEGER DEFAULT 0,
    github_issue_number INTEGER,
    status TEXT DEFAULT 'new',
    severity TEXT DEFAULT 'HIGH'
);

CREATE TABLE IF NOT EXISTS error_occurrences (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern_id INTEGER NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source_job TEXT,
    source_pod TEXT,
    log_level TEXT,
    trace_context TEXT,
    FOREIGN KEY (pattern_id) REFERENCES error_patterns(id)
);

CREATE INDEX IF NOT EXISTS idx_pattern_hash ON error_patterns(pattern_hash);
CREATE INDEX IF NOT EXISTS idx_last_seen ON error_patterns(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_status ON error_patterns(status);
CREATE INDEX IF NOT EXISTS idx_occurrences_pattern ON error_occurrences(pattern_id);
SQL
    log_info "Triage database initialized: $TRIAGE_DB"
}

alert_on_pattern() {
count="$1"
msg="$2"
hash="$3"

existing_issue
    existing_issue=$("$SQLITE3" "$TRIAGE_DB" "SELECT github_issue_number FROM error_patterns WHERE pattern_hash = '$hash' AND github_issue_number IS NOT NULL LIMIT 1;")
    if [[ -n "$existing_issue" ]]; then
        return 0
    fi

    log_warn "Threshold reached for new error pattern ($count occurrences). Creating GitHub issue..."

    if ! gh auth status >/dev/null 2>&1; then
        log_warn "GitHub CLI is not authenticated; skipping issue creation for this cycle."
        return 0
    fi

    if [[ ! -f "$ISSUE_CREATE_HELPER" ]]; then
        log_warn "Issue creation helper not available; skipping issue creation for this cycle."
        return 0
    fi

    # shellcheck source=/dev/null
    source "$ISSUE_CREATE_HELPER"

issue_title="[AUTO-TRIAGE] Error Pattern: ${msg:0:60}..."
issue_body
    issue_body=$(cat <<'BODY'
## Automated Error Detection Report

**Pattern Hash**: HASH_PLACEHOLDER
**Hourly Frequency**: COUNT_PLACEHOLDER
**Timestamp**: $(date)

### Error Message
```text
MSG_PLACEHOLDER
```

### Triage Recommendation
1. Identify the source container/service.
2. Check for recent deployment or config changes.
3. Review related Loki logs around the first occurrence.

---
*Auto-generated by Error Triage Engine*
BODY
)

    issue_body="${issue_body//HASH_PLACEHOLDER/$hash}"
    issue_body="${issue_body//COUNT_PLACEHOLDER/$count}"
    issue_body="${issue_body//MSG_PLACEHOLDER/$msg}"

issue_url
    issue_url=$(copilot_create_issue \
        --title "$issue_title" \
        --body "$issue_body" \
        --priority P1 \
        --type infrastructure \
        --repo kushin77/code-server \
        --force-create 2>&1) || {
        log_warn "Failed to create GitHub issue for pattern $hash"
        return 1
    }

new_issue_number
    new_issue_number=$(printf '%s' "$issue_url" | grep -oE 'issues/[0-9]+' | awk -F/ '{print $NF}' || true)

    if [[ -n "$new_issue_number" ]]; then
        "$SQLITE3" "$TRIAGE_DB" "UPDATE error_patterns SET github_issue_number = $new_issue_number, status = 'alerted' WHERE pattern_hash = '$hash';"
        log_info "Linked error pattern $hash to GitHub Issue #$new_issue_number"
    else
        log_warn "Could not extract issue number from issue creation output: $issue_url"
    fi
}

query_loki() {
query='{level=~"ERROR|FATAL|error|fatal"}'
now_epoch
start_epoch
start

    now_epoch=$(date +%s)
    start_epoch=$((now_epoch - ERROR_TRIAGE_WINDOW))
    start="${start_epoch}000000000"

    log_debug "Querying Loki at $LOKI_ENDPOINT for errors since $start..."

    curl -s -G "$LOKI_ENDPOINT/loki/api/v1/query_range" \
        --data-urlencode "query=$query" \
        --data-urlencode "start=$start" \
        --data-urlencode "end=${now_epoch}000000000" \
        --data-urlencode "limit=1000" 2>/dev/null \
      | jq -r '.data.result[].values[][1]' 2>/dev/null \
      | grep -oE '(ERROR|FATAL|error|fatal).*' \
      | sort | uniq -c | sort -rn || true
}

record_error() {
count="$1"
msg="$2"
hash
escaped_msg

    hash=$(printf '%s' "$msg" | sha256sum | cut -d' ' -f1)
    escaped_msg=${msg//\'/\'\'}

    log_info "Recording pattern [$count x]: ${msg:0:80}..."

    "$SQLITE3" "$TRIAGE_DB" "INSERT OR IGNORE INTO error_patterns (pattern_hash, error_message) VALUES ('$hash', '$escaped_msg');"
    "$SQLITE3" "$TRIAGE_DB" "UPDATE error_patterns SET occurrence_count = occurrence_count + $count, last_seen = CURRENT_TIMESTAMP WHERE pattern_hash = '$hash';"

    if [[ "$count" -ge 25 ]]; then
        alert_on_pattern "$count" "$msg" "$hash"
    fi
}

scan_once() {
patterns
    patterns=$(query_loki)

    if [[ -z "${patterns// }" ]]; then
        log_info "No significant error patterns detected in the last hour."
        return 0
    fi

    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
count
msg
        count=$(echo "$line" | awk '{print $1}')
        msg=$(echo "$line" | cut -d' ' -f2-)
        if [[ -n "$count" && -n "$msg" && "$count" -ge "$MIN_OCCURRENCE_THRESHOLD" ]]; then
            record_error "$count" "$msg"
        fi
    done <<< "$patterns"

    log_info "Triage cycle complete."
}

run_daemon() {
    log_info "Starting automated error triage daemon (interval: ${CHECK_INTERVAL}s)..."
    while true; do
        scan_once
        sleep "$CHECK_INTERVAL"
    done
}

cleanup() {
    rm -f "$PID_FILE"
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --daemon)
                DAEMON_MODE=true
                shift
                ;;
            --interval)
                CHECK_INTERVAL="$2"
                shift 2
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

main() {
    parse_args "$@"
    log_info "Automated Error Triage Engine starting..."
    mkdir -p "$(dirname "$PID_FILE")"
    printf '%s\n' "$$" > "$PID_FILE"
    trap cleanup EXIT INT TERM
    init_db

    if [[ "$DAEMON_MODE" == "true" ]]; then
        run_daemon
    else
        scan_once
    fi
}

main "$@"
