#!/usr/bin/env bash
# @file        scripts/fetch-gsm-secrets.sh
# @module      operations
# @description fetch gsm secrets — on-prem code-server
# @owner       platform
# @status      active
# fetch-gsm-secrets.sh
# Fetches code-server secrets from Google Secret Manager (gcp-eiq project)
# Mimics eiq-org pattern: gcloud secrets versions access → env var injection
# Requires: gcloud auth login (or service account activation)
# Usage: source ./fetch-gsm-secrets.sh   (sources env vars into current shell)
#        ./fetch-gsm-secrets.sh > .env    (writes to env file)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_common/init.sh"

readonly GSM_PROJECT="${GSM_PROJECT:-gcp-eiq}"

fetch_gsm_secret() {
    local secret_id="$1"
    local var_name="$2"
    local value
    value=$(CLOUDSDK_CORE_DISABLE_PROMPTS=1 gcloud --quiet secrets versions access latest \
        --secret="$secret_id" \
        --project="$GSM_PROJECT" 2>/dev/null) || {
        echo "ERROR: Could not fetch $secret_id from GSM project=$GSM_PROJECT" >&2
        echo "Run: gcloud auth login   then retry" >&2
        return 1
    }
    printf -v "$var_name" '%s' "$value"
    export "$var_name"
    echo "export ${var_name}=<redacted>" >&2
}

fetch_gsm_secret_optional() {
    local secret_id="$1"
    local var_name="$2"
    local value

    value=$(CLOUDSDK_CORE_DISABLE_PROMPTS=1 gcloud --quiet secrets versions access latest \
        --secret="$secret_id" \
        --project="$GSM_PROJECT" 2>/dev/null) || return 1

    printf -v "$var_name" '%s' "$value"
    export "$var_name"
    echo "export ${var_name}=<redacted> (from $secret_id)" >&2
    return 0
}

fetch_first_available_secret() {
    local var_name="$1"
    shift

    local secret_id
    for secret_id in "$@"; do
        if fetch_gsm_secret_optional "$secret_id" "$var_name"; then
            return 0
        fi
    done

    return 1
}

echo "Fetching secrets from GSM project=${GSM_PROJECT}..." >&2

# GoDaddy API credentials (DNS management)
fetch_gsm_secret "prod-godaddy-api-key"    GODADDY_KEY
fetch_gsm_secret "prod-godaddy-api-secret" GODADDY_SECRET

# Google OAuth2 credentials (code-server login via oauth2-proxy)
fetch_gsm_secret "prod-portal-google-oauth-client-id"     GOOGLE_CLIENT_ID
fetch_gsm_secret "prod-portal-google-oauth-client-secret" GOOGLE_CLIENT_SECRET

# oauth2-proxy cookie secre
fetch_gsm_secret "prod-portal-oauth2-cookie-secret" OAUTH2_PROXY_COOKIE_SECRET

# GitHub PAT (optional): default auth token for GitHub API/gh CLI calls.
# Set GSM_GITHUB_TOKEN_SECRET to override the primary secret name.
if ! fetch_first_available_secret "GITHUB_TOKEN" \
    "${GSM_GITHUB_TOKEN_SECRET:-prod-github-token}" \
    "prod-github-pat" \
    "prod-code-server-github-token" \
    "github-token"; then
    echo "WARN: No GitHub PAT found in GSM (continuing without GITHUB_TOKEN)" >&2
fi

# Keep gh CLI compatibility: GH_TOKEN is honored by gh for API/auth calls.
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    export GH_TOKEN="$GITHUB_TOKEN"
fi

echo "All secrets fetched successfully." >&2

# Output env file format when not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cat <<EOF
# Generated by fetch-gsm-secrets.sh — DO NOT COMMI
DOMAIN=${DOMAIN:-ide.kushnir.cloud}
GODADDY_KEY=${GODADDY_KEY}
GODADDY_SECRET=${GODADDY_SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
GITHUB_TOKEN=${GITHUB_TOKEN:-}
CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD:-}
ALLOWED_EMAIL_DOMAINS=${ALLOWED_EMAIL_DOMAINS:-*}
WORKSPACE_PATH=${WORKSPACE_PATH:-/mnt/nas-56/kushin77/applications/code-server-enterprise}
CODER_DATA_PATH=${CODER_DATA_PATH:-/mnt/nas-56/code-server}
OLLAMA_DATA_PATH=${OLLAMA_DATA_PATH:-/mnt/nas-56/ollama}
EOF
fi

