#!/usr/bin/env bash
# fetch-gsm-secrets.sh
# Fetches code-server secrets from Google Secret Manager (nexusshield-prod project)
# Mimics eiq-org pattern: gcloud secrets versions access → env var injection
# Requires: gcloud auth login (or service account activation)
# Usage: source ./fetch-gsm-secrets.sh   (sources env vars into current shell)
#        ./fetch-gsm-secrets.sh > .env    (writes to env file)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_common/init.sh" || { echo "FATAL: Cannot source _common/init.sh"; exit 1; }

readonly GSM_PROJECT="${GSM_PROJECT:-nexusshield-prod}"

fetch_gsm_secret() {
    local secret_id="$1"
    local var_name="$2"
    local value
    value=$(gcloud secrets versions access latest \
        --secret="$secret_id" \
        --project="$GSM_PROJECT" 2>/dev/null) || {
        echo "ERROR: Could not fetch $secret_id from GSM project=$GSM_PROJECT" >&2
        echo "Run: gcloud auth login   then retry" >&2
        return 1
    }
    printf -v "$var_name" '%s' "$value"
    export "$var_name"
    echo "export ${var_name}=<redacted>" >&2
}

echo "Fetching secrets from GSM project=${GSM_PROJECT}..." >&2

# GoDaddy API credentials (DNS management)
fetch_gsm_secret "prod-godaddy-api-key"    GODADDY_KEY
fetch_gsm_secret "prod-godaddy-api-secret" GODADDY_SECRE

# Google OAuth2 credentials (code-server login via oauth2-proxy)
fetch_gsm_secret "prod-portal-google-oauth-client-id"     GOOGLE_CLIENT_ID
fetch_gsm_secret "prod-portal-google-oauth-client-secret" GOOGLE_CLIENT_SECRE

# oauth2-proxy cookie secre
fetch_gsm_secret "prod-portal-oauth2-cookie-secret" OAUTH2_PROXY_COOKIE_SECRE

echo "All secrets fetched successfully." >&2

# Output env file format when not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cat <<EOF
# Generated by fetch-gsm-secrets.sh — DO NOT COMMI
DOMAIN=${DOMAIN:-ide.kushnir.cloud}
GODADDY_KEY=${GODADDY_KEY}
GODADDY_SECRET=${GODADDY_SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD:-change-me}
ALLOWED_EMAIL_DOMAINS=${ALLOWED_EMAIL_DOMAINS:-*}
WORKSPACE_PATH=${WORKSPACE_PATH:-./workspace}
EOF
fi
