#!/usr/bin/env python3
"""
Grafana Dashboard Generator for Phase 3 Observability Spine

Generates comprehensive Grafana dashboards from metrics:
- Layer-by-layer latency breakdown (Cloudflare → Caddy → OAuth2 → App → Data)
- Error attribution dashboard (trace context-based error correlation)
- P50/P95/P99 percentile latency graphs
- Cache performance (Redis hit rate, evictions)
- Database performance (query latency, slow queries)
- System resource usage (CPU, memory, disk)
- SLO compliance tracking (99.99% availability, < 100ms p99)

Generated by: Phase 3 observability spine - TASK 10 (Grafana Dashboards)
Date: April 16, 2026
Version: 1.0.0
"""

import json
import time
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional

class GrafanaDashboard:
    """
    Generates Grafana dashboard JSON with proper structure and defaults.
    """
    
    def __init__(
        self,
        title: str,
        description: str,
        tags: List[str],
        timezone: str = "browser",
        refresh: str = "30s"
    ):
        self.title = title
        self.description = description
        self.tags = tags
        self.timezone = timezone
        self.refresh = refresh
        self.panels: List[Dict[str, Any]] = []
        self.next_grid_pos = {"x": 0, "y": 0, "w": 12, "h": 8}
    
    def add_panel(
        self,
        title: str,
        panel_type: str,
        targets: List[Dict[str, Any]],
        unit: str = "short",
        legend: Optional[Dict] = None,
        thresholds: Optional[List] = None,
        alert: Optional[Dict] = None
    ):
        """Add a panel to the dashboard."""
        panel = {
            "id": len(self.panels) + 1,
            "title": title,
            "type": panel_type,
            "targets": targets,
            "fieldConfig": {
                "defaults": {
                    "unit": unit,
                    "custom": {}
                }
            },
            "options": {},
            "gridPos": self.next_grid_pos.copy(),
        }
        
        if panel_type == "graph":
            panel["options"]["legend"] = legend or {
                "showLegend": True,
                "placement": "bottom"
            }
        
        if thresholds:
            panel["fieldConfig"]["defaults"]["thresholds"] = {
                "mode": "absolute",
                "steps": thresholds
            }
        
        if alert:
            panel["alert"] = alert
        
        self.panels.append(panel)
        
        # Move to next position
        self.next_grid_pos["x"] += 12
        if self.next_grid_pos["x"] >= 24:
            self.next_grid_pos["x"] = 0
            self.next_grid_pos["y"] += 8
    
    def to_json(self) -> Dict[str, Any]:
        """Export dashboard as JSON."""
        return {
            "dashboard": {
                "title": self.title,
                "description": self.description,
                "tags": self.tags,
                "timezone": self.timezone,
                "panels": self.panels,
                "refresh": self.refresh,
                "time": {
                    "from": "now-1h",
                    "to": "now"
                },
                "timepicker": {
                    "refresh_intervals": [
                        "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"
                    ]
                }
            },
            "overwrite": True
        }


def create_latency_breakdown_dashboard() -> Dict[str, Any]:
    """
    Create dashboard showing layer-by-layer latency breakdown.
    
    Visualizes latency at each layer:
    1. Cloudflare → Caddy
    2. Caddy → OAuth2-Proxy
    3. OAuth2-Proxy → Application
    4. Application → PostgreSQL
    5. Application → Redis
    """
    dashboard = GrafanaDashboard(
        title="Layer-by-Layer Latency Breakdown",
        description="Traces request journey through system with latency at each layer",
        tags=["observability", "latency", "performance"],
    )
    
    # Layer 1: Cloudflare to Caddy
    dashboard.add_panel(
        title="Cloudflare → Caddy Latency",
        panel_type="graph",
        targets=[
            {
                "expr": 'histogram_quantile(0.50, rate(cloudflare_latency_seconds_bucket[5m]))',
                "legendFormat": "p50"
            },
            {
                "expr": 'histogram_quantile(0.95, rate(cloudflare_latency_seconds_bucket[5m]))',
                "legendFormat": "p95"
            },
            {
                "expr": 'histogram_quantile(0.99, rate(cloudflare_latency_seconds_bucket[5m]))',
                "legendFormat": "p99"
            },
        ],
        unit="ms",
        thresholds=[
            {"value": 0, "color": "green"},
            {"value": 50, "color": "yellow"},
            {"value": 100, "color": "red"}
        ]
    )
    
    # Layer 2: Caddy to OAuth2
    dashboard.add_panel(
        title="Caddy → OAuth2-Proxy Latency",
        panel_type="graph",
        targets=[
            {
                "expr": 'histogram_quantile(0.50, rate(caddy_upstreams_request_duration_seconds_bucket{upstream="oauth2-proxy"}[5m]))',
                "legendFormat": "p50"
            },
            {
                "expr": 'histogram_quantile(0.95, rate(caddy_upstreams_request_duration_seconds_bucket{upstream="oauth2-proxy"}[5m]))',
                "legendFormat": "p95"
            },
            {
                "expr": 'histogram_quantile(0.99, rate(caddy_upstreams_request_duration_seconds_bucket{upstream="oauth2-proxy"}[5m]))',
                "legendFormat": "p99"
            },
        ],
        unit="ms",
    )
    
    # Layer 3: OAuth2 to Application
    dashboard.add_panel(
        title="OAuth2-Proxy → Application Latency",
        panel_type="graph",
        targets=[
            {
                "expr": 'histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{handler="app"}[5m]))',
                "legendFormat": "p50"
            },
            {
                "expr": 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler="app"}[5m]))',
                "legendFormat": "p95"
            },
            {
                "expr": 'histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler="app"}[5m]))',
                "legendFormat": "p99"
            },
        ],
        unit="ms",
    )
    
    # Layer 4: App to Database
    dashboard.add_panel(
        title="Application → PostgreSQL Latency",
        panel_type="graph",
        targets=[
            {
                "expr": 'histogram_quantile(0.50, rate(postgres_query_duration_seconds_bucket[5m]))',
                "legendFormat": "p50"
            },
            {
                "expr": 'histogram_quantile(0.95, rate(postgres_query_duration_seconds_bucket[5m]))',
                "legendFormat": "p95"
            },
            {
                "expr": 'histogram_quantile(0.99, rate(postgres_query_duration_seconds_bucket[5m]))',
                "legendFormat": "p99"
            },
        ],
        unit="ms",
    )
    
    # Layer 5: App to Cache
    dashboard.add_panel(
        title="Application → Redis Latency",
        panel_type="graph",
        targets=[
            {
                "expr": 'histogram_quantile(0.50, rate(redis_operation_duration_seconds_bucket[5m]))',
                "legendFormat": "p50"
            },
            {
                "expr": 'histogram_quantile(0.95, rate(redis_operation_duration_seconds_bucket[5m]))',
                "legendFormat": "p95"
            },
            {
                "expr": 'histogram_quantile(0.99, rate(redis_operation_duration_seconds_bucket[5m]))',
                "legendFormat": "p99"
            },
        ],
        unit="ms",
    )
    
    # Total end-to-end latency
    dashboard.add_panel(
        title="Total End-to-End Latency (p99)",
        panel_type="gauge",
        targets=[
            {
                "expr": 'histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))',
                "legendFormat": "p99"
            }
        ],
        unit="ms",
        thresholds=[
            {"value": 0, "color": "green"},
            {"value": 50, "color": "yellow"},
            {"value": 100, "color": "orange"},
            {"value": 500, "color": "red"}
        ]
    )
    
    return dashboard.to_json()


def create_error_attribution_dashboard() -> Dict[str, Any]:
    """
    Create dashboard for error attribution analysis.
    
    Shows which layer errors originate from via trace context.
    """
    dashboard = GrafanaDashboard(
        title="Error Attribution Dashboard",
        description="Identify error sources across all layers via distributed traces",
        tags=["observability", "errors", "debugging"],
    )
    
    # Error rate by layer
    dashboard.add_panel(
        title="Error Rate by Layer",
        panel_type="graph",
        targets=[
            {
                "expr": 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])',
                "legendFormat": "Application Errors"
            },
            {
                "expr": 'rate(postgres_errors_total[5m]) / rate(postgres_queries_total[5m])',
                "legendFormat": "Database Errors"
            },
            {
                "expr": 'rate(redis_operations_total{status="error"}[5m]) / rate(redis_operations_total[5m])',
                "legendFormat": "Cache Errors"
            },
        ],
        unit="percentunit",
    )
    
    # Top error messages (last 1h)
    dashboard.add_panel(
        title="Top Error Messages (Last 1h)",
        panel_type="table",
        targets=[
            {
                "expr": 'topk(10, count_over_time(log_errors_total[1h]) by (error_message))',
                "legendFormat": "{{ error_message }}"
            }
        ],
        unit="short",
    )
    
    # Errors by trace ID (for RCA)
    dashboard.add_panel(
        title="Recent Error Traces",
        panel_type="table",
        targets=[
            {
                "expr": 'topk(20, log_entries{level="error"}) by (trace_id, service)',
                "legendFormat": "{{ trace_id }} - {{ service }}"
            }
        ],
        unit="short",
    )
    
    # Error distribution by service
    dashboard.add_panel(
        title="Error Distribution by Service",
        panel_type="piechart",
        targets=[
            {
                "expr": 'sum by (service) (rate(log_entries{level="error"}[5m]))',
                "legendFormat": "{{ service }}"
            }
        ],
        unit="short",
    )
    
    return dashboard.to_json()


def create_slo_compliance_dashboard() -> Dict[str, Any]:
    """
    Create SLO compliance tracking dashboard.
    
    Monitors targets:
    - Availability: 99.99%
    - Latency p99: < 100ms
    - Error rate: < 0.1%
    """
    dashboard = GrafanaDashboard(
        title="SLO Compliance Dashboard",
        description="Real-time monitoring of SLO targets and compliance status",
        tags=["slo", "compliance", "production"],
    )
    
    # Availability SLO (99.99%)
    dashboard.add_panel(
        title="Availability SLO (Target: 99.99%)",
        panel_type="gauge",
        targets=[
            {
                "expr": '(1 - (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])))) * 100',
                "legendFormat": "Availability %"
            }
        ],
        unit="percent",
        thresholds=[
            {"value": 0, "color": "red"},
            {"value": 99.9, "color": "orange"},
            {"value": 99.95, "color": "yellow"},
            {"value": 99.99, "color": "green"}
        ]
    )
    
    # Latency p99 SLO (< 100ms)
    dashboard.add_panel(
        title="Latency p99 SLO (Target: < 100ms)",
        panel_type="gauge",
        targets=[
            {
                "expr": 'histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) * 1000',
                "legendFormat": "p99 Latency (ms)"
            }
        ],
        unit="ms",
        thresholds=[
            {"value": 0, "color": "green"},
            {"value": 50, "color": "yellow"},
            {"value": 100, "color": "orange"},
            {"value": 500, "color": "red"}
        ]
    )
    
    # Error rate SLO (< 0.1%)
    dashboard.add_panel(
        title="Error Rate SLO (Target: < 0.1%)",
        panel_type="gauge",
        targets=[
            {
                "expr": '(sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) * 100',
                "legendFormat": "Error Rate %"
            }
        ],
        unit="percent",
        thresholds=[
            {"value": 0, "color": "green"},
            {"value": 0.05, "color": "yellow"},
            {"value": 0.1, "color": "orange"},
            {"value": 1, "color": "red"}
        ]
    )
    
    # 30-day SLO history
    dashboard.add_panel(
        title="30-Day Availability History",
        panel_type="graph",
        targets=[
            {
                "expr": '(1 - (sum(increase(http_requests_total{status=~"5.."}[1d])) / sum(increase(http_requests_total[1d])))) * 100',
                "legendFormat": "Availability %"
            }
        ],
        unit="percent",
    )
    
    return dashboard.to_json()


def create_resource_utilization_dashboard() -> Dict[str, Any]:
    """
    Create system resource utilization dashboard.
    
    Tracks:
    - CPU usage per container
    - Memory usage per container
    - Disk I/O
    - Network bandwidth
    - PostgreSQL connections
    - Redis memory
    """
    dashboard = GrafanaDashboard(
        title="System Resource Utilization",
        description="Monitor CPU, memory, disk, and network resources",
        tags=["infrastructure", "resources", "performance"],
    )
    
    # CPU usage
    dashboard.add_panel(
        title="CPU Usage by Container",
        panel_type="graph",
        targets=[
            {
                "expr": 'rate(container_cpu_usage_seconds_total[5m]) * 100',
                "legendFormat": "{{ container_name }}"
            }
        ],
        unit="percent",
    )
    
    # Memory usage
    dashboard.add_panel(
        title="Memory Usage by Container",
        panel_type="graph",
        targets=[
            {
                "expr": 'container_memory_usage_bytes / (1024*1024)',
                "legendFormat": "{{ container_name }}"
            }
        ],
        unit="MB",
    )
    
    # Disk I/O
    dashboard.add_panel(
        title="Disk I/O Operations",
        panel_type="graph",
        targets=[
            {
                "expr": 'rate(node_disk_read_bytes_total[5m]) / (1024*1024)',
                "legendFormat": "Read MB/s"
            },
            {
                "expr": 'rate(node_disk_written_bytes_total[5m]) / (1024*1024)',
                "legendFormat": "Write MB/s"
            }
        ],
        unit="MBmol",
    )
    
    # Network bandwidth
    dashboard.add_panel(
        title="Network Bandwidth",
        panel_type="graph",
        targets=[
            {
                "expr": 'rate(node_network_receive_bytes_total[5m]) / (1024*1024)',
                "legendFormat": "Inbound MB/s"
            },
            {
                "expr": 'rate(node_network_transmit_bytes_total[5m]) / (1024*1024)',
                "legendFormat": "Outbound MB/s"
            }
        ],
        unit="MBmol",
    )
    
    return dashboard.to_json()


# Export all dashboards
DASHBOARDS = {
    "latency-breakdown": create_latency_breakdown_dashboard,
    "error-attribution": create_error_attribution_dashboard,
    "slo-compliance": create_slo_compliance_dashboard,
    "resource-utilization": create_resource_utilization_dashboard,
}


def export_dashboard(name: str, filepath: str):
    """Export dashboard to JSON file."""
    if name not in DASHBOARDS:
        raise ValueError(f"Unknown dashboard: {name}")
    
    dashboard_fn = DASHBOARDS[name]
    dashboard_json = dashboard_fn()
    
    with open(filepath, 'w') as f:
        json.dump(dashboard_json, f, indent=2)
    
    print(f"✅ Exported dashboard '{name}' to {filepath}")


if __name__ == '__main__':
    import sys
    
    # Export all dashboards
    for name in DASHBOARDS:
        filepath = f"dashboards/{name}.json"
        try:
            export_dashboard(name, filepath)
        except Exception as e:
            print(f"❌ Failed to export '{name}': {e}")
            sys.exit(1)
    
    print(f"\n✅ All {len(DASHBOARDS)} dashboards exported successfully")
