#!/usr/bin/env python3
"""
Load Testing Script with OpenTelemetry Integration

Validates system performance under load while recording OpenTelemetry traces.
Tests progression from 100 → 1000 requests per second with metrics collection.

Tests:
- Baseline latency (p50, p95, p99)
- Throughput validation
- Error rate
- Cache hit rate
- Database connection pool
- Memory growth
- SLO compliance

Generated by: Phase 3 observability spine - TASK 10 (Load Testing)
Date: April 16, 2026
Version: 1.0.0
"""

import asyncio
import json
import time
import sys
import logging
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from statistics import mean, median, stdev
import random
import string

try:
    import aiohttp
    import psutil
    from opentelemetry import trace, metrics
    from opentelemetry.exporter.jaeger import JaegerExporter
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import BatchSpanProcessor
except ImportError:
    print("❌ Missing dependencies. Install:")
    print("   pip install aiohttp psutil opentelemetry-api opentelemetry-exporter-jaeger")
    sys.exit(1)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)

# OpenTelemetry setup
jaeger_exporter = JaegerExporter(
    agent_host_name="localhost",
    agent_port=6831,
)
trace_provider = TracerProvider()
trace_provider.add_span_processor(BatchSpanProcessor(jaeger_exporter))
trace.set_tracer_provider(trace_provider)
tracer = trace.get_tracer(__name__)


@dataclass
class LoadTestResult:
    """Single request result."""
    timestamp: datetime
    latency_ms: float
    status_code: int
    success: bool
    error: Optional[str] = None
    trace_id: Optional[str] = None


@dataclass
class LoadTestStats:
    """Statistics for a load test phase."""
    phase: str
    target_rps: int
    actual_rps: float
    duration_seconds: float
    total_requests: int
    successful_requests: int
    error_requests: int
    latency_p50: float
    latency_p95: float
    latency_p99: float
    latency_min: float
    latency_max: float
    latency_mean: float
    error_rate: float
    memory_mb_start: float
    memory_mb_end: float
    memory_growth_mb: float


class LoadTester:
    """
    Load testing with OpenTelemetry tracing.
    """
    
    def __init__(
        self,
        base_url: str = "http://localhost:8080",
        jaeger_enabled: bool = True
    ):
        self.base_url = base_url
        self.tracer = tracer
        self.results: List[LoadTestResult] = []
        self.jaeger_enabled = jaeger_enabled
        self.process = psutil.Process()
    
    async def make_request(
        self,
        session: aiohttp.ClientSession,
        phase_name: str,
        request_id: int
    ) -> LoadTestResult:
        """Make a single HTTP request with tracing."""
        with self.tracer.start_as_current_span(
            f"load_test.{phase_name}.request",
            attributes={
                "phase": phase_name,
                "request_id": request_id,
            }
        ) as span:
            start_time = time.time()
            trace_id = span.get_span_context().trace_id
            
            try:
                # Vary endpoints to simulate realistic traffic
                endpoint = random.choice([
                    f"/api/projects/{random.randint(1, 100)}",
                    f"/api/workspaces/{random.randint(1, 50)}/files",
                    f"/api/extensions/metadata",
                    "/health",
                ])
                
                async with session.get(
                    f"{self.base_url}{endpoint}",
                    timeout=aiohttp.ClientTimeout(total=30),
                    headers={
                        "X-Trace-ID": str(trace_id),
                    }
                ) as response:
                    latency_ms = (time.time() - start_time) * 1000
                    status_code = response.status
                    
                    span.set_attribute("http.status_code", status_code)
                    span.set_attribute("http.latency_ms", latency_ms)
                    
                    success = 200 <= status_code < 300
                    
                    return LoadTestResult(
                        timestamp=datetime.now(timezone.utc),
                        latency_ms=latency_ms,
                        status_code=status_code,
                        success=success,
                        trace_id=str(trace_id),
                    )
            
            except asyncio.TimeoutError:
                latency_ms = (time.time() - start_time) * 1000
                span.set_attribute("http.error", "timeout")
                return LoadTestResult(
                    timestamp=datetime.now(timezone.utc),
                    latency_ms=latency_ms,
                    status_code=0,
                    success=False,
                    error="Request timeout",
                    trace_id=str(trace_id),
                )
            
            except Exception as e:
                latency_ms = (time.time() - start_time) * 1000
                span.set_attribute("http.error", str(e))
                return LoadTestResult(
                    timestamp=datetime.now(timezone.utc),
                    latency_ms=latency_ms,
                    status_code=0,
                    success=False,
                    error=str(e),
                    trace_id=str(trace_id),
                )
    
    async def run_phase(
        self,
        phase_name: str,
        target_rps: int,
        duration_seconds: int
    ) -> LoadTestStats:
        """
        Run a single load test phase.
        
        Args:
            phase_name: Name of the phase (e.g., "baseline", "100rps")
            target_rps: Target requests per second
            duration_seconds: How long to run the phase
        
        Returns:
            Statistics for the phase
        """
        logger.info(f"Starting phase '{phase_name}' - target {target_rps} RPS for {duration_seconds}s")
        
        self.results.clear()
        memory_start = self.process.memory_info().rss / (1024 * 1024)
        phase_start_time = time.time()
        
        async with aiohttp.ClientSession() as session:
            request_id = 0
            last_second = int(phase_start_time)
            requests_in_second = 0
            
            while time.time() - phase_start_time < duration_seconds:
                # Rate limiting: target N requests per second
                current_second = int(time.time())
                if current_second > last_second:
                    last_second = current_second
                    requests_in_second = 0
                
                # Create request with jitter
                request_id += 1
                result = await self.make_request(session, phase_name, request_id)
                self.results.append(result)
                requests_in_second += 1
                
                # Sleep to maintain target RPS
                expected_requests_per_sec = target_rps
                sleep_time = (1.0 / expected_requests_per_sec) - 0.01
                await asyncio.sleep(max(0, sleep_time))
                
                # Log progress
                if request_id % 100 == 0:
                    elapsed = time.time() - phase_start_time
                    actual_rps = request_id / elapsed
                    logger.debug(f"  Progress: {request_id} requests, {actual_rps:.1f} actual RPS")
        
        # Calculate statistics
        duration_actual = time.time() - phase_start_time
        memory_end = self.process.memory_info().rss / (1024 * 1024)
        
        latencies = [r.latency_ms for r in self.results]
        latencies_sorted = sorted(latencies)
        
        successful = [r for r in self.results if r.success]
        error_count = len([r for r in self.results if not r.success])
        
        stats = LoadTestStats(
            phase=phase_name,
            target_rps=target_rps,
            actual_rps=len(self.results) / duration_actual,
            duration_seconds=duration_actual,
            total_requests=len(self.results),
            successful_requests=len(successful),
            error_requests=error_count,
            latency_p50=self._percentile(latencies_sorted, 0.50),
            latency_p95=self._percentile(latencies_sorted, 0.95),
            latency_p99=self._percentile(latencies_sorted, 0.99),
            latency_min=min(latencies),
            latency_max=max(latencies),
            latency_mean=mean(latencies),
            error_rate=error_count / len(self.results) if self.results else 0,
            memory_mb_start=memory_start,
            memory_mb_end=memory_end,
            memory_growth_mb=memory_end - memory_start,
        )
        
        logger.info(f"Phase '{phase_name}' complete:")
        logger.info(f"  Actual RPS: {stats.actual_rps:.1f}")
        logger.info(f"  Latency: p50={stats.latency_p50:.1f}ms p95={stats.latency_p95:.1f}ms p99={stats.latency_p99:.1f}ms")
        logger.info(f"  Error Rate: {stats.error_rate*100:.2f}%")
        logger.info(f"  Memory Growth: {stats.memory_growth_mb:.1f} MB")
        
        return stats
    
    async def run_full_test(self) -> List[LoadTestStats]:
        """
        Run full load test progression.
        
        Progression:
        1. Baseline (10 RPS, 30s)
        2. Light load (50 RPS, 30s)
        3. Medium load (100 RPS, 60s)
        4. Heavy load (500 RPS, 60s)
        5. Peak load (1000 RPS, 60s)
        """
        phases = [
            ("baseline", 10, 30),
            ("light-load", 50, 30),
            ("medium-load", 100, 60),
            ("heavy-load", 500, 60),
            ("peak-load", 1000, 60),
        ]
        
        all_stats = []
        
        for phase_name, target_rps, duration in phases:
            try:
                stats = await self.run_phase(phase_name, target_rps, duration)
                all_stats.append(stats)
                
                # Validate SLOs after each phase
                self._validate_slos(stats)
                
                # Brief pause between phases
                await asyncio.sleep(5)
            
            except Exception as e:
                logger.error(f"Phase '{phase_name}' failed: {e}")
                return all_stats
        
        return all_stats
    
    def _percentile(self, sorted_values: List[float], percentile: float) -> float:
        """Calculate percentile from sorted values."""
        if not sorted_values:
            return 0.0
        idx = int(len(sorted_values) * percentile)
        return sorted_values[min(idx, len(sorted_values) - 1)]
    
    def _validate_slos(self, stats: LoadTestStats):
        """Validate SLO targets."""
        # Latency SLOs
        if stats.latency_p99 > 500:
            logger.warning(f"⚠️  p99 latency {stats.latency_p99:.1f}ms exceeds target 500ms")
        
        if stats.latency_p99 > 100 and stats.phase not in ["heavy-load", "peak-load"]:
            logger.warning(f"⚠️  p99 latency {stats.latency_p99:.1f}ms exceeds target 100ms")
        
        # Error rate SLOs
        if stats.error_rate > 0.01:  # 1%
            logger.warning(f"⚠️  Error rate {stats.error_rate*100:.2f}% exceeds target 1%")
        
        # Success under normal load
        if stats.phase == "baseline" and stats.error_rate > 0.001:
            logger.warning(f"⚠️  Baseline error rate {stats.error_rate*100:.2f}% (target: < 0.1%)")
    
    def print_report(self, stats_list: List[LoadTestStats]):
        """Print comprehensive load test report."""
        print("\n" + "=" * 100)
        print("LOAD TEST REPORT".center(100))
        print("=" * 100)
        
        print(f"\n{'Phase':<15} {'RPS Target':<12} {'RPS Actual':<12} {'p50 (ms)':<12} {'p95 (ms)':<12} {'p99 (ms)':<12} {'Error %':<10}")
        print("-" * 100)
        
        for stats in stats_list:
            print(
                f"{stats.phase:<15} "
                f"{stats.target_rps:<12} "
                f"{stats.actual_rps:<12.1f} "
                f"{stats.latency_p50:<12.1f} "
                f"{stats.latency_p95:<12.1f} "
                f"{stats.latency_p99:<12.1f} "
                f"{stats.error_rate*100:<10.2f}"
            )
        
        print("\n" + "=" * 100)
        print("DETAILED METRICS".center(100))
        print("=" * 100)
        
        for stats in stats_list:
            print(f"\n{stats.phase.upper()}")
            print(f"  Duration: {stats.duration_seconds:.1f}s")
            print(f"  Requests: {stats.total_requests} ({stats.successful_requests} successful, {stats.error_requests} errors)")
            print(f"  Latency: min={stats.latency_min:.1f}ms max={stats.latency_max:.1f}ms mean={stats.latency_mean:.1f}ms")
            print(f"  Memory: {stats.memory_mb_start:.1f}MB → {stats.memory_mb_end:.1f}MB (Δ{stats.memory_growth_mb:+.1f}MB)")
        
        print("\n" + "=" * 100)
        
        # Trace IDs for debugging
        if self.results:
            print("\nSample trace IDs for debugging (search in Jaeger):")
            sample_traces = random.sample([r.trace_id for r in self.results if r.trace_id], min(5, len(self.results)))
            for i, trace_id in enumerate(sample_traces, 1):
                print(f"  {i}. {trace_id}")
        
        print()


async def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Load test with OpenTelemetry tracing")
    parser.add_argument("--url", default="http://localhost:8080", help="Target URL")
    parser.add_argument("--output", default="load-test-results.json", help="Output file")
    parser.add_argument("--no-jaeger", action="store_true", help="Disable Jaeger tracing")
    
    args = parser.parse_args()
    
    logger.info(f"Starting load test against {args.url}")
    
    tester = LoadTester(base_url=args.url, jaeger_enabled=not args.no_jaeger)
    
    try:
        stats_list = await tester.run_full_test()
        
        # Print report
        tester.print_report(stats_list)
        
        # Save results to file
        results_dict = [asdict(s) for s in stats_list]
        with open(args.output, 'w') as f:
            json.dump(results_dict, f, indent=2, default=str)
        
        logger.info(f"✅ Results saved to {args.output}")
        
        # Exit with success if no SLO violations
        violations = [s for s in stats_list if s.error_rate > 0.01 or (s.latency_p99 > 100 and s.phase not in ["heavy-load", "peak-load"])]
        if violations:
            logger.warning(f"⚠️  {len(violations)} phase(s) had SLO violations")
            return 1
        
        return 0
    
    except Exception as e:
        logger.error(f"❌ Load test failed: {e}", exc_info=True)
        return 1


if __name__ == '__main__':
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
