#!/usr/bin/env python3
#
# PostgreSQL Query Log Parser with Trace Context Extraction
# Parses PostgreSQL logs and exports trace context to OpenTelemetry
#
# Generated by: Phase 3 observability spine - TASK 7 (PostgreSQL Query Tracing)

import os
import re
import json
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional, Tuple, List
import subprocess

class PostgreSQLQueryLogParser:
    """
    Parse PostgreSQL logs and extract trace context from query comments.
    
    Supports:
    - Trace ID extraction from /*+ trace_id='...' */
    - Span ID extraction from /*+ span_id='...' */
    - Slow query identification
    - Log aggregation and correlation
    """
    
    def __init__(self, log_file: str, trace_context_pattern: Optional[str] = None):
        """
        Initialize parser.
        
        Args:
            log_file: Path to PostgreSQL log file
            trace_context_pattern: Optional custom regex for trace context
        """
        self.log_file = log_file
        self.trace_context_pattern = trace_context_pattern or (
            r"/\*\+\s+trace_id='([^']+)'\s+span_id='([^']+)'\s+service='([^']+)'\s*\*/"
        )
        self.query_pattern = re.compile(
            r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\s+\[(\d+)\]:\s+\[(\d+)-(\d+)\]\s+.*?\s+"
            r"duration:\s+([\d.]+)\s+ms\s+statement:\s+(.*)",
            re.DOTALL
        )
        self.slow_queries: List[Dict] = []
        self.trace_correlations: Dict[str, Dict] = {}
    
    def extract_trace_context(self, query: str) -> Tuple[Optional[str], Optional[str], Optional[str]]:
        """
        Extract trace context from query comment.
        
        Returns: (trace_id, span_id, service)
        """
        match = re.search(self.trace_context_pattern, query)
        if match:
            return match.group(1), match.group(2), match.group(3)
        return None, None, None
    
    def parse_log_line(self, line: str) -> Optional[Dict]:
        """
        Parse a single log line and extract metadata.
        
        Returns: Dictionary with query metadata or None if not a query log
        """
        # Parse timestamp and query info
        timestamp_match = re.match(
            r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\s+\[(\d+)\]",
            line
        )
        
        if not timestamp_match:
            return None
        
        timestamp = timestamp_match.group(1)
        pid = timestamp_match.group(2)
        
        # Extract duration and query
        duration_match = re.search(r"duration:\s+([\d.]+)\s+ms", line)
        if not duration_match:
            return None
        
        duration_ms = float(duration_match.group(1))
        
        # Extract query text (everything after "statement:")
        statement_match = re.search(r"statement:\s+(.*)", line, re.DOTALL)
        if not statement_match:
            return None
        
        query = statement_match.group(1).strip()
        
        # Extract trace context
        trace_id, span_id, service = self.extract_trace_context(query)
        
        # Extract operation type
        operation = self._extract_operation_type(query)
        
        return {
            'timestamp': timestamp,
            'pid': pid,
            'duration_ms': duration_ms,
            'query': query,
            'trace_id': trace_id,
            'span_id': span_id,
            'service': service,
            'operation': operation,
            'is_slow': duration_ms > 1000,
        }
    
    def _extract_operation_type(self, query: str) -> str:
        """Extract SQL operation type from query."""
        query_upper = query.upper().split('/*')[0].strip()  # Remove comments
        
        if query_upper.startswith('SELECT'):
            return 'select'
        elif query_upper.startswith('INSERT'):
            return 'insert'
        elif query_upper.startswith('UPDATE'):
            return 'update'
        elif query_upper.startswith('DELETE'):
            return 'delete'
        elif query_upper.startswith('CREATE'):
            return 'create'
        elif query_upper.startswith('DROP'):
            return 'drop'
        elif query_upper.startswith('ALTER'):
            return 'alter'
        elif query_upper.startswith('BEGIN'):
            return 'begin'
        elif query_upper.startswith('COMMIT'):
            return 'commit'
        elif query_upper.startswith('ROLLBACK'):
            return 'rollback'
        else:
            return 'unknown'
    
    def parse_file(self) -> List[Dict]:
        """Parse entire log file and return list of query records."""
        queries = []
        
        try:
            with open(self.log_file, 'r') as f:
                buffer = ''
                for line in f:
                    # PostgreSQL logs can span multiple lines
                    buffer += line
                    
                    # Check if this is a complete log entry (ends with duration)
                    if 'ms\n' in buffer and 'duration:' in buffer:
                        parsed = self.parse_log_line(buffer)
                        if parsed:
                            queries.append(parsed)
                            
                            # Track slow queries
                            if parsed['is_slow']:
                                self.slow_queries.append(parsed)
                            
                            # Track trace correlations
                            if parsed['trace_id']:
                                if parsed['trace_id'] not in self.trace_correlations:
                                    self.trace_correlations[parsed['trace_id']] = {
                                        'trace_id': parsed['trace_id'],
                                        'queries': [],
                                        'total_duration_ms': 0,
                                        'min_duration_ms': float('inf'),
                                        'max_duration_ms': 0,
                                        'operations': set(),
                                    }
                                
                                corr = self.trace_correlations[parsed['trace_id']]
                                corr['queries'].append(parsed)
                                corr['total_duration_ms'] += parsed['duration_ms']
                                corr['min_duration_ms'] = min(corr['min_duration_ms'], parsed['duration_ms'])
                                corr['max_duration_ms'] = max(corr['max_duration_ms'], parsed['duration_ms'])
                                corr['operations'].add(parsed['operation'])
                        
                        buffer = ''
        
        except FileNotFoundError:
            print(f"ERROR: Log file not found: {self.log_file}", file=sys.stderr)
            return []
        except Exception as e:
            print(f"ERROR: Failed to parse log file: {e}", file=sys.stderr)
            return []
        
        return queries
    
    def export_to_json(self, output_file: str) -> None:
        """Export parsed queries and correlations to JSON."""
        export_data = {
            'metadata': {
                'timestamp': datetime.now().isoformat(),
                'log_file': self.log_file,
                'total_queries': len(self.slow_queries),
            },
            'slow_queries': self.slow_queries,
            'trace_correlations': {
                trace_id: {
                    **data,
                    'operations': list(data['operations']),
                    'query_count': len(data['queries']),
                }
                for trace_id, data in self.trace_correlations.items()
            },
        }
        
        with open(output_file, 'w') as f:
            json.dump(export_data, f, indent=2, default=str)
        
        print(f"✅ Exported {len(self.slow_queries)} slow queries to {output_file}")
    
    def export_to_prometheus(self, output_file: str) -> None:
        """Export metrics in Prometheus format."""
        metrics = []
        
        # Total slow queries
        metrics.append(f"# HELP pg_slow_queries_total Total slow queries")
        metrics.append(f"# TYPE pg_slow_queries_total counter")
        metrics.append(f"pg_slow_queries_total {len(self.slow_queries)}")
        
        # Queries by operation type
        operations = {}
        for query in self.slow_queries:
            op = query['operation']
            operations[op] = operations.get(op, 0) + 1
        
        metrics.append(f"# HELP pg_slow_queries_by_operation Slow queries by operation")
        metrics.append(f"# TYPE pg_slow_queries_by_operation gauge")
        for op, count in operations.items():
            metrics.append(f'pg_slow_queries_by_operation{{operation="{op}"}} {count}')
        
        # Average query duration
        if self.slow_queries:
            avg_duration = sum(q['duration_ms'] for q in self.slow_queries) / len(self.slow_queries)
            metrics.append(f"# HELP pg_slow_queries_avg_duration Average slow query duration")
            metrics.append(f"# TYPE pg_slow_queries_avg_duration gauge")
            metrics.append(f"pg_slow_queries_avg_duration {avg_duration:.2f}")
        
        # Queries with trace context
        traced_queries = sum(1 for q in self.slow_queries if q['trace_id'])
        metrics.append(f"# HELP pg_traced_queries Total queries with trace context")
        metrics.append(f"# TYPE pg_traced_queries gauge")
        metrics.append(f"pg_traced_queries {traced_queries}")
        
        with open(output_file, 'w') as f:
            f.write('\n'.join(metrics) + '\n')
        
        print(f"✅ Exported Prometheus metrics to {output_file}")
    
    def print_summary(self) -> None:
        """Print summary statistics."""
        print("\n" + "="*80)
        print("PostgreSQL Query Log Analysis Summary")
        print("="*80)
        print(f"Log file: {self.log_file}")
        print(f"Slow queries found: {len(self.slow_queries)}")
        print(f"Queries with trace context: {len(self.trace_correlations)}")
        
        if self.slow_queries:
            print("\n📊 Slow Query Statistics:")
            durations = [q['duration_ms'] for q in self.slow_queries]
            print(f"  Min: {min(durations):.2f}ms")
            print(f"  Max: {max(durations):.2f}ms")
            print(f"  Avg: {sum(durations) / len(durations):.2f}ms")
            
            print("\n📈 Slow Queries by Operation:")
            ops = {}
            for q in self.slow_queries:
                op = q['operation']
                ops[op] = ops.get(op, 0) + 1
            for op, count in sorted(ops.items(), key=lambda x: x[1], reverse=True):
                print(f"  {op}: {count}")
        
        if self.trace_correlations:
            print("\n🔗 Trace Correlation Summary:")
            print(f"  Unique traces: {len(self.trace_correlations)}")
            
            durations = [
                data['total_duration_ms']
                for data in self.trace_correlations.values()
            ]
            print(f"  Total duration by trace:")
            print(f"    Min: {min(durations):.2f}ms")
            print(f"    Max: {max(durations):.2f}ms")
            print(f"    Avg: {sum(durations) / len(durations):.2f}ms")
        
        print("\n" + "="*80)


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Parse PostgreSQL logs and extract trace context'
    )
    parser.add_argument(
        'log_file',
        help='Path to PostgreSQL log file'
    )
    parser.add_argument(
        '--json',
        help='Export to JSON file',
        metavar='FILE'
    )
    parser.add_argument(
        '--prometheus',
        help='Export to Prometheus metrics file',
        metavar='FILE'
    )
    parser.add_argument(
        '--summary',
        action='store_true',
        help='Print summary statistics'
    )
    
    args = parser.parse_args()
    
    # Parse log file
    parser_instance = PostgreSQLQueryLogParser(args.log_file)
    queries = parser_instance.parse_file()
    
    print(f"✅ Parsed {len(queries)} queries")
    print(f"✅ Found {len(parser_instance.slow_queries)} slow queries")
    print(f"✅ Found {len(parser_instance.trace_correlations)} unique traces")
    
    # Export formats
    if args.json:
        parser_instance.export_to_json(args.json)
    
    if args.prometheus:
        parser_instance.export_to_prometheus(args.prometheus)
    
    if args.summary or not (args.json or args.prometheus):
        parser_instance.print_summary()


if __name__ == '__main__':
    main()
