#!/bin/bash
# scripts/qa-service-bootstrap.sh - QA Service Account Authentication & Session Setup
# Purpose: Non-interactive OAuth session bootstrap for automated testing

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
QA_SERVICE_EMAIL="${QA_SERVICE_EMAIL:-qa-service@ide.kushnir.cloud}"
QA_SERVICE_ROLE="${QA_SERVICE_ROLE:-developer}"
QA_SESSION_DIR="${QA_SESSION_DIR:-.qa-sessions}"
QA_SESSION_TOKEN_FILE="${QA_SESSION_DIR}/session-token"
QA_COOKIEJAR="${QA_SESSION_DIR}/cookies.jar"
QA_OAUTH_STATE="${QA_SESSION_DIR}/oauth-state"

# Test environment
TEST_AUTH_MODE="${TEST_AUTH_MODE:-mock}" # mock, headless, or interactive

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

log_info() {
  echo "[QA-SESSION] $1"
}

log_error() {
  echo "[QA-SESSION] ERROR: $1" >&2
}

# Create session directory structure
init_session_dir() {
  mkdir -p "$QA_SESSION_DIR"
  chmod 700 "$QA_SESSION_DIR"
  log_info "Session directory initialized: $QA_SESSION_DIR"
}

# Generate session token (UUID format)
generate_session_token() {
  python3 -c "import uuid; print(str(uuid.uuid4()))" 2>/dev/null || \
    uuidgen 2>/dev/null || \
    openssl rand -hex 16
}

# ─────────────────────────────────────────────────────────────────────────────
# AUTHENTICATION MODE: Mock (Development/CI)
# ─────────────────────────────────────────────────────────────────────────────
# Simulates a valid OAuth session without hitting the real OAuth2 provider
mock_auth() {
  log_info "Using MOCK authentication (development mode)"
  
  # Generate mock session token
  local session_token=$(generate_session_token)
  echo "$session_token" > "$QA_SESSION_TOKEN_FILE"
  
  # Generate mock OAuth state
  local oauth_state=$(generate_session_token)
  echo "$oauth_state" > "$QA_OAUTH_STATE"
  
  # Create mock cookie for oauth2-proxy session
  {
    echo "# This file was generated by qa-service-bootstrap.sh (mock mode)"
    echo "# Cookie Name: oauth2-proxy-session"
    echo "# Expires: 86400 seconds"
    echo ".ide.kushnir.cloud	TRUE	/	FALSE	$(($(date +%s) + 86400))	_oauth2_proxy	$session_token"
  } > "$QA_COOKIEJAR"
  
  # Log this session
  {
    echo "$(date -I'seconds') | QA_SESSION_CREATED | email:$QA_SERVICE_EMAIL | mode:mock | token:${session_token:0:8}..."
  } >> audit/qa-sessions.log
  
  log_info "Mock session established for: $QA_SERVICE_EMAIL"
  echo "$session_token"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# AUTHENTICATION MODE: Headless (Real OAuth2 Provider)
# ─────────────────────────────────────────────────────────────────────────────
# Uses Resource Owner Password Credentials flow for non-interactive auth
# Requires: QA_SERVICE_PASSWORD environment variable
headless_auth() {
  log_info "Using HEADLESS authentication (real OAuth2 provider)"
  
  # Validate prerequisite
  if [[ -z "${QA_SERVICE_PASSWORD:-}" ]]; then
    log_error "QA_SERVICE_PASSWORD must be set for headless auth"
    return 1
  fi
  
  # Get OAuth2 provider details from config
  local oauth_client_id="${OAUTH2_PROXY_CLIENT_ID:-}"
  local oauth_client_secret="${OAUTH2_PROXY_CLIENT_SECRET:-}"
  
  if [[ -z "$oauth_client_id" ]] || [[ -z "$oauth_client_secret" ]]; then
    log_error "OAuth2 credentials not configured"
    return 1
  fi
  
  # Attempt Resource Owner Password Credentials flow
  local token_response=$(curl -s -X POST \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=password" \
    -d "client_id=$oauth_client_id" \
    -d "client_secret=$oauth_client_secret" \
    -d "username=$QA_SERVICE_EMAIL" \
    -d "password=$QA_SERVICE_PASSWORD" \
    "http://localhost:4180/oauth2/token" 2>/dev/null || echo "")
  
  if [[ -z "$token_response" ]] || ! echo "$token_response" | grep -q "access_token"; then
    log_error "OAuth2 headless auth failed"
    return 1
  fi
  
  # Extract access token
  local access_token=$(echo "$token_response" | python3 -c "import sys, json; print(json.load(sys.stdin).get('access_token', ''))" 2>/dev/null || echo "")
  
  if [[ -z "$access_token" ]]; then
    log_error "Could not extract access token from OAuth2 response"
    return 1
  fi
  
  # Store session
  echo "$access_token" > "$QA_SESSION_TOKEN_FILE"
  
  # Log this session
  {
    echo "$(date -I'seconds') | QA_SESSION_CREATED | email:$QA_SERVICE_EMAIL | mode:headless | provider:oauth2 | token:${access_token:0:8}..."
  } >> audit/qa-sessions.log
  
  log_info "Headless OAuth2 session established for: $QA_SERVICE_EMAIL"
  echo "$access_token"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# Session Validation
# ─────────────────────────────────────────────────────────────────────────────
validate_session() {
  if [[ ! -f "$QA_SESSION_TOKEN_FILE" ]]; then
    log_error "No session token found"
    return 1
  fi
  
  local session_token=$(cat "$QA_SESSION_TOKEN_FILE")
  
  # Validate token format (should be non-empty)
  if [[ -z "$session_token" ]]; then
    log_error "Session token is empty"
    return 1
  fi
  
  log_info "Session token validated: ${session_token:0:8}..."
  return 0
}

# Get current session token
get_session_token() {
  if [[ ! -f "$QA_SESSION_TOKEN_FILE" ]]; then
    log_error "No active session. Run bootstrap first."
    return 1
  fi
  cat "$QA_SESSION_TOKEN_FILE"
}

# Revoke session
revoke_session() {
  if [[ -f "$QA_SESSION_TOKEN_FILE" ]]; then
    local token=$(cat "$QA_SESSION_TOKEN_FILE")
    
    # Log revocation
    {
      echo "$(date -I'seconds') | QA_SESSION_REVOKED | email:$QA_SERVICE_EMAIL | token:${token:0:8}..."
    } >> audit/qa-sessions.log
    
    rm -f "$QA_SESSION_TOKEN_FILE"
    rm -f "$QA_COOKIEJAR"
    rm -f "$QA_OAUTH_STATE"
    
    log_info "QA session revoked"
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

case "${1:-bootstrap}" in
  bootstrap)
    init_session_dir
    
    case "$TEST_AUTH_MODE" in
      mock)
        mock_auth
        ;;
      headless)
        headless_auth
        ;;
      *)
        log_error "Unknown auth mode: $TEST_AUTH_MODE (use: mock or headless)"
        exit 1
        ;;
    esac
    
    # Validate the session
    if validate_session; then
      log_info "✅ QA session bootstrap complete"
      exit 0
    else
      log_error "❌ QA session validation failed"
      exit 1
    fi
    ;;
    
  validate)
    validate_session
    ;;
    
  token)
    get_session_token
    ;;
    
  revoke)
    revoke_session
    ;;
    
  *)
    echo "Usage: $0 [bootstrap|validate|token|revoke]"
    echo ""
    echo "Commands:"
    echo "  bootstrap  - Initialize QA service session (default)"
    echo "  validate   - Check if session is valid"
    echo "  token      - Print current session token"
    echo "  revoke     - Clear session token"
    echo ""
    echo "Environment Variables:"
    echo "  TEST_AUTH_MODE      - mock (default) or headless"
    echo "  QA_SERVICE_EMAIL    - QA user email (default: qa-service@ide.kushnir.cloud)"
    echo "  QA_SERVICE_PASSWORD - Password for headless auth (required for headless mode)"
    exit 1
    ;;
esac
