#!/usr/bin/env python3
"""
Redis Instrumentation Wrapper - OpenTelemetry Integration

Provides distributed tracing for Redis cache operations via OpenTelemetry.
- Automatic span creation for GET/SET/DEL/SCAN operations
- Cache hit/miss detection and tracking
- Latency measurement per operation
- W3C Trace Context propagation

Generated by: Phase 3 observability spine - TASK 8 (Redis Instrumentation)
Date: April 16, 2026
Version: 1.0.0
"""

import os
import json
import time
import logging
from typing import Any, Optional, Dict, List
from contextvars import ContextVar

import redis
from opentelemetry import trace, metrics
from opentelemetry.trace import Status, StatusCode
from opentelemetry.exporter.prometheus import PrometheusMetricReader
from prometheus_client import Counter, Histogram, Gauge

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(levelname)s: %(message)s'
)
logger = logging.getLogger(__name__)

# OpenTelemetry setup
tracer = trace.get_tracer(__name__)
metrics_reader = PrometheusMetricReader()
meter = metrics.get_meter(__name__)

# Context variables for trace propagation
current_trace_id: ContextVar[Optional[str]] = ContextVar('trace_id', default=None)
current_span_id: ContextVar[Optional[str]] = ContextVar('span_id', default=None)

# Prometheus metrics
cache_operations_total = Counter(
    'redis_operations_total',
    'Total number of Redis operations',
    ['operation', 'status'],
    registry=metrics_reader.registry if hasattr(metrics_reader, 'registry') else None
)

cache_hits_total = Counter(
    'redis_cache_hits_total',
    'Total number of cache hits',
    ['key_pattern'],
)

cache_misses_total = Counter(
    'redis_cache_misses_total',
    'Total number of cache misses',
    ['key_pattern'],
)

cache_operation_duration = Histogram(
    'redis_operation_duration_seconds',
    'Duration of Redis operations in seconds',
    ['operation'],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0)
)

cache_hit_rate = Gauge(
    'redis_cache_hit_rate',
    'Current cache hit rate (0.0-1.0)',
    ['key_pattern'],
)


class InstrumentedRedisClient:
    """
    Redis client wrapper with OpenTelemetry instrumentation.
    
    Automatically creates spans for all cache operations with:
    - Operation type (GET, SET, DEL, SCAN)
    - Key pattern
    - Hit/miss indicator
    - Latency measurement
    - Trace context propagation
    """
    
    def __init__(
        self,
        host: str = 'localhost',
        port: int = 6379,
        db: int = 0,
        password: Optional[str] = None,
        decode_responses: bool = True,
        socket_keepalive: bool = True,
        socket_keepalive_options: Optional[Dict] = None,
    ):
        """Initialize instrumented Redis client."""
        self.client = redis.Redis(
            host=host,
            port=port,
            db=db,
            password=password,
            decode_responses=decode_responses,
            socket_keepalive=socket_keepalive,
            socket_keepalive_options=socket_keepalive_options or {}
        )
        
        # Metrics tracking
        self.operation_count = {'hits': 0, 'misses': 0}
        self.operation_latencies: Dict[str, List[float]] = {}
        
        logger.info(f"Instrumented Redis client initialized: {host}:{port}")
    
    def _get_trace_context(self) -> tuple[Optional[str], Optional[str]]:
        """Get current trace context from context variables."""
        trace_id = current_trace_id.get()
        span_id = current_span_id.get()
        return trace_id, span_id
    
    def _set_trace_context(self, trace_id: str, span_id: str):
        """Set trace context in context variables."""
        current_trace_id.set(trace_id)
        current_span_id.set(span_id)
    
    def get(self, key: str, trace_id: Optional[str] = None, span_id: Optional[str] = None) -> Any:
        """
        Get value from cache with tracing.
        
        Args:
            key: Cache key
            trace_id: Optional trace ID for correlation
            span_id: Optional span ID for correlation
        
        Returns:
            Cached value or None if not found
        """
        if trace_id is None:
            trace_id = current_trace_id.get()
        if span_id is None:
            span_id = current_span_id.get()
        
        with tracer.start_as_current_span("redis.cache.get") as span:
            span.set_attribute("redis.operation", "GET")
            span.set_attribute("redis.key", key)
            if trace_id:
                span.set_attribute("trace_id", trace_id)
            if span_id:
                span.set_attribute("span_id", span_id)
            
            start_time = time.time()
            try:
                value = self.client.get(key)
                duration = time.time() - start_time
                
                # Determine hit/miss
                hit = value is not None
                status = "hit" if hit else "miss"
                
                span.set_attribute("redis.hit_miss", status)
                span.set_attribute("redis.duration_ms", duration * 1000)
                span.set_attribute("redis.value_bytes", len(str(value)) if value else 0)
                
                # Update metrics
                cache_operations_total.labels(operation='GET', status=status).inc()
                if hit:
                    self.operation_count['hits'] += 1
                    cache_hits_total.labels(key_pattern=self._extract_pattern(key)).inc()
                else:
                    self.operation_count['misses'] += 1
                    cache_misses_total.labels(key_pattern=self._extract_pattern(key)).inc()
                
                cache_operation_duration.labels(operation='GET').observe(duration)
                
                # Update hit rate
                total = self.operation_count['hits'] + self.operation_count['misses']
                if total > 0:
                    hit_rate = self.operation_count['hits'] / total
                    cache_hit_rate.labels(key_pattern=self._extract_pattern(key)).set(hit_rate)
                
                span.set_status(Status(StatusCode.OK))
                logger.debug(f"GET {key}: {status} ({duration*1000:.2f}ms)")
                
                return value
            
            except Exception as e:
                span.set_status(Status(StatusCode.ERROR, str(e)))
                span.record_exception(e)
                cache_operations_total.labels(operation='GET', status='error').inc()
                logger.error(f"GET {key} failed: {e}")
                raise
    
    def set(
        self,
        key: str,
        value: Any,
        ex: Optional[int] = None,
        trace_id: Optional[str] = None,
        span_id: Optional[str] = None
    ) -> bool:
        """
        Set value in cache with tracing.
        
        Args:
            key: Cache key
            value: Value to cache
            ex: Optional expiration time in seconds
            trace_id: Optional trace ID for correlation
            span_id: Optional span ID for correlation
        
        Returns:
            True if successful
        """
        if trace_id is None:
            trace_id = current_trace_id.get()
        if span_id is None:
            span_id = current_span_id.get()
        
        with tracer.start_as_current_span("redis.cache.set") as span:
            span.set_attribute("redis.operation", "SET")
            span.set_attribute("redis.key", key)
            span.set_attribute("redis.ttl_seconds", ex or 0)
            if trace_id:
                span.set_attribute("trace_id", trace_id)
            if span_id:
                span.set_attribute("span_id", span_id)
            
            start_time = time.time()
            try:
                result = self.client.set(key, value, ex=ex)
                duration = time.time() - start_time
                
                span.set_attribute("redis.duration_ms", duration * 1000)
                span.set_attribute("redis.value_bytes", len(str(value)))
                
                # Update metrics
                cache_operations_total.labels(operation='SET', status='success').inc()
                cache_operation_duration.labels(operation='SET').observe(duration)
                
                span.set_status(Status(StatusCode.OK))
                logger.debug(f"SET {key}: success ({duration*1000:.2f}ms)")
                
                return result
            
            except Exception as e:
                span.set_status(Status(StatusCode.ERROR, str(e)))
                span.record_exception(e)
                cache_operations_total.labels(operation='SET', status='error').inc()
                logger.error(f"SET {key} failed: {e}")
                raise
    
    def delete(self, *keys, trace_id: Optional[str] = None, span_id: Optional[str] = None) -> int:
        """
        Delete keys from cache with tracing.
        
        Args:
            keys: Cache keys to delete
            trace_id: Optional trace ID for correlation
            span_id: Optional span ID for correlation
        
        Returns:
            Number of keys deleted
        """
        if trace_id is None:
            trace_id = current_trace_id.get()
        if span_id is None:
            span_id = current_span_id.get()
        
        with tracer.start_as_current_span("redis.cache.delete") as span:
            span.set_attribute("redis.operation", "DEL")
            span.set_attribute("redis.keys_count", len(keys))
            for i, key in enumerate(keys[:10]):  # Log first 10 keys
                span.set_attribute(f"redis.key_{i}", key)
            if trace_id:
                span.set_attribute("trace_id", trace_id)
            if span_id:
                span.set_attribute("span_id", span_id)
            
            start_time = time.time()
            try:
                result = self.client.delete(*keys)
                duration = time.time() - start_time
                
                span.set_attribute("redis.duration_ms", duration * 1000)
                span.set_attribute("redis.deleted_count", result)
                
                # Update metrics
                cache_operations_total.labels(operation='DEL', status='success').inc()
                cache_operation_duration.labels(operation='DEL').observe(duration)
                
                span.set_status(Status(StatusCode.OK))
                logger.debug(f"DEL {len(keys)} keys: {result} deleted ({duration*1000:.2f}ms)")
                
                return result
            
            except Exception as e:
                span.set_status(Status(StatusCode.ERROR, str(e)))
                span.record_exception(e)
                cache_operations_total.labels(operation='DEL', status='error').inc()
                logger.error(f"DEL {len(keys)} keys failed: {e}")
                raise
    
    def scan(
        self,
        cursor: int = 0,
        match: Optional[str] = None,
        count: int = 10,
        trace_id: Optional[str] = None,
        span_id: Optional[str] = None
    ) -> tuple[int, List[str]]:
        """
        Scan keys with pattern matching and tracing.
        
        Args:
            cursor: Scan cursor (0 to start)
            match: Pattern to match keys
            count: Approximate number of keys per iteration
            trace_id: Optional trace ID for correlation
            span_id: Optional span ID for correlation
        
        Returns:
            Tuple of (new_cursor, keys)
        """
        if trace_id is None:
            trace_id = current_trace_id.get()
        if span_id is None:
            span_id = current_span_id.get()
        
        with tracer.start_as_current_span("redis.cache.scan") as span:
            span.set_attribute("redis.operation", "SCAN")
            span.set_attribute("redis.cursor", cursor)
            span.set_attribute("redis.match_pattern", match or "*")
            span.set_attribute("redis.count", count)
            if trace_id:
                span.set_attribute("trace_id", trace_id)
            if span_id:
                span.set_attribute("span_id", span_id)
            
            start_time = time.time()
            try:
                result = self.client.scan(cursor, match=match, count=count)
                duration = time.time() - start_time
                
                span.set_attribute("redis.duration_ms", duration * 1000)
                span.set_attribute("redis.keys_found", len(result[1]))
                
                # Update metrics
                cache_operations_total.labels(operation='SCAN', status='success').inc()
                cache_operation_duration.labels(operation='SCAN').observe(duration)
                
                span.set_status(Status(StatusCode.OK))
                logger.debug(f"SCAN {match or '*'}: {len(result[1])} keys ({duration*1000:.2f}ms)")
                
                return result
            
            except Exception as e:
                span.set_status(Status(StatusCode.ERROR, str(e)))
                span.record_exception(e)
                cache_operations_total.labels(operation='SCAN', status='error').inc()
                logger.error(f"SCAN failed: {e}")
                raise
    
    def mget(self, keys: List[str], trace_id: Optional[str] = None, span_id: Optional[str] = None) -> List[Any]:
        """
        Get multiple values with tracing.
        
        Args:
            keys: Cache keys
            trace_id: Optional trace ID for correlation
            span_id: Optional span ID for correlation
        
        Returns:
            List of values
        """
        if trace_id is None:
            trace_id = current_trace_id.get()
        if span_id is None:
            span_id = current_span_id.get()
        
        with tracer.start_as_current_span("redis.cache.mget") as span:
            span.set_attribute("redis.operation", "MGET")
            span.set_attribute("redis.keys_count", len(keys))
            if trace_id:
                span.set_attribute("trace_id", trace_id)
            if span_id:
                span.set_attribute("span_id", span_id)
            
            start_time = time.time()
            try:
                values = self.client.mget(keys)
                duration = time.time() - start_time
                
                # Count hits/misses
                hits = sum(1 for v in values if v is not None)
                misses = len(values) - hits
                
                span.set_attribute("redis.duration_ms", duration * 1000)
                span.set_attribute("redis.hits", hits)
                span.set_attribute("redis.misses", misses)
                
                # Update metrics
                cache_operations_total.labels(operation='MGET', status='success').inc()
                cache_operation_duration.labels(operation='MGET').observe(duration)
                
                span.set_status(Status(StatusCode.OK))
                logger.debug(f"MGET {len(keys)} keys: {hits} hits ({duration*1000:.2f}ms)")
                
                return values
            
            except Exception as e:
                span.set_status(Status(StatusCode.ERROR, str(e)))
                span.record_exception(e)
                cache_operations_total.labels(operation='MGET', status='error').inc()
                logger.error(f"MGET failed: {e}")
                raise
    
    def ping(self) -> bool:
        """Health check."""
        try:
            return self.client.ping()
        except Exception as e:
            logger.error(f"Redis ping failed: {e}")
            return False
    
    def close(self):
        """Close Redis connection."""
        try:
            self.client.close()
            logger.info("Redis connection closed")
        except Exception as e:
            logger.error(f"Error closing Redis connection: {e}")
    
    def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics."""
        try:
            info = self.client.info('stats')
            total_ops = self.operation_count['hits'] + self.operation_count['misses']
            hit_rate = self.operation_count['hits'] / total_ops if total_ops > 0 else 0.0
            
            return {
                'total_operations': total_ops,
                'hits': self.operation_count['hits'],
                'misses': self.operation_count['misses'],
                'hit_rate': hit_rate,
                'redis_info': info
            }
        except Exception as e:
            logger.error(f"Failed to get stats: {e}")
            return {}
    
    @staticmethod
    def _extract_pattern(key: str) -> str:
        """Extract pattern from key for metrics grouping."""
        # Simple heuristic: take first part before colon
        if ':' in key:
            return key.split(':')[0]
        return key[:20]  # First 20 chars as pattern


# Module-level instance
_client: Optional[InstrumentedRedisClient] = None


def get_client(
    host: str = 'localhost',
    port: int = 6379,
    db: int = 0,
    **kwargs
) -> InstrumentedRedisClient:
    """
    Get or create instrumented Redis client.
    
    Args:
        host: Redis host
        port: Redis port
        db: Database number
        **kwargs: Additional arguments for RedisClient
    
    Returns:
        InstrumentedRedisClient instance
    """
    global _client
    if _client is None:
        _client = InstrumentedRedisClient(host=host, port=port, db=db, **kwargs)
    return _client


if __name__ == '__main__':
    # Test instrumentation
    logger.info("Testing Redis instrumentation...")
    
    client = get_client()
    
    # Test set/get
    client.set('test:key', 'test_value', ex=3600)
    value = client.get('test:key')
    logger.info(f"Got value: {value}")
    
    # Test cache miss
    missing = client.get('nonexistent:key')
    logger.info(f"Missing key result: {missing}")
    
    # Print stats
    stats = client.get_stats()
    logger.info(f"Cache stats: {json.dumps(stats, indent=2, default=str)}")
    
    client.close()
    logger.info("Test complete")
