/**
 * @file        apps/frontend/src/services/session-snapshot/service.ts
 * @module      collaboration/session-persistence
 * @description Session snapshot capture and restore service with SLA tracking
 */

import {
  SessionSnapshot,
  SnapshotFile,
  SnapshotTerminal,
  RestoreOptions,
  RestoreResult,
  SnapshotLayout,
  SnapshotDebugSession,
} from './types.js';
import {
  SessionSnapshotStorage,
  getSessionSnapshotStorage,
} from './storage.js';

/**
 * Simple event emitter for snapshot service
 */
class SimpleEventEmitter {
  private listeners = new Map<string, Set<Function>>();

  on(event: string, listener: Function): void {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, new Set());
    }
    this.listeners.get(event)!.add(listener);
  }

  off(event: string, listener: Function): void {
    this.listeners.get(event)?.delete(listener);
  }

  emit(event: string, data?: any): void {
    this.listeners.get(event)?.forEach((listener) => listener(data));
  }
}

/**
 * Capture metrics
 */
export interface CaptureMetrics {
  captureStartMs: number;
  captureEndMs: number;
  totalCaptureTimeMs: number;
  filesCollected: number;
  terminalsCollected: number;
  estimatedRestoreTimeMs: number;
}

/**
 * SessionSnapshotService: Manages full session snapshot capture and restore
 */
export class SessionSnapshotService extends SimpleEventEmitter {
  private storage: SessionSnapshotStorage | null = null;
  private isInitialized = false;
  private currentWorkspaceId: string | null = null;
  private captureMetrics: CaptureMetrics | null = null;

  // SLA targets (ms)
  private readonly IMMEDIATE_RESTORE_THRESHOLD = 500;
  private readonly QUICK_RESTORE_THRESHOLD = 2000;

  /**
   * Initialize service
   */
  async initialize(workspaceId: string): Promise<void> {
    if (this.isInitialized) return;

    try {
      this.storage = await getSessionSnapshotStorage();
      this.currentWorkspaceId = workspaceId;
      this.isInitialized = true;
      console.log(
        `[SessionSnapshotService] Initialized for workspace ${workspaceId}`
      );
      this.emit('initialized', { workspaceId });
    } catch (error) {
      console.error(
        '[SessionSnapshotService] Initialization failed:',
        error
      );
      throw error;
    }
  }

  /**
   * Capture current session state
   */
  async captureSnapshot(label?: string): Promise<SessionSnapshot> {
    if (!this.storage || !this.currentWorkspaceId) {
      throw new Error('Service not initialized');
    }

    const startTime = performance.now();
    const metrics: CaptureMetrics = {
      captureStartMs: startTime,
      captureEndMs: 0,
      totalCaptureTimeMs: 0,
      filesCollected: 0,
      terminalsCollected: 0,
      estimatedRestoreTimeMs: 0,
    };

    try {
      // Collect current state from VS Code API
      const layout = this.captureLayout();
      const files = this.captureOpenFiles();
      const terminals = this.captureTerminals();
      const debugSessions = this.captureDebugSessions();
      const extensions = this.captureExtensions();
      const settings = this.captureSettings();
      const fileTree = this.captureFileTree();
      const recentFiles = this.captureRecentFiles();
      const bookmarks = this.captureBookmarks();

      metrics.filesCollected = files.length;
      metrics.terminalsCollected = terminals.length;

      // Create snapshot
      const snapshot: SessionSnapshot = {
        id: '', // Will be generated by storage
        workspaceId: this.currentWorkspaceId,
        userId: this.getCurrentUserId(),
        createdAt: Date.now(),
        updatedAt: Date.now(),
        version: 1,
        label,
        layout,
        openFiles: files,
        selectedFile: this.getSelectedFile(),
        terminals,
        debugSessions,
        enabledExtensions: extensions.enabled,
        disabledExtensions: extensions.disabled,
        settings,
        fileTreeExpanded: fileTree,
        recentFiles,
        bookmarks,
        restoreableIn: 'immediate',
        estimatedRestoreTimeMs: 100,
        size: 0,
      };

      // Estimate restore time based on content
      snapshot.estimatedRestoreTimeMs = this.estimateRestoreTime(snapshot);
      snapshot.restoreableIn = this.categorizeRestoreability(
        snapshot.estimatedRestoreTimeMs
      );
      // Calculate size after object is fully defined
      snapshot.size = JSON.stringify(snapshot).length;

      // Save to storage
      await this.storage.saveSnapshot(snapshot);

      metrics.captureEndMs = performance.now();
      metrics.totalCaptureTimeMs = metrics.captureEndMs - startTime;
      this.captureMetrics = metrics;

      console.log(
        `[SessionSnapshotService] Captured snapshot in ${metrics.totalCaptureTimeMs.toFixed(2)}ms`
      );

      this.emit('snapshot-captured', {
        snapshotId: snapshot.id,
        metrics,
        label,
      });

      return snapshot;
    } catch (error) {
      console.error('[SessionSnapshotService] Capture failed:', error);
      throw error;
    }
  }

  /**
   * Restore session from snapshot
   */
  async restoreSnapshot(
    snapshotId: string,
    options: RestoreOptions = {}
  ): Promise<RestoreResult> {
    if (!this.storage) throw new Error('Service not initialized');

    const startTime = performance.now();

    try {
      const snapshot = await this.storage.loadSnapshot(snapshotId);
      if (!snapshot) {
        throw new Error(`Snapshot ${snapshotId} not found`);
      }

      const result: RestoreResult = {
        snapshotId,
        success: true,
        filesRestored: 0,
        terminalsRestored: 0,
        settingsRestored: false,
        totalTimeMs: 0,
      };

      // Restore components based on options
      const includeFiles = options.includeFiles !== false;
      const includeTerminals = options.includeTerminals !== false;
      const includeDebug = options.includeDebug !== false;
      const includeSettings = options.includeSettings !== false;
      const includeExtensions = options.includeExtensions !== false;

      if (includeFiles) {
        await this.restoreFiles(snapshot.openFiles, snapshot.selectedFile);
        result.filesRestored = snapshot.openFiles.length;
      }

      if (includeTerminals) {
        await this.restoreTerminals(snapshot.terminals);
        result.terminalsRestored = snapshot.terminals.length;
      }

      if (includeDebug) {
        await this.restoreDebugSessions(snapshot.debugSessions);
      }

      if (includeSettings) {
        await this.restoreSettings(snapshot.settings, includeExtensions);
        result.settingsRestored = true;
      }

      if (includeExtensions) {
        await this.restoreExtensions(
          snapshot.enabledExtensions,
          snapshot.disabledExtensions
        );
      }

      // Restore layout
      await this.restoreLayout(snapshot.layout);

      result.totalTimeMs = performance.now() - startTime;

      console.log(
        `[SessionSnapshotService] Restored snapshot in ${result.totalTimeMs.toFixed(2)}ms`
      );

      this.emit('snapshot-restored', result);

      return result;
    } catch (error) {
      console.error('[SessionSnapshotService] Restore failed:', error);

      return {
        snapshotId,
        success: false,
        filesRestored: 0,
        terminalsRestored: 0,
        settingsRestored: false,
        totalTimeMs: performance.now() - startTime,
        error: String(error),
      };
    }
  }

  /**
   * List snapshots for current workspace
   */
  async listSnapshots(page = 1, pageSize = 10) {
    if (!this.storage || !this.currentWorkspaceId) {
      throw new Error('Service not initialized');
    }

    return this.storage.listSnapshots(this.currentWorkspaceId, page, pageSize);
  }

  /**
   * Delete snapshot
   */
  async deleteSnapshot(snapshotId: string): Promise<void> {
    if (!this.storage) throw new Error('Service not initialized');
    await this.storage.deleteSnapshot(snapshotId);
    this.emit('snapshot-deleted', { snapshotId });
  }

  /**
   * Get capture metrics from last snapshot
   */
  getMetrics(): CaptureMetrics | null {
    return this.captureMetrics;
  }

  /**
   * Private helper: Capture layout state
   */
  private captureLayout(): SnapshotLayout {
    // In real implementation, read from VS Code API
    return {
      mainPanelWidth: 0.7,
      sidePanelWidth: 0.25,
      bottomPanelHeight: 0.25,
      sidebarVisible: true,
      bottomPanelVisible: true,
      activityBarPosition: 'left',
      focusedPanel: 'main',
    };
  }

  /**
   * Private helper: Capture open files
   */
  private captureOpenFiles(): SnapshotFile[] {
    // In real implementation, enumerate from VS Code editors
    return [];
  }

  /**
   * Private helper: Capture terminals
   */
  private captureTerminals(): SnapshotTerminal[] {
    // In real implementation, get terminals from VS Code API
    return [];
  }

  /**
   * Private helper: Capture debug sessions
   */
  private captureDebugSessions(): SnapshotDebugSession[] {
    // In real implementation, get debug state from VS Code
    return [];
  }

  /**
   * Private helper: Capture extension state
   */
  private captureExtensions(): {
    enabled: string[];
    disabled: string[];
  } {
    return { enabled: [], disabled: [] };
  }

  /**
   * Private helper: Capture settings
   */
  private captureSettings(): Record<string, any> {
    return {};
  }

  /**
   * Private helper: Get selected file
   */
  private getSelectedFile(): string | null {
    return null;
  }

  /**
   * Private helper: Capture file tree expansion
   */
  private captureFileTree(): string[] {
    return [];
  }

  /**
   * Private helper: Capture recent files
   */
  private captureRecentFiles(): string[] {
    return [];
  }

  /**
   * Private helper: Capture bookmarks
   */
  private captureBookmarks(): Array<{ path: string; label?: string }> {
    return [];
  }

  /**
   * Private helper: Get current user ID
   */
  private getCurrentUserId(): string {
    return 'user-default';
  }

  /**
   * Private helper: Estimate restore time based on content
   */
  private estimateRestoreTime(snapshot: SessionSnapshot): number {
    let baseTime = 100; // Base 100ms
    baseTime += snapshot.openFiles.length * 10; // 10ms per file
    baseTime += snapshot.terminals.length * 50; // 50ms per terminal
    baseTime += snapshot.debugSessions.length * 100; // 100ms per debug session
    return Math.min(baseTime, 5000); // Cap at 5s
  }

  /**
   * Private helper: Categorize restore time
   */
  private categorizeRestoreability(
    timeMs: number
  ): 'immediate' | 'quick' | 'full' {
    if (timeMs <= this.IMMEDIATE_RESTORE_THRESHOLD) return 'immediate';
    if (timeMs <= this.QUICK_RESTORE_THRESHOLD) return 'quick';
    return 'full';
  }

  /**
   * Private helper: Restore files
   */
  private async restoreFiles(
    files: SnapshotFile[],
    selectedFile: string | null
  ): Promise<void> {
    // In real implementation, open files via VS Code API
  }

  /**
   * Private helper: Restore terminals
   */
  private async restoreTerminals(terminals: SnapshotTerminal[]): Promise<void> {
    // In real implementation, recreate terminals via VS Code API
  }

  /**
   * Private helper: Restore debug sessions
   */
  private async restoreDebugSessions(
    sessions: SnapshotDebugSession[]
  ): Promise<void> {
    // In real implementation, restore debug state via VS Code API
  }

  /**
   * Private helper: Restore settings
   */
  private async restoreSettings(
    settings: Record<string, any>,
    includeExtensions: boolean
  ): Promise<void> {
    // In real implementation, update VS Code settings
  }

  /**
   * Private helper: Restore extensions
   */
  private async restoreExtensions(
    enabled: string[],
    disabled: string[]
  ): Promise<void> {
    // In real implementation, enable/disable extensions via VS Code API
  }

  /**
   * Private helper: Restore layout
   */
  private async restoreLayout(layout: SnapshotLayout): Promise<void> {
    // In real implementation, apply layout via VS Code API
  }
}

/**
 * Global service instance
 */
let serviceInstance: SessionSnapshotService | null = null;

/**
 * Get global service instance
 */
export async function getSessionSnapshotService(
  workspaceId: string
): Promise<SessionSnapshotService> {
  if (!serviceInstance) {
    serviceInstance = new SessionSnapshotService();
    await serviceInstance.initialize(workspaceId);
  }
  return serviceInstance;
}
