#!/bin/bash
# Placeholder for user provisioning script
# Template will be rendered by Terraform with actual values

# User provisioning via Matrix admin API
# Called after successful OIDC login to create account if not exists

echo "User provisioning script placeholder"
echo "Will be generated by Terraform module matrix-sso"
