apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://code-server-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://code-server-loki:3100
    jsonData:
      maxLines: 1000
    version: 1
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://code-server-tempo:3200
    version: 1
    editable: true
