# Database Environment Configuration
# Generated by Terraform: terraform/templates/database.env.tpl
# Source: terraform/modules/database
# Date: $(date)

# PostgreSQL Connection
POSTGRES_HOST=${postgres_host}
POSTGRES_PORT=${postgres_port}
POSTGRES_DB=${postgres_db}
POSTGRES_USER=${postgres_user}
# POSTGRES_PASSWORD: Set via AWS Secrets Manager (Phase 3 Week 2)
POSTGRES_URL="postgresql://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@$${POSTGRES_HOST}:$${POSTGRES_PORT}/$${POSTGRES_DB}"

# Redis Connection
REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}
REDIS_URL="redis://$${REDIS_HOST}:$${REDIS_PORT}/0"

# Application Configuration
ENVIRONMENT=${environment}
DATABASE_INITIALIZED=true
DEPLOYMENT_ENVIRONMENT=${environment}
