#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @file        scripts/observability/demo-logging-to-issues.py
# @module      observability/demo
# @description Demonstrate infrastructure logging → GitHub issues end-to-end
# @owner       platform

import sys
import io

# Fix Windows console encoding issue (charmap -> UTF-8)
if sys.stdout.encoding and sys.stdout.encoding.lower() in ('cp1252', 'charmap', 'ascii'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
# @status      active

import sys
import os
import json
import time
import urllib.request
import urllib.error
from datetime import datetime

def get_github_token():
    """Get GitHub token from environment or gh CLI"""
    token = os.environ.get('GITHUB_TOKEN')
    if not token:
        try:
            import subprocess
            result = subprocess.run(['gh', 'auth', 'token'], capture_output=True, text=True)
            if result.returncode == 0:
                token = result.stdout.strip()
        except:
            pass
    return token

def create_github_issue(title, body, labels, repo="kushin77/code-server"):
    """Create a GitHub issue via REST API"""
    token = get_github_token()
    if not token:
        print(f"[ERROR] GITHUB_TOKEN not set and could not get token from gh CLI")
        print(f"[ERROR] Set token: export GITHUB_TOKEN=<your_token>")
        return None
    
    payload = {
        "title": title,
        "body": body,
        "labels": labels
    }
    
    url = f"https://api.github.com/repos/{repo}/issues"
    
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode('utf-8'),
            headers={
                'Authorization': f'token {token}',
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github+json',
                'User-Agent': 'logging-demo-script'
            },
            method='POST'
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            result = json.loads(response.read().decode('utf-8'))
            issue_number = result.get('number')
            if issue_number:
                print(f"[INFO] ✓ Created GitHub issue #{issue_number}")
                print(f"[INFO]   URL: https://github.com/{repo}/issues/{issue_number}")
                return issue_number
            else:
                print(f"[ERROR] Response missing issue number")
                return None
                
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8')
        print(f"[ERROR] HTTP {e.code}: {error_body}")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to create issue: {e}")
        return None

def main():
    demo_namespace = f"demo-logs-{int(time.time())}"
    repo = "kushin77/code-server"
    
    print("[INFO] ════════════════════════════════════════════════════════════════════════════")
    print("[INFO] LOG PIPELINE DEMONSTRATION: Infrastructure Events → GitHub Issues")
    print("[INFO] ════════════════════════════════════════════════════════════════════════════")
    print(f"[INFO]")
    print(f"[INFO] Demo Namespace: {demo_namespace}")
    print(f"[INFO] Target Repo: {repo}")
    print(f"[INFO] Timestamp: {datetime.utcnow().isoformat()}Z")
    print(f"[INFO]")
    
    # Issue 1: Terraform failure
    print("[INFO] Creating Issue 1: Terraform Deployment Failure")
    create_github_issue(
        title="[AUTO-TRIAGE] terraform: Terraform apply failed - Resource conflict",
        body="""## Automated Issue from Infrastructure Logs

**Severity**: P1  
**Source**: terraform-apply  
**Detected**: """ + datetime.utcnow().isoformat() + """Z  
**Demo Namespace**: """ + demo_namespace + """  

### Error Pattern
```
ERROR: Resource conflict - aws_instance.primary already exists in state.
Manual intervention required. Stack: terraform/modules/compute.tf:42
```

### Detection
This issue was automatically created by the logging pipeline.
In production, Terraform apply failures would trigger GitHub issues automatically
within 5 minutes of occurrence, allowing the team to react quickly.

### Root Cause Analysis
- State file corruption or manual infrastructure modifications
- Concurrent terraform apply operations (race condition)
- IaC versioning mismatch between environments

### Next Steps
1. Verify infrastructure state: `terraform state list`
2. Check for running operations: `ps aux | grep terraform`
3. If safe, refresh state: `terraform refresh`
4. Implement lock mechanism to prevent concurrent applies

---
**Auto-generated by Logging Demo Pipeline**
""",
        labels=["error-triage", "P1", "logging-demo", "automated", "terraform"]
    )
    time.sleep(1)
    
    # Issue 2: Failover event
    print("[INFO] Creating Issue 2: Infrastructure Failover Event")
    create_github_issue(
        title="[AUTO-TRIAGE] failover: Primary host DOWN - Replica failover in progress",
        body="""## Automated Issue from Infrastructure Logs

**Severity**: P0  
**Source**: haproxy-monitor  
**Detected**: """ + datetime.utcnow().isoformat() + """Z  
**Demo Namespace**: """ + demo_namespace + """  
**Incident Start**: Now  
**RTO (Recovery Time Objective)**: ~45 seconds  

### Incident Details
```
Primary host 192.168.168.31 DOWN
- Health check failed 3 consecutive times
- Failing over to replica 192.168.168.42
- All sessions being redirected to replica
```

### Impact
- ⚠️ Brief service interruption (< 1 min) during failover
- ✓ Data integrity maintained (stateless sessions on replica)
- ✓ Authentication state preserved in Redis

### Automated Response
1. [✓] Detected: Primary health check failed
2. [✓] Initiated: Failover to replica 192.168.168.42
3. [✓] Updated: DNS/load balancer routing
4. [⏳] In Progress: Draining existing connections

### Investigation Required
- [ ] SSH to 192.168.168.31 and check logs
- [ ] Verify Docker daemon is running
- [ ] Check network connectivity
- [ ] Review recent deployments or changes
- [ ] Once recovered: Run full regression test suite

### Prevention
- Implement better alerting thresholds
- Add pre-checks before health failures
- Automate recovery (already in progress)

---
**P0 Incident - Immediate Investigation Required**
""",
        labels=["error-triage", "P0", "logging-demo", "automated", "failover", "incident"]
    )
    time.sleep(1)
    
    # Issue 3: System errors
    print("[INFO] Creating Issue 3: Multiple System Errors Detected")
    create_github_issue(
        title="[AUTO-TRIAGE] system: Kernel panic and container failures detected",
        body="""## Automated Issue from Infrastructure Logs

**Severity**: P1  
**Source**: syslog  
**Detected**: """ + datetime.utcnow().isoformat() + """Z  
**Demo Namespace**: """ + demo_namespace + """  

### Logged Events
```
1. kernel panic: attempting to kill init!
2. docker: container code-server exited with code 137 (OOMKilled)
3. auth: 5 failed login attempts from 203.0.113.42 in 30 seconds
4. postgresql: connection timeout after 30 seconds waiting for lock
```

### Correlation Analysis
Multiple infrastructure components failing suggests:
- **Likely Cause**: Memory pressure on host (OOMKilled is strong signal)
- **Secondary**: Database lock contention / slow queries
- **Security**: Brute force attempt (5 failed logins in 30s)

### Remediation Steps
1. **Immediate**: Check memory on host
   ```bash
   ssh akushnir@192.168.168.31
   free -h
   top -b -n1 | head -20
   ```

2. **Investigate kernel panic**: `journalctl -xb`

3. **Check PostgreSQL locks**:
   ```sql
   SELECT * FROM pg_locks;
   SELECT query FROM pg_stat_activity WHERE query_start < now() - interval '30s';
   ```

4. **Security**: Review auth logs
   ```bash
   grep "failed login" /var/log/auth.log | tail -20
   ```

5. **Docker**: Restart container
   ```bash
   docker compose restart code-server
   ```

### Long-term Actions
- [ ] Increase host memory allocation
- [ ] Add memory monitoring to Prometheus
- [ ] Implement query optimization for slow queries
- [ ] Add rate limiting to auth endpoints

---
**Requires Human Investigation - Not Auto-Recoverable**
""",
        labels=["error-triage", "P1", "logging-demo", "automated", "system", "performance"]
    )
    time.sleep(1)
    
    # Issue 4: Kubernetes failure
    print("[INFO] Creating Issue 4: Kubernetes Pod CrashLoopBackOff")
    create_github_issue(
        title="[AUTO-TRIAGE] kubernetes: Pod CrashLoopBackOff - Port binding conflict",
        body="""## Automated Issue from Infrastructure Logs

**Severity**: P1  
**Source**: kubernetes  
**Pod**: code-server-xyz  
**Namespace**: default  
**Detected**: """ + datetime.utcnow().isoformat() + """Z  
**Demo Namespace**: """ + demo_namespace + """  

### Pod Status
```
Pod CrashLoopBackOff
Container: code-server
Exit Code: 2
Last Restart: 45 seconds ago
Restart Count: 12
```

### Error Message
```
FATAL: Cannot bind to port 8080: Address already in use
```

### Root Causes (in order of likelihood)
1. **Port already bound** (most likely)
   - Another container/process using port 8080
   - Stale connection not cleaned up after pod restart

2. **Race condition during pod startup**
   - Multiple pods starting simultaneously

3. **ConfigMap/volume mount issue**
   - Missing or corrupt port configuration

### Troubleshooting
1. **Check if port is actually bound**:
   ```bash
   kubectl exec -it code-server-xyz -- lsof -i :8080
   kubectl exec -it code-server-xyz -- netstat -tlnp | grep 8080
   ```

2. **Check node resources**:
   ```bash
   kubectl describe node <node-name>
   ```

3. **Review pod events**:
   ```bash
   kubectl describe pod code-server-xyz
   ```

4. **Check pod logs**:
   ```bash
   kubectl logs code-server-xyz --previous  # See last exit
   kubectl logs code-server-xyz --tail=50
   ```

### Automatic Recovery Attempts
- [x] Detected CrashLoop (3+ failures)
- [x] Created GitHub issue
- [ ] Manual intervention required
- [ ] Will NOT auto-restart (prevent cascade failures)

### Fix Steps
1. Terminate existing code-server pods to free port
2. Increase readiness probe initial delay
3. Add port conflict detection to startup script
4. Redeploy pod

---
**Action Required: Manual pod restart after fixing port conflict**
""",
        labels=["error-triage", "P1", "logging-demo", "automated", "kubernetes", "container"]
    )
    
    print(f"[INFO]")
    print(f"[INFO] ════════════════════════════════════════════════════════════════════════════")
    print(f"[INFO] ✓ DEMONSTRATION COMPLETE")
    print(f"[INFO] ════════════════════════════════════════════════════════════════════════════")
    print(f"[INFO]")
    print(f"[INFO] Summary:")
    print(f"[INFO]   - Created 4 automated GitHub issues from simulated infrastructure events")
    print(f"[INFO]   - Each issue includes context, severity, root cause analysis, and next steps")
    print(f"[INFO]   - Issues are labeled: logging-demo, error-triage, and severity (P0/P1)")
    print(f"[INFO]")
    print(f"[INFO] In production:")
    print(f"[INFO]   1. All infrastructure logs flow to Loki continuously")
    print(f"[INFO]   2. Error patterns are detected and clustered automatically")
    print(f"[INFO]   3. Similar errors update existing issues (no duplicate spam)")
    print(f"[INFO]   4. GitHub issues are created within 5 minutes of first occurrence")
    print(f"[INFO]   5. On-call team receives immediate alerts via GitHub notifications")
    print(f"[INFO]")
    print(f"[INFO] View the created issues:")
    print(f"[INFO]   https://github.com/{repo}/issues?labels=logging-demo")
    print(f"[INFO]")

if __name__ == "__main__":
    main()
